### ISSUE TITLE
After Install/Repair in 1.2.5, multi-boot (from original) broken

### ISSUE THREAD

**Issue by hwchoy** [TeamShinkansen/Hakchi2-CE#100]
I was able to multi-boot fine in 1.2.4.  From my US SNES Classic, I was able to switch to NES mode using a NES .hsqs file until I did the Install/Repair in 1.2.5.  It doesn't seem to reboot when I try to select NES from my SNES menu.  Screen goes black (instead of hakchi splash screen like before) and returns to SNES menu.  However, when I power down and back up, it then switches me to NES mode.  Switching back to SNES mode from NES menu is still fine.

**Comment by daPhie79** [comment]
this is a known issue if that's what i think it is. we should address this in 1.2.6 hopefully!

**Comment by ryguy2010** [comment]
I have this issue also. Tried to reinstall from scratch and it didn't fix the issue.

**Comment by bslenul** [comment]
https://www.reddit.com/r/miniSNESmods/comments/8m532c/anyone_else_having_multiboot_issues_on_hakchi_ce/dzlvri5/

Or just wait for a fix ;)

**Comment by daPhie79** [comment]
it should be fixed by now in hakchi image.
