### ISSUE TITLE
Feature Request - Option to delete/replace kernel backup stored in NAND

### ISSUE THREAD

**Issue by hwchoy** [TeamShinkansen/Hakchi2-CE#101]
I had previously run hakchi CE 1.2.X and my kernel was backed up into NAND (by the way, where/how can I find it?).  However, my SNES Classic was at that time running on an older kernel and firmware.  I flashed the newer firmware into NAND-B (Flash decrypted system software) successfully and using an older version of hakchi, I flashed the newer kernel too.

After playing with hakchi CE on it a little, I decided to uninstall it for the time being.  Out of curiosity, I decided to dump my kernel (both with hakchi CE and an older one), and I see that the MD5 result was that of my original kernel.  I was hoping to keep the newer kernel as the one backed up.

**Comment by daPhie79** [comment]
if you want to backup the current state of your mini, there are options in `Kernel > Advanced` submenu :)

**Comment by KMFDManic** [comment]
@hwchoy As daPhie79 stated, you can easily dump the kernel via the submenu.  At that point, simply copy and paste and back it up to a location of your choosing.  I keep a few different kernels backed up from my systems.  If you need any other help, let me know.
