### ISSUE TITLE
unexpected network udp traffic

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#102]
Hi there,

since I got strange errors while leaving hackchi on my laptop. i figured out there alot of udp connections opening. i guess (not investigated yet) its about the internal updater and not some data collecting thing.

i would recommend to just start the updater on programmstart and then suspend or terminate that procedure...

my firewall detects this as a attack and forces to shutdown the network port. -.-

**Comment by skogaby** [comment]
It’s not the auto updater. The UDP connections are likely Hakchi polling for the actual console. It listens for UDP packets from the SNES that advertise its presence on the network.

**Comment by ghost** [comment]
what about a toggle on and off about that "feature". i dont have that device connected through network ?

**Comment by DanTheMan827** [comment]
you can't turn the feature off, the classic simulates a network adapter of its own over the usb connection and syncs with ssh/ftp
