### ISSUE TITLE
[Feature request] Bios manager (including a beautiful mockup!).

### ISSUE THREAD

**Issue by bslenul** [TeamShinkansen/Hakchi2-CE#103]
Hey TeamShinkansen :)

A question that really comes back often is "How do I install bios?", there's multiple ways to do it (FTP, hmod, options menu) but I think that would be awesome if a "Bios manager" was included directly in hakchi2 CE.

This is how I imaging it: you put your bios files/folders in `\hakchi2\bios` folder, then you go to `Tools > Bios manager` and you have a window like this that let you upload to (or download from) `/etc/libretro/system`:

![bios_manager](https://user-images.githubusercontent.com/33353403/40886163-75f4ad18-6733-11e8-9963-f3770bb65f36.png)

This way it wouldnt require any hmod installation and it would be really noob friendly.

**Comment by daPhie79** [comment]
good idea!

**Comment by ghost** [comment]
I just use the Bios importmodule from KMFDManic but thats a good feature for non advanced users ;)
