### ISSUE TITLE
[ERROR] Select Core "System String"

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#104]
while importing an .nds game an error dialog showing up:
`Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.InvalidCastException: Das Objekt des Typs "System.String" kann nicht in Typ "CoreInfo" umgewandelt werden.
   bei com.clusterrr.hakchi_gui.SelectCoreDialog.buttonApply_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2650.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
hakchi
    Assembly-Version: 3.2.5.0.
    Win32-Version: 3.2.5.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/hakchi.exe.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2634.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2634.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 11.0.0.0.
    Win32-Version: 3.2.5.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/hakchi.exe.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2623.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2623.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
hakchi.resources
    Assembly-Version: 3.2.2.0.
    Win32-Version: 3.2.2.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/languages/de-DE/hakchi.resources.DLL.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
AutoUpdater.NET
    Assembly-Version: 1.4.7.0.
    Win32-Version: 3.2.5.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/hakchi.exe.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2558.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
ProgressODoom
    Assembly-Version: 1.0.6711.39475.
    Win32-Version: 3.2.5.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/hakchi.exe.
----------------------------------------
Renci.SshNet
    Assembly-Version: 2017.0.0.0.
    Win32-Version: 3.2.5.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/hakchi.exe.
----------------------------------------
DnsUtils
    Assembly-Version: 1.0.0.0.
    Win32-Version: 3.2.5.0.
    CodeBase: file:///C:/TEMP/SNES/hakchi2_CE/hakchi.exe.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

`
`
InvalidCastException
Das Objekt des Typs "System.String" kann nicht in Typ "CoreInfo" umgewandelt werden.
   bei System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   bei System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   bei com.clusterrr.hakchi_gui.Tasks.AddGamesTask.UpdateListView(Tasker tasker, Object syncObject)
   bei com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\TEMP\SNES\hakchi2_CE (portable mode)
Loading configuration
Starting, version: 1.2.5
CoreCollection loading indexes from cache: Done!
Loading C:\TEMP\SNES\hakchi2_CE\data\nescarts.xml
Loading C:\TEMP\SNES\hakchi2_CE\data\snescarts.xml
SNES XML loading done, 786 roms total
[Upgrade] No upgrade action needed
NES XML loading done, 2150 roms total
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.112.19-madmonkey, script v1.0.4-116
Downloading motd file, URL: https://teamshinkansen.github.io/motd.md
Der Remotename konnte nicht aufgelöst werden: 'teamshinkansen.github.io'
Saving selected games
Saving configuration
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromList
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Saving selected games
Saving configuration
.Executing task: GameTask.DeleteGames
Tasker completed all tasks, conclusion: Success
.Executing task: AddGamesTask.AddGames
Saving application "CLV-S-UOCGJ" as CLV-S-UOCGJ
Saving application "Contra 4" as CLV-S-UOCGJ
Executing task: AddGamesTask.UpdateListView
Closing main form
Saving selected games
Saving configuration
--- End of DEBUGLOG.TXT content ---

USED CORES:KMFDManic-NESC-SNESC-Cores.5-31-18
USED HACKCHI CE_ 1.2.5
`

**Comment by daPhie79** [comment]
i'm not sure if i understood the error log, but that should be fixed in 3.3.0
