### ISSUE TITLE
Ability to save folder structure as you can with presets

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#105]
Today I just lost my folder structure because i thought it saved with my preset.

So, please add that as it would be a useful feature.

**Comment by KMFDManic** [comment]
@gingerbeardman For now, if it is pertinent to your current set-up, you can follow my tip on having backed up folder structures, at:

https://github.com/TeamShinkansen/hakchi2/issues/228

**Comment by DanTheMan827** [comment]
Sorry, I mistakenly re-opened this issue

this was implemented with #203

**Comment by gingerbeardman** [comment]
Thanks all!
