### ISSUE TITLE
Reset button combination has no effect

### ISSUE THREAD

**Issue by GiovanH** [TeamShinkansen/Hakchi2-CE#107]
On the latest release, using the settings -> controller hacks -> use button combination to reset feature has no effect. Possible issue with the clovercon module?

**Comment by YonatanAhituv** [comment]
@GiovanH It works for me (and I also have clovercon installed). However, I had to disable the controller hack and re-enable it to get it working. Can you try it and see if it works for you?

**Comment by GiovanH** [comment]
I've tried that. I've also tried reinstalling the clovercon driver from source. 

I'm happy to provide any additional details or logs that may help.

**Comment by YonatanAhituv** [comment]
@GiovanH I know this may sound like too much, but you're holding down + select right?

I just need to make sure it's a bug with hakchi.

**Comment by DanTheMan827** [comment]
Closed because of age, if this still applies, please open another issue
