### ISSUE TITLE
wifi hmod on usb-host

### ISSUE THREAD

**Issue by adamcarter1** [TeamShinkansen/Hakchi2-CE#108]
I have my usb-host setup perfectly. Every game with cover art. Every game in it’s place. But i cant do wifi from usb-host.   Anyway to get online with usb-host... without having to just load games from within retroarch?

**Comment by KMFDManic** [comment]
@adamcarter1 Not sure if you got my previous messages about successfully getting many DOS-CD games up and running.  Hope all is well!

As far as Wi-Fi, it is all about the right combination of Hakchi2 CE, Wi-Fi Adapter, WPA Supplicant HMOD, and OTG Device.  I still have a working tutorial, which has given me no problems getting things going, at:

https://www.youtube.com/watch?v=i06ZEBysq1Y

The text version of the tutorial is in Xtras/WiFi:

https://hakchi.net/KMFDManic/NESC-SNESC-Modifications/KMFDManic-S-NESC-PSC-Cores_4-29-19/_km_Xtras/WI-FI/_WI-FI_Tutorial.txt

**Comment by adamcarter1** [comment]
Kyland!!! Thats great news

I am still having problems with using the newer versions of hakchi and getting my games to play properly.

Do u have time to teamviewer in or perhaps i can send my classic to you?
