### ISSUE TITLE
Neo Geo Roms don't work

### ISSUE THREAD

**Issue by chris121278** [TeamShinkansen/Hakchi2-CE#109]
Hello,

I flashed my snes classic.
I use Hakchi2 CE in order to install FBA, I put a rom like mslug5.zip, Add neogeo.zip in the same folder and modify bin/fba /.
I use 2 differents neogeo.zip but the problem is the same: when I launch the game, it's written loading, and go back to the main menu of the snes.
I do not find some tutos about it, so I request your help.

Thanks !!

**Comment by ghost** [comment]
the game has to be fit the neogeo.zip and its working for sure if they are compatible. no issue on hackchi . ;)
