### ISSUE TITLE
Confole freezing when doing soft reset

### ISSUE THREAD

**Issue by Rafalas** [TeamShinkansen/Hakchi2-CE#11]
Hi! After installing this version of hakchi, the soft reset on the console (either by the button on the console, or using down+select) freezes completely the console and the only way to get it out of it is unplugging it from the power. When doing it with SNES games, everything works fine, but when doing it with games from other platforms (I've tried NES, Genesis, GBA and TurboGrafx) it freezes.

I've tried using select+start and 'Quit RetroArch' from the menu, but it freezes as well.

Any idea of how I could fix this or why is it happening? Thanks a lot!

**Comment by daPhie79** [comment]
this is a known issue with retro arch 1.6.7 (see faq) update to the latest 1.7.0 version in KMFDManic's core set. and it should work.
