### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Domi78** [TeamShinkansen/Hakchi2-CE#112]
There is only English and France in the language selection of Hakchi CE. I'm missing German. In the ClusterM-version 2.30 there was a german translation.
I wrote this in the discord suggestion channel and viral_dna told me, that French is currently the only option in 'Hakchi2 CE\languages\fr-FR\hakchi.resources.dll'. Also he said, that i can translate it by creating a new issue (which i am doing now).
I took a look at the cote, but it seems that there is no language.xml or something. I found just some .fr-fr.resx files.

**Comment by DanTheMan827** [comment]
Translate this file and upload it, then I'll integrate it
[2018_07_06.xlsx](https://github.com/TeamShinkansen/hakchi2/files/2171435/2018_07_06.xlsx)

**Comment by Domi78** [comment]
Hi Dan,
here is my german translation. It is all done by hand and i used lot of the translation from hakchi 2.30 to get a verry simillar look.
[2018_07_06 de-de.xlsx](https://github.com/TeamShinkansen/hakchi2/files/2190200/2018_07_06.de-de.xlsx)
To test it, i need a compiled version because i don't have Visual Studio on my machine.
