### ISSUE TITLE
Audio channels sometimes reversed after launching game in Canoe

### ISSUE THREAD

**Issue by FreezingAlone** [TeamShinkansen/Hakchi2-CE#113]
Hey everyone, so basically the issue is that sometimes (I'd say about 50% of the time at this point) when I launch a game through Canoe, the stereo audio channels will be reversed so that sounds that should be coming out of the right speaker come out of the left and vice versa. It's very noticeable in games like Mega Man X where attacking enemies on one side of the screen makes the audio come from that side. In this case, I'll be attacking an enemy on the right side of the screen but the "attack" sounds will be coming from my left speaker. Restarting the game usually fixes it, but whether it happens or not seems to be random.

I'm using Hakchi v1.2.5 with default settings other than no folders, no-thumbnail module and no boot screen. All of my games are running on Canoe and this issue occurs on new games as well as the original 21 titles. When I return the system to factory defaults with my original dump the issue seems to go away, and there's a post online from someone who's having the exact same issue (using Hakchi v1.2.5) so I don't think it's my hardware. I think I've covered everything, but if you need more information I'll be happy to help.

**Comment by skogaby** [comment]
This one is likely gonna be tricky to diagnose.

Do you have any Retroarch cores installed? Specifically, do you get "loading" screens when you load games in Canoe, before the game starts?

If you could attach a screenshot showing your installed mods, and maybe a link to that online post you mentioned as well, that'd be a good start.

**Comment by FreezingAlone** [comment]
Thanks for the quick response. I don't have any RetroArch cores installed and no "loading" screens when loading a game. My setup is literally Store Bought SNES Classic > Hakchi2 CE v1.2.5 fresh install > Disable folders, thumbnails and splash screen. Here's the post I was talking about (Sorry about not sharing it initially, not sure what the rules were for that):

https://www.reddit.com/r/miniSNESmods/comments/8vbj85/audio_channels_sometimes_reversed_snes_games/

As for the screenshot, sorry for being a little dumb but are you asking for my installed modules screen?

**Comment by Zaidyer** [comment]
I'm having this problem too, in stock games as well as added games.
Some people blame A/V devices such as stereo receivers and sound bars, so I connected my SNES Classic directly to my television with the included HDMI cable and only used my TV's built-in speakers. Yet even then, this bug still happens under hakchi2 CE 1.2.5 exactly as described. 
Whether it happens at all is entirely random, but it only happens to Canoe and only when Canoe is  loaded, such as starting a game from the main menu, loading a Suspend Point, or using the Rewind feature. Returning to the main menu and doing any of these things, whether to the game I was just playing or another game, re-loads Canoe and thusly re-rolls the dice.
I should note that I also can't make this bug happen while using my original stock kernel with hakchi completely uninstalled. It appears to be a problem with hakchi2 CE specifically.

**Comment by rhester72** [comment]
I believe this is fixed in the latest 3.x release.

**Comment by daPhie79** [comment]
it has indeed been fixed!
