### ISSUE TITLE
(Device taking too long to reboot) in all ways possible

### ISSUE THREAD

**Issue by OfTheZ** [TeamShinkansen/Hakchi2-CE#116]
My sness has current stock load out when i plug to play and can be played.
I am getting the Device is taking too long to reboot error during loading boota 47400000 when:
- I try to install the kernel in the install/repair option
- tryed to unninstall
- factory reset

I am:
- using stock cable
- on Mac platform using virtual box
- I downloaded the expantion and am running usb 2.0
- shutdown the windows security
- I did unnable the usb port in the bios (using the f7 option)

I did in hakchi ce told me to do in the important to know section:
- install the driver manualy has described
- the Zadig port update

I previously done:
- used hakchi3.0 , Was able to load games and play them
- messed up when i wanted to upload a different batch of games and had to unninstall hakchi
- Reinstalled factory kernel and I was able to only play back to stock state
- tryed to add games back to hakchi3.0 however i was unnable to load games from 3.0 due to not reconising the normal mode only after I flashed costum kernel (before flashing costum kernel, My port was detecting the Nintendo Co., Ltd CLV-S-SNSY (0233) but after costum kernel, I could only see the ftl mode).
- I then unninstalled hakchi3.0 on snes and then reset to factory kernel
- Last, I unninstalled 100% 3.0 and started trying CE

I seek help in finding the resolution to this mystery!

**Comment by Brds7t7** [comment]
I had the same issue, SNESC just stalled at reboot command when trying to do anything. 

Try these instructions provided to me by Princess_Daphie on Reddit:

Start with your nes/snes mini powered off - press ctrl-f12 while on the main hakchi2 CE window - go to settings -> developer tools -> force clovershell memboots. 

Then click modules -> install modules -> check Clovershell Daemon -> OK

See if that works.

**Comment by OfTheZ** [comment]
I just had a frend having the same problem than I. Just realised. Everything worked before the windows 10 update and after it did not and same for my friend.

I will try what you said brds7t7 and add my experience. I just have that feeling that the windows update of win 10 has something to do with this since the consol does not reboot half way through flashing the costum kernel

**Comment by Shienarier** [comment]
Based on the information here, I have the exact same problem.

**Comment by Crusher0508** [comment]
I am currently having the same issue and cant seem to find any way around it

**Comment by klydeoscope** [comment]
I'm having literally the exact same problem, made an account just to post about it. Anyone know what to do about it? :(

**Comment by bobthebobish** [comment]
Yep same here.  No rebooting allowed apparently.

**Comment by madmonkey1907** [comment]
chek your firewall settings. and/or disable vpn

**Comment by bobthebobish** [comment]
On top of the reset error I can no longer do anything with the system as far as adding new games, flashing a kernel or adding/removing mods.  Tried firewall settings and hakchi is allowed on all fronts.

**Comment by madmonkey1907** [comment]
reset error?
again, it's likely a network issue
if you're on vbox, you probably didn't pass through 'hakchi classic' device

**Comment by bobthebobish** [comment]
Not sure what's going on.  I've added hakchi ce as an exception to the firewall, there is no VPN and anything I try to do to it now ends in 'device is taking too long to reboot'.  Guess I'll try a different computer entirely?  It was working with hakchi 2.31 but once I tried CE the regular hakchi no longer works either.

**Comment by madmonkey1907** [comment]
switch to fel mode, advanced->boot recovery
does that work?
if it does, follow this https://github.com/TeamShinkansen/hakchi2/issues/94#issuecomment-403522119

**Comment by bobthebobish** [comment]
Thanks for the help!  Didn't work sadly but thanks!  Get the reboot error and the power light stays on even after turning power off lol.

**Comment by bobthebobish** [comment]
Got a new debug when trying to install the driver though:

Win32Exception
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at com.clusterrr.hakchi_gui.WaitingShellForm.buttonDriver_Click(Object sender, EventArgs e)
--- DEBUGLOG.TXT content ---
Base directory: C:\hakchice (portable mode)
Loading configuration
Starting, version: 3.4.1
Loading libretro core info files
Building libretro core cross index
Loading C:\hakchice\data\snescarts.xml
Loading C:\hakchice\data\nescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.23-madmonkey, script v1.0.4-120
.Executing task: MembootTasks.WaitForFelOrMembootableShell
Executing task: <>c__DisplayClass68_0.<TaskIf>b__0
Executing task: MembootTasks.WaitForShellCycle
Tasker completed all tasks, conclusion: Abort
..Executing task: MembootTasks.WaitForFelOrMembootableShell
Executing task: <>c__DisplayClass68_0.<TaskIf>b__0
Executing task: MembootTasks.WaitForShellCycle
Tasker completed all tasks, conclusion: Abort
Saving selected games
Saving configuration
.Executing task: SyncTask.ExportGames
Executing task: SyncTask.ShowExportDialog
Tasker completed all tasks, conclusion: Abort
The system cannot find the file specified   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at com.clusterrr.hakchi_gui.WaitingShellForm.buttonDriver_Click(Object sender, EventArgs e)
--- End of DEBUGLOG.TXT content ---

**Comment by madmonkey1907** [comment]
Didn't work how exactly? What happened? Again, switch to fel mode first, then advanced - > boot recovery. Describe everything that happens. If you get long reboot error, open device manager, expand usb, other, unknown and network devices, post screenshot.

**Comment by bobthebobish** [comment]
Boot recovery gets me the same message as any other action requiring a reset:

![image](https://user-images.githubusercontent.com/42742491/45132178-2b308b80-b14d-11e8-8209-259f2c2b3649.png)

And All of the USB devices on device manager:

![image](https://user-images.githubusercontent.com/42742491/45132357-db05f900-b14d-11e8-82dc-ed3e909e86b7.png)

Hope that helps!

**Comment by bobthebobish** [comment]
Forgot the other/network devices oops!

![image](https://user-images.githubusercontent.com/42742491/45135256-ab5ded80-b15b-11e8-89bc-dd67196e538a.png)

**Comment by madmonkey1907** [comment]
right click on the "remote ndis based internet sharing device" and select update driver. if it works, try again.

**Comment by bobthebobish** [comment]
Didn't work, got the same result.  Windows seems to think that remote NDIS device is a samsung mobile usb remote though which seems odd as I don't even have a samsung phone.

**Comment by playab0yyy** [comment]
I'm having the same problem. Was working fine on the old 2.17 and 2.20 for both, NES and SNES Classics. Now this with CE 3.5.
![capture](https://user-images.githubusercontent.com/44752609/47967800-6b1dcd00-e02f-11e8-9a4b-9daff147a0b2.JPG)

**Comment by playab0yyy** [comment]
I figured out a solution that works for me. I disconnected from the internet! Literally, unplugged my hardwire while doing anything in CE 3.5 pertaining to flashing, the kernal, or synchronizing and everything ran perfectly!

**Comment by KMFDManic** [comment]
@OfTheZ @Brds7t7 @Shienarier @Crusher0508 @klydeoscope Improvements have been made for the next Hakchi release, which should help with the device taking too long.  Generally, when I run into the issue, which is not too often, I unplug power from the back of the system for a few seconds...effectively doing a "router reset" style of scenario.  Then, plug back in, and I have no problems retrying whichever process or step I was "stuck" at.  If any of you still have any problems, feel free to respond!

**Comment by jormc** [comment]
Hi friends,

Same problem for me... I have upgraded from 2.2 to 3.5 too... :-(

**Comment by jormc** [comment]
Hi there, I've seen this tutorial, and it solves the problem for me:

https://www.youtube.com/watch?v=JObjJohstn0

**Comment by TroisPieces** [comment]
> Hi there, I've seen this tutorial, and it solves the problem for me:
> 
> https://www.youtube.com/watch?v=JObjJohstn0

Hi there, do you have any idea of what step of the tutorial solved the problem ? I don't think the issue is specifically covered in the video.

**Comment by Fonsie001** [comment]
So i guess the problem isn't solved yet?
I think its important to mention to only hack the device once. Do not add more games in a later stage, it will either brick the system or it wont allow you to flash the kernel or re-install hakchi anymore.

**Comment by ltupin** [comment]
Im stuck in exactly the same situation. After try on different versions I can say the bundle MAC, VM Win10 on VBOX :

- Hakchi2 all_versions >> **OK**
- Hakchi2-CE 1.0.0 >> **OK**
- Hakchi2-CE 1.2.1  and above versions >> **KO**

Why this issue is closed :-( ?

**Comment by Anthcort4** [comment]
I also am getting the same problem  - My Mini Genesis will not reboot, i only make it to 14% and then it just stops. No fix for this yet? Why is it closed?  I am using a proper USB cable, and even disabled my firewall to try and push this through. nothing, and excpetions in the fire wall settings seem to do nothing.. help! 
![1111](https://user-images.githubusercontent.com/67932146/86664667-eaaa2f00-bfbc-11ea-97ee-3217df6913e8.PNG)

**Comment by biogerm** [comment]
I have to reboot the computer into **Disable Driver Signature Enforcement** mode to make it work. Steps:

**Click Start>Settings>Update&Security>Recovery>Advanced Startup+Reboot Now>TroubleShoot>Advanced Options>Startup Settings>F7 Option to Disable Driver Signature Enforcement**

Also in this mode, I'm unable to connect to the SNES mini via USB2.0 port but only 3.0 port. it might be different on different PCs but definitely try both ports if you are running into trouble.

Also I tried to disable all the Network Adapters but it didn't work. It worked this way two years ago on my other laptop but it doesn't work anymore on the same laptop.

what gives away the final solution is that after Hakchi tried to reboot the console, I can see a **Remote NDIS based Internet Sharing** Device but it's disabled and cannot be enabled. then I googled a bit and found [this question](https://github.com/TeamShinkansen/Hakchi2-CE/issues/162). one answer had described the steps.

**Comment by eastxtwitch** [comment]
I had to disconnect from the internet in order to get it to work.

**Comment by bencsimd** [comment]
Got my NES mini to work finally. I was having the same issue, taking too long on reboot using the Kernel>Install / Repair button.

With the NES unplugged and off:
In hakchi CE v3.8.0 when to Kernel>Reset. Go though process of pressing power in button, hold reset, plug into computer. 
NES actually rebooted for me when it was time to.

Then I added .nes roms and clicked Synchronize in lower right. Worked for me. Good luck.

**Comment by AnCh7** [comment]
Still facing same issue

**Comment by Wowter** [comment]
Same problem here

**Comment by underme123** [comment]
It's unfortunate that the problem still persists for myself and for others. I have been to the subreddit and if the copy/paste list of solutions does not work for you then you get ridiculed and downvoted. I have retired my mini consoles, mediocre while it lasted.

**Comment by impeeza** [comment]
100% of times that problem is a computer/driver/OS related, nor Hakchi; try another computer and the problem will go away. My self sometime had to reinstall all my OS in order to get working.

Be polite and grateful because this is a free project and cost so many effort and dedication.  No body forces you to use.

**Comment by matbess** [comment]
> reset error? again, it's likely a network issue if you're on vbox, you probably didn't pass through 'hakchi classic' device

This was the problem.

Make sure you do the following:

1. On menubar go to "Devices->USB" and select hakchi classic
2. Go back to Machine->Settings->Ports->USB and add another USB device. Now you'll see "hakchi classic" - add it.

<img width="389" alt="Screen Shot 2022-11-07 at 8 55 12 PM" src="https://user-images.githubusercontent.com/1884731/200478497-787f4b3e-7364-4239-b69b-1f8f31be384f.png">
