### ISSUE TITLE
Thumbnail shouldn't stretch UP to 40 x 40

### ISSUE THREAD

**Issue by Mime64** [TeamShinkansen/Hakchi2-CE#12]
All my thumbnails are 32 x 32, which allows you to fit more on the screen, but if importing them into hakchi then it thinks I want them to be 40 x 40. Stretching down makes sense, but if the user is supplying smaller thumbnails then it is probably intentional. I plan to release a huge pack of thumbnail sprites soon and it would be nice if people didn't get 40 x 40 stretched versions of them. :)

![hakchi](https://user-images.githubusercontent.com/20603668/36049766-d1da330c-0ddb-11e8-8e03-988c694f1410.png)

**Comment by daPhie79** [comment]
this is exactly what i've been working on for the last few days, this feature should be included in 1.1 when we release it, among many other improvements! 👍

**Comment by daPhie79** [comment]
should be fixed in current 1.1.0 version!
