### ISSUE TITLE
ROMs with same id gets overwritten even if file size and name differs.

### ISSUE THREAD

**Issue by snigel** [TeamShinkansen/Hakchi2-CE#120]
For example, both "Golf (PC10).nes" and "Golf (GC).nes" uses the same id, but their size and hash differs.
Trying to add both to hakchi2 CE 1.2.5 results in only one rom ending up in the list.

**Comment by rhester72** [comment]
If their size and hash differ, the auto-calculated ID should differ as well, so both will be added with the same name (in two separate entries).

**Comment by DanTheMan827** [comment]
It could be possible that the two have a CRC32 hash collision, this would mean that they would both get the same game code

Could you please check both of those rom files with this tool to see if they give the same CRC32?

https://emn178.github.io/online-tools/crc32_checksum.html

**Comment by DanTheMan827** [comment]
I was able to re-create the issue, it appears that it may be getting the checksum from the header instead of hashing the entire file.

I'll have to investigate further

**Comment by DanTheMan827** [comment]
Is there any difference between the two roms or is it possible that the only difference is the header and padding?

Hakchi2 CE only hashes the actual game data, it doesn't include any of the data that wouldn't be written to the rom chips on the original cartridge

**Comment by bslenul** [comment]
![image](https://user-images.githubusercontent.com/33353403/53966160-e339f380-40f2-11e9-8f36-f0f1ecd228ac.png)

Only difference is in the header, if CE ignores the header that would explain it :D

**Comment by DanTheMan827** [comment]
The file size is different as well, but I would guess that it's padding from using a slightly larger rom chip

I'm going to close this issue then

**Comment by bslenul** [comment]
The "(PC10)" rom is actually trimmed down from 32 to 24KB once you add it to hakchi CE. My guess is that hakchi CE reads infos from the header and knows what kind of rom it is and remove the unnecessary data.

That unnecessary data being hints for the PlayChoice-10 arcade cabinet apparently:
`the PlayChoice used special expansion cards containing (usually unmodified) NES games along with an extra 8KB ROM to display hints`
