### ISSUE TITLE
Hakchi doesn't seem to run on my computer

### ISSUE THREAD

**Issue by Dominator593** [TeamShinkansen/Hakchi2-CE#121]
Whenever I try running Hakchi on my computer, It simply won't run. I've extracted all of the files (Which the only thing it does it duplicate Hakchi), but it seems to say 51% next to the 3,732 KB. What is wrong?

**Comment by ghost** [comment]
you should use the binary files instead of the source code dude ;)

**Comment by Dominator593** [comment]
Thank you, AntiFly. Unfortuanatly, I am not a computer expert. Im not at that age yet.
