### ISSUE TITLE
[Feature request] Auto-compression exclusion list.

### ISSUE THREAD

**Issue by bslenul** [TeamShinkansen/Hakchi2-CE#124]
Hello!

When adding .cue to hakchi2 sometimes I forget to uncheck "Compress" and my game is not starting because of it (same with .exe for DOSBox games, etc.). I know this is not CE fault obviously but I was wondering if it would be possible to have some sort of "exclusion" list for auto-compression?

Something like this for example:
![image](https://user-images.githubusercontent.com/33353403/43394704-ec04304c-93fb-11e8-9691-2f6b70943af3.png)

Or directly a .txt file to edit to not clutter the CE interface maybe?

Anyway it's just an idea, really low low low priority (I know you guys must have way more important stuff to add/fix), just thought it could be a useful feature :D

**Comment by KMFDManic** [comment]
@bslenul We discussed this, previously.  This is still an excellent idea that we should try to incorporate either via Whitelist or Blacklist.  Generally, CD Based Games will not run compressed/Cartridge Based ones, will.  I task this project to you and myself, as we have the best general idea of what works and what doesn't.  So, if still interested, let me know.  But, I will have this on the To Do list!
