### ISSUE TITLE
Installed modules doesn't has checked mark if installed

### ISSUE THREAD

**Issue by ZeroSuf3r** [TeamShinkansen/Hakchi2-CE#125]
After latest update it seems that my installed modules doesn't have "check mark", only greyed box.
Windows version: 1803 (17134.165)
![list](https://user-images.githubusercontent.com/584896/43452343-e274c306-94bf-11e8-93d5-a04f131c2425.png)

**Comment by ghost** [comment]
yep ... I would think that's because of the new feature of re-installing an HMOD.
So you can select it for re-installation "again". greyed out is the indicator for already installed as you mentioned above.

**Comment by ZeroSuf3r** [comment]
It would be more informational if installed modules in "Install external modules" would be without check box and only clickable those which are didn't installed. Same goes for "Uninstall extra modules" section. It's kind of feature/suggestion.

**Comment by bslenul** [comment]
This is perfect like this IMO, you know which ones are installed (greyed out) and you can re-install them without having to uninstall first!

**Comment by DanTheMan827** [comment]
Yes, this was changed to allow re-installing modules while still being able to see which ones are installed.

This isn't a bug, it's _actually_ a feature.
