### ISSUE TITLE
SD Mode uboot flash error in 3.3.0 coming from working SD mode on 1.2.5

### ISSUE THREAD

**Issue by esmith13** [TeamShinkansen/Hakchi2-CE#126]
hakchi can't see the SD card internal to my snes mini so in 1.2.5 I used to "export" to the SD in a usb flash reader and then insert card in the mini. That worked fine.

Now with 3.3.0 I was prompted to upgrade the kernel and after doing so I only saw the stock 30 games so I decided to do Kernel -> flash uboot -> SD Mode and I get this error:

.......Executing task: <>c__DisplayClass24_0.<FlashUboot>b__0
cat > /uboot.bin # exit code 0
truncate -s 640K /uboot.bin # exit code 0
flash md5 mismatch! 87ea696f08975fe68e3b4746e238135b(/uboot.bin) != 328c541aeddcc9aefce242a9c3eb2d17(flash+8)
hakchi flashBoot2 /uboot.bin 8 5 # exit code 1
--- End of DEBUGLOG.TXT content ---

Help!

**Comment by daPhie79** [comment]
the md5 fail on uboot flash is a known issue, we're working on it.

as for your games... did you upgrade from 1.2.5 to 3.3.0, or did you started fresh anew? make sure separate games storage and always copy original games are properly set for your files configuration. those are new options and have an effect on which games you see available in your list.

**Comment by esmith13** [comment]
I created a new directory for 3.3.0 and moved over my art, dump, games, games_snes folders as well as migrated my added user_mods and folder images. I see all of my games in hakchi fine. when I hook my SNES mini up to the TV I only see the 30 built-in games, not my custom setup on SD. Basically it no longer reads the SD card. 

Thanks for the info on the md5 fail.

**Comment by BananaRama203** [comment]
OK I worked it out.

```
Connected!
Executing task: ShellTasks.ShowSplashScreen
uistop # exit code 0
gunzip -c - > /dev/fb0 # exit code 0
Executing task: <>c__DisplayClass24_0.<FlashUboot>b__0
cat > /uboot.bin # exit code 0
truncate -s 640K /uboot.bin # exit code 0
nand sectors written: 6
flash md5 mismatch! 87ea696f08975fe68e3b4746e238135b(/uboot.bin) != 328c541aeddcc9aefce242a9c3eb2d17(flash+8)
hakchi flashBoot2 /uboot.bin 8 5 # exit code 1
--- End of DEBUGLOG.TXT content ---
```

I get this error and the screen locks up and you need to hard reset however the uboot is flashed.

You can test by telneting to console after and running commands:

`lsblk` to see if mmcblk0 exists and you can do `dmesg` to check for any mmc errors.

This seems to be more a GUI issue however I will do some more testing on this and let you guys know.

**Comment by ghost** [comment]
just for the record! I upgraded from 1.2.5 and did a reset before. it worked very well.

**Comment by daPhie79** [comment]
the md5 failure on uboot flashing  *should* be fixed in next release. (3.4.0rc1 has that fix)
