### ISSUE TITLE
hakchi2 CE v3.4.0rc1 | device does not come in online mode

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#127]
after upgrading the files from 3.3.0 to 3.4.0rc1 the device is not shown online.

edit:
after resetting the device with reset method and reflash, the system comes online again correctly.
the flashing itself worked without errors.

leave this as hint, close it if you read.

**Comment by daPhie79** [comment]
thanks! i did write a notice in the message of the day 👍 major change in the way hakchi2 detects the mini, because of major change on the mini!
