### ISSUE TITLE
Issue with SD card with many games

### ISSUE THREAD

**Issue by v1das** [TeamShinkansen/Hakchi2-CE#128]
I have modified my SNES mini adding micro SD card and everything seemed working perfectly until I have put a lot of games to SD (currently about 2300).
Now, when I connect SNES Mini to PC via USB and launch Hakchi CE (does not matter if it is 1.2.5, 3.3.0 or 3.4.0 RC1), it starts loading games, goes slowly until around 40% and then jumps to 100%, but shows space available on SNES Mini as "??? MB" and games gannot be synchronized, it throws error about "0 MB of writable memory" - see screenshot attached.

If I delete the games on SD and then reconnect SNES Mini, everything works just fine, it shows full capacity of SD card and game CAN be synchronized (all of those 2300) - but only one time. After synchronization, Hakchi starts showing available space again as "??? MB". Despite of this, if I connect SNES mini to TV I can play all the games synced to SD, also I can access the content of SD with all games via FTP and telnet, so SD is not corrupted, I have even tried with 3 different SD cards. 
Seems to me like Hakch issue - maybe there is a timeout for reading of SD content and when there are many games it expires and shows capacity as "??? MB" 

![capture1](https://user-images.githubusercontent.com/7092146/43639980-bd7ead6e-9726-11e8-9a51-4c359e44b6ae.JPG)

**Comment by daPhie79** [comment]
tell us if it still does it in 3.4

**Comment by v1das** [comment]
It works like a charm now in 3.4.1 ;)

Thanks for your effort to make Hakchi 2 CE great again! 😄

**Comment by daPhie79** [comment]
good to know. if i remember correctly, it was a bug with parsing the device memory information!
