### ISSUE TITLE
GMOs issues on SD

### ISSUE THREAD

**Issue by DecanFrost** [TeamShinkansen/Hakchi2-CE#133]
GMOs it should say HMODs

So I have done a few SD mods now but today I did one with Hakci 2 CE v3.4.1 . None of the games added work   i get loading screen and then back to game menu.

I have installed and uninstalled all HMODs over and over.  It seems like they are not transferring to the SD anymore and yes I am using the external retroarch hmod

**Comment by DNA64** [comment]
Odd, I was under the impression after installing the SD mod that any other files installed would be to the SD rather then the NAND, but it appears as you say, they do not. I don't use the "external_retroarch.hmod". 

I suspect this could be an issue with some mods that aren't configured to write to "/media/", but I'm not sure about the external_retroarch.hmod, or why you'd be having issues. I will have to look at the code.

**Comment by DecanFrost** [comment]
When I install the hmods like normal they all sit on the internal nand.  I check the sd card and no libretro folder is there. If I install the external hmod then it says transfering and then when I check the ad card it makes the folder and transfers the items now. After lots of tweaking around.  However there still seems to hmods sitting in the internal band still taking up space


________________________________

**Comment by DNA64** [comment]
Yes, you're correct. I just checked my own install and they do reside on the NAND. It's possible some of the hmods aren't configured to use SD. Personally, I think if someone is using an SD Mod, everything should install to it, and not the NAND. The problem is the way we have things setup right now we can't really control or enforce this. I'm hoping down the line we will have a better system for installing .hmods

**Comment by KMFDManic** [comment]
@DecanFrost External RetroArch is meant more or less for testing purposes.  With the current addition of Compression Support for the Cores, the best course of action is to stick to NAND installations.  Some HMODs will be tweaked to be smaller sizes in future Releases.  For now, I have added Install Sizes to nearly all Cores/HMODs in the Xtreme Core Set Release.  You can install up to 75 percent smaller than when you initially made your post.  If you have any other questions, let me know.  But, definitely stick to NAND for Core/HMOD installation, with a few variances, depending on what exactly you are hoping or attempting to install.
