### ISSUE TITLE
wrong labeled CORE

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#134]
Version 3.4.1
Under sorting through cores the core for FBA2016 is not listed correctly
should be - FBA2016 -  currently is -/bin/fba2016

second.. the N64 cores are listed together under GlupeN64
this should be seperated (for my understanding)
/bin/mupen64plus
/bin/parallel 
... ends up under GlupeN64. 

should be ---- Mupen64 --- and --- Parallelei ---
cheers

used hmods KMFDManic-NESC-SNESC-Cores.8-11-18

**Comment by BananaRama203** [comment]
@AntiFly They are not officially fully supported within CE UI in that sense because they are using custom prefixes and do not use the standard libretro file naming conventions or info files.

If you want to use the KM cores you can use the command line which was the original way of doing it.

You can read up on it here: https://old.reddit.com/r/miniSNESmods/comments/9674wq/housekeeping/

**Comment by ghost** [comment]
@swingflip 
hey thanks for reply. yes i know of using it, just thought about to get that sorted and shown correctly.
if iam think about that further would be cool to add these prefixes in some way to make it sorted correctly ;)
if it not worth to update / impelement just close ticket.

**Comment by madmonkey1907** [comment]
They are supported, and this is a simple oversight. Don't listen to flip, he just tries to push his inferior builds as always.

**Comment by BananaRama203** [comment]
No version is inferior just madmonkey being a salty dickhead as always

**Comment by BananaRama203** [comment]
Lol but all seriousness. Just read that Reddit post

**Comment by ghost** [comment]
@swingflip 
nope i just dont care about anything else than hackchi2 ce and kmfd mods. if kyland doesn´t add it its not from importance to me ;)

**Comment by daPhie79** [comment]
with most recent release, you can add custom .info files in /info directory, to add more cores supported. i suggest you try this, it might make it easier :) also, if you don't plan on using standard libretro cores naming (which happens with kmfd's pack), you can remove the offending info files from /data/libretro_cores.7z and you have to delete /config/cores*.json to see the changes immediately. then start h2ce again, you should see the new cores in the core selector. this is a veru new feature though, so i can't tell exactly everything that might happen, but i've added it to allow working with kmfd's pack!

**Comment by KMFDManic** [comment]
@AntiFly As always, thanks for the pointing out and support of the Xtreme Core Set:)  Some of the special Command Lines will be added to Emulation Core Selections, as well as a few other things, taken into account.  Thanks again!  Keep in touch, via Email!  I know you've been pretty busy!
