### ISSUE TITLE
File error. Code=553 ('Error') 

### ISSUE THREAD

**Issue by pmiller8** [TeamShinkansen/Hakchi2-CE#137]
I added an SD card (soldered in) and the space is recognized just fine.   Now when I try to sync games, im getting a 553 error.  The dump doesnt seem to be too specific.  Anyone experiencing this?

**Comment by daPhie79** [comment]
it usually has to do with either file system corruption or a file system format that the mini doesn't like too much and causes issues with ftp upload. sorry i can't be more specific.

**Comment by KMFDManic** [comment]
@pmiller8 Try with the newer SD Prep Mod, if you still currently have issues.  

https://github.com/DanTheMan827-Hakchi/sdprep.hmod/releases

If you still have problems, be sure to reply and let us know.

**Comment by pmiller8** [comment]
im pretty sure its the sd card i used.  i tried another one just like
it and had the same intermitten boot issues.
