### ISSUE TITLE
Web Installer and Source Code contains Win32/Fuery.B!cl

### ISSUE THREAD

**Issue by bluegekkon** [TeamShinkansen/Hakchi2-CE#138]
Windows Defender and Protect System integrated in my browser checked source code package and some files in the web installer as infected by Win32/Fuery.B!cl

**Comment by DanTheMan827** [comment]
Which files?

**Comment by bluegekkon** [comment]
Nintendo_Classic_USB_Driver.exe
![image 22](https://user-images.githubusercontent.com/1947374/44620998-32cb7700-a8a7-11e8-830b-d26d848ccaf9.png)
![image 21](https://user-images.githubusercontent.com/1947374/44620999-32cb7700-a8a7-11e8-8a5e-2e2db6fc9b97.png)

**Comment by daPhie79** [comment]
this file is the driver installed for FEL communication with the nes/snes mini, which does use a workaround to allow automatic installing, which might sound suspicious to antivirus software.

**Comment by bluegekkon** [comment]
Can I download somewhere an archive with an application that does not contain this driver?

**Comment by DNA64** [comment]
You could, but how do you plan on using this on your system without the proper drivers?

**Comment by daPhie79** [comment]
the new driver should work  better with win7 and win10 now.
