### ISSUE TITLE
SD mod not mount

### ISSUE THREAD

**Issue by jetbalanced** [TeamShinkansen/Hakchi2-CE#139]
After update sd mod do not working. Any card, any file system. Are you testing your soft?

**Comment by DNA64** [comment]
There is nothing wrong Hakchi or it's ability to detect and utilize an internal SD Mod. I suggest you test all your solder points with a multi-meter. I also suggest installing the [sdprep.hmod](https://github.com/DanTheMan827-Hakchi/sdprep.hmod/releases/) file and make sure you've flashed uboot to SD mode (Kernel > Flash uboot > SD mode) after confirming the memory size change in H2CE.

**Comment by madmonkey1907** [comment]
нехер стоковое ядро шить патамушта. теперь снова flash uboot->sd

**Comment by jetbalanced** [comment]
ORLY? А то я не знал...
Поставился, от "сохранить настройки" вылетает, во время игр вылетает, на ровном, цуко, месте (поиграл, выключил, через час опять включил) вылетает. Ставишь повторно (я приставку и не закручиваю уже, ибо задолбался флешку туда-сюда дёргать) - когда восстановится, когда плюнет, и ни в какую.
Стабильность во все поля!!!

**Comment by madmonkey1907** [comment]
Fat32?

**Comment by jetbalanced** [comment]
не, ntfs. ставил ntfs-3g - та же хрень. самое обидное, что слетает совершенно рандомно от любого (я серьёзно: АБСОЛЮТНО ЛЮБОГО) действия. или ошибка может выскочить при добавлении игры, что, в свою очередь, опять приводит к необходимости установки мода по-новой.
а ещё она разучилась нормально играть в игры СНЕС через ретроарх. работает только через Snes9x (но там глючит звук), на остальных модулях тупо не заводится.

**Comment by KMFDManic** [comment]
@jetbalanced There is a newer SD Prep Modification, which might help you, if you still have issues.  It is at:

https://github.com/DanTheMan827-Hakchi/sdprep.hmod/releases

WIP Support is also being implemented directly into Hakchi.  Hope this helps!
