### ISSUE TITLE
USB/pendrive not recognized on boot, slow device?

### ISSUE THREAD

**Issue by nuvalo** [TeamShinkansen/Hakchi2-CE#14]
Hi, i´m not sure if this is an incompatibility with the usb-host driver or just a problem with a slow pendrive. I have three pendrives formatted as NTFS attached through an OTG+power adapter to the snes mini usb. I installed hakchi2 1.0.1 kernel and exported some games to the pendrive. Two of the pendrives are ignored on boot, the third pendrive (a samsung 32gb usb3.0) seems to work ok and is recogniced on boot.  One of the ignored pendrives has an activity led, it seems that it takes too much time to be recogniced, it starts blinking after some time after booting. The other does not have any led, so i´m not sure what is going on.

I had a similar problem some time a go, trying to boot a filesystem from a usb. It took some time to be recogniced by the kernel (some seconds), so maybe it is just that some pendrives needs some more time to be initialized. Just wondering if it is possible to add a small delay to the custom kernel before deciding that there is no usb attached.

**Comment by daPhie79** [comment]
i know from reading a lot on forums that usb drive support is hit and miss, and it's kinda normal since the whole thing wasn't exactly the designed use of the mini :) some people have some OTG adapter that works, while others don't. same thing with usb drive 👎

**Comment by daPhie79** [comment]
go on the snes mini reddit thread you might have more help on troubleshooting! thanks for trying out CE!
