### ISSUE TITLE
Add option to hide unused games collections

### ISSUE THREAD

**Issue by ShaunDreclin** [TeamShinkansen/Hakchi2-CE#141]
I would like to only see the `NES (USA/Europe)` and `Super NES (USA)` games collections, since I'll never use the other ones.

**Comment by daPhie79** [comment]
i'll leave this as a feature request, but it's not priority. you can just ignore the games collections you don't want.

**Comment by ShaunDreclin** [comment]
Haha yeah it's not a big deal, would just be nice if somebody feels like doing it

**Comment by KMFDManic** [comment]
We will accept pull requests on this, as long as there are no conflicts.  But, this is very low priority, for the time being.
