### ISSUE TITLE
[BUG] Reinstalling HMOD didn´t work properly

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#143]
Hi there ;-)

Version: hakchi2_CE_3.4.1_Release
HMODs: KMFDManic-NESC-SNESC-Cores.9-3-18

ive tested to re-install the "km_master_bios_module_9_3_18.hmod" (HMOD) from KMFD because i forgot a file once in a subfolder "dc".
the file does not appear in the storage even after uninstalling hmod. so i guess there is something wrong with the existance check here...

ive loaded the core where the file was missing and it told me "not present".
after reset snes mini and reinstall everything, file is present!

you may could have a look into this, cause re-installing hmod will save many time (other wise , reset and reinstall everything)

cheers

**Comment by KMFDManic** [comment]
Hey @AntiFly :)  Did you try creating hakchi/transfer and letting it install that way?  If you run into a problem where files do not override, sometimes the disk may need checked.  I generally do hakchi/transfer, and copy the HMOD I want to Update to, and it overwrites.  If you use Hakchi on PC, it will deem it already installed, and need uninstalled, then reinstalled.  But, if using my Core Set, you should have no problems simply using transfer folder to Update the files, provided they are from same set.  Hope that helps!  There are other ways to do it, as well.  But, hope this solves the issue.

**Comment by ghost** [comment]
hi @KMFDManic i didn´t tried that transfer method. 
but ive tried to uninstall the hmod, unfortunally that didn´t worked either.... (even a reset didn´t worked) in that particula situation only a complete reflash of my device worked later on.

**Comment by KMFDManic** [comment]
@AntiFly As I know you should no longer be having this issue, I am closing it:)  Hope all is well, otherwise!  Feel free to email me if you need any Updates.
