### ISSUE TITLE
SMW Hacks With SA-1 Patched

### ISSUE THREAD

**Issue by Mogu94** [TeamShinkansen/Hakchi2-CE#145]
There seems to be something up with playing Super Mario World hacks on my SNES Classic that has the [SA-1 patch](https://www.smwcentral.net/?p=section&a=details&id=15116) installed into the hack. I keep getting a C7 error and booted back to the main menu. The hacks in question work 100% in the BSNES / Higan emulator though. Also tried using Retroarch on my SNES Classic for these roms, same deal.

**Comment by daPhie79** [comment]
can't really help out on game specific questions, sorry. try hitting the /r/miniSNESmods/ subreddit!
