### ISSUE TITLE
User configurable tools menu

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#15]
It would be great if we could configure hakchi2 to run external tools with the selected rom (uncompressing it if required)

For example if I want to:
- remove the header of a SNES game (using Tush)
- correct the checksum of a SNES game (using WindHex)
- change the format of a disk image for PX68K (using VFIC)
- hex edit file (using WinHex)
- crop box art (using Paint)
etc

**Comment by gingerbeardman** [comment]
Testing @gingerbeardman

**Comment by KMFDManic** [comment]
This is an excellent idea.  But, the path Hakchi2 CE is currently taking is to try to best avoid implementation of external tools.  You are probably already aware of me adding tools to Xtras/Tools to account for many of these.  Don't completely rule external tools out as an option, though!  I will get some of these together, as they are great recommendations.  If you have any others, definitely let me know.  I will put them into Xtras Folder for people to utilize in the meantime!  Hope all is well, by the way!  Be sure to stop in and chat in Discord when you get a moment away from reality:)
