### ISSUE TITLE
I can´t mod anymore my SNES mini

### ISSUE THREAD

**Issue by SpeedwagonIsHusbando** [TeamShinkansen/Hakchi2-CE#150]
I was trying to upgrade my SNES mini from the hakchi cluster 2.31 edition to the ce 3.4.1. I uninstalled hakchi from the SNES and flashed the original kernel. Then I attempted to flash the custom kernel in the CE version, but it didn't work. I tried to turn the SNES mini off, but it didn't until I unplugged it. I connected it to my tv but the screen was dark, and the led was flashing. So, I uninstalled hakchi from the CE version and it didn't work, i tried doing it from the 2.31 version and it went back to normal, but then I tried to flash the custom kernel again, and it still didn't work. I tried from my NES mini and i didn't have any problems. Has someone had this problem?
Sorry for bad English

**Comment by SpeedwagonIsHusbando** [comment]
I tried to flash the custom kernel on the 2.31 version of hakchi, and it worked! However, I would still like to know if I can change to the CE version.

**Comment by DanTheMan827** [comment]
from a completely stock state, download a fresh copy of ce and select kernel > install, turn on the system while holding reset, and it should install

If you get a message saying it's taking too long to reboot, try disabling your firewall, if that fails, check device manager for any devices with an exclamation point

**Comment by KMFDManic** [comment]
If you still have any trouble getting onto CE, let me know.  I have helped many migrate over from 2.30.  But, the steps DanTheMan827 outlined, should help you along.  Just make sure you confirm firewall permission when prompted to do so by Hakchi2 CE, upon first opening it.
