### ISSUE TITLE
Cores do not work

### ISSUE THREAD

**Issue by Dominator593** [TeamShinkansen/Hakchi2-CE#152]
On Hakchi2 CE 1.2.5, I download the cores for each appropriate ROM to be able to run. I download and install the cores. But when I tried running Super Mario 64 on my SNES Classic, I always just get booted back to the menu. What am I doing wrong?

**Comment by DanTheMan827** [comment]
Please verify that this issue still occurs with the latest version of hakchi2 ce (3.4.1 as of this comment)

Also, please ensure that you have retroarch installed as well as the cores and that the command line is correct for the core you want to use.
