### ISSUE TITLE
Controller "not configured"

### ISSUE THREAD

**Issue by Dominator593** [TeamShinkansen/Hakchi2-CE#153]
So, before, when I used my Wii Classic Controller Pro, the games worked absolutely fine. Now, the controller is "not configured". What does this mean and how do I "configure" my controller?

**Comment by Dominator593** [comment]
I'd also like to point out that none of my controllers work on any of my ROMs besides SNES.

**Comment by KMFDManic** [comment]
@Dominator593 You still having any controller issues?  You might want to try RetroArch 1.7.5 Xtreme, which should recognize and auto configure it, just fine.

**Comment by Dominator593** [comment]
I am no longer having control issues. I was told to uninstall and reinstall retroarch.

**Comment by KMFDManic** [comment]
Awesome! Exactly as I would have recommended.  I edited your email out of your response:) Have a great day.
