### ISSUE TITLE
Moving Rom with Save Data

### ISSUE THREAD

**Issue by belskis68** [TeamShinkansen/Hakchi2-CE#155]
This may be a stupid question but how do I move a copy of a ROM (the original Zelda) without losing progress? I was playing it on Openemu on my MAC and then got an nes mini.  I have successfully put nes, snes and MAME games on it using Hakchi but when I copied that ROM none of the save data transfered with it. 

Is there a way to properly do that? Would love to continue my progress on the mini. Thanks!﻿

**Comment by DamianS-eng** [comment]
On other emulators like FCEUX, save data is handled in a different file, format .sav. Check your Mac for a file like that, could be sitting next to the ROMs or in a dedicated save folder, then simply move it to the NES mini.
