### ISSUE TITLE
3.5.0 ext hd how to

### ISSUE THREAD

**Issue by dpickl01** [TeamShinkansen/Hakchi2-CE#156]
can some one point me to a video on how to load and make work the ext hd for snes on the 3.5.0 

i have loaded roms to the 3.5.0 and clicked export to ext hd, but when i load the mini up it dont show them ?

**Comment by ghost** [comment]
you may have a look into the vids from this guy ;)
https://www.youtube.com/channel/UCoRrbw6gyi4KRPGUNnVVjMQ

**Comment by KMFDManic** [comment]
@dpickl01 This is entirely about having the appropriate hardware.  I would recommend an Inateck OTG device, which is the standard for most of us on USB-HOST, and at a minimum, a 32 GB Sandisk Flash Drive, formatted to Fat32/NTFS/Ext4.  Once these are accounted for, a simple install/repair of the kernel on hakchi2 CE current version, then export, will do the trick.  If still stuck, let us know!
