### ISSUE TITLE
Separate nes usa and nes europe

### ISSUE THREAD

**Issue by SamYStudiO** [TeamShinkansen/Hakchi2-CE#158]
Is there any way to separate usa and eur region from nes mini?
I want to have dual boot, one with usa games and another one with french games for children. So far multi boot works great with differents region/platform firmwares but in my case both usa and eur use same firmaware so when i switch fimware my games are shared on both firmware since they're on the same/var/lib/hakchi/games/nes-usa fodler.
Any suggestion appreciated!
Thx

**Comment by YaSoC** [comment]
hey there.
got the similar problem today and solved it like opening Hakchi CE, then going to Pull-Down menu:
Tools -> Separate games for multiboot,.


However at first it will still be the same.
You will have to delete your games from "library" of Hakchi2 CE and re-add them and then re-upload.

Tricky thing, but works.

**Comment by DanTheMan827** [comment]
This isn't possible because the EUR and USA software is the same
