### ISSUE TITLE
Modded SNESC freezes TV contols

### ISSUE THREAD

**Issue by 12seth12** [TeamShinkansen/Hakchi2-CE#159]
This only started happening since the CE version of Hakchi a few months back. When i turn on my SNESC after it's been modded, I can't change the volume, change the channel or even turn it off. Even if i turn off my SNES, it'll be frozen until i turn off my computer (I have to go to the back of my TV and unplug it). This issue doesn't happen when i remove Hakchi from my SNESC (restore to factory settings). I have a Magnavox TV. Can you help me?

**Comment by 12seth12** [comment]
I'm using the latest Hakchi CE 3.5.0 and i just noticed that this only occurs when i power my SNESC from a USB slot in my TV. If i plug it in an power socket, the TV doesn't freeze

**Comment by nl255** [comment]
Most likely it is because with the Hakchi kernel the s/nesc spoofs itself as "Samsung Electronics Co., Ltd GT-I9500 [Galaxy S4] / GT-I9250 [Galaxy Nexus] (network tethering)" which causes many Linux systems to try to load the rndis_host driver.

**Comment by DanTheMan827** [comment]
This is a problem with the TV software itself trying to make sense of a network device being attached to it
