### ISSUE TITLE
probleme net frame 3.5.1

### ISSUE THREAD

**Issue by islandmen** [TeamShinkansen/Hakchi2-CE#16]
hello, I have a problem this hakchi, puts me an error message about the netframe 3.5.1, I followed the steps to fix the problem but impossible to install the 3.5.1 that it is with updat win or other solution find on the net, help me please

**Comment by islandmen** [comment]
I have the net frame 3.5 and 4.6 under win10
I have the net frame 3.5 and 4.6 under win10
I already downloaded the 3.5.1 win6.1-KB2836943-v2x64 but could not install

**Comment by daPhie79** [comment]
![image](https://user-images.githubusercontent.com/33412188/36346401-f6c0bb60-140b-11e8-8387-e37ae7811373.png)
do you have this enabled?
do you have all your windows updates done?

the file you've downloaded is for windows 7 i think based on the win6.1 version in file.

**Comment by islandmen** [comment]
Bonjour j'ai bien activé les net framework 3.5 et 4.6

 mais je ne pas encore le 4.7 , ça serait le 4.7 qu'il faut que j'installe
? Pour que ça fonctionne ?

Je ne suis pas à jour de Windows 10 je ne peux pas , la dernière fois que
j'ai fait toutes les maj win10 je n'avais plus de son et ma carte mère qui
peut mettre 3 écran ne marchait plus que deux écrans depuis ce coup là mon
j'ai dû réinstaller complètement mon PC et je fais des maj manuel ..

Si vous savez exactement ce qu'il faut comme maj win10 pour faire
fonctionner le hakchi CE , ça m'arrangerait, merci d'avance.


Hello I have enabled the net framework 3.5 and 4.6

but I do not yet 4.7, that would be the 4.7 that I need to install? For it
to work?

I am not up to date with Windows 10 I can not, the last time I did all the
maj win10 I did not have any sound and my motherboard that can put 3 screen
only worked two screens since that I had to completely reinstall my PC and
I'm doing manual maj ..

If you know exactly what it takes like maj win10 to make the CE hakchi
work, it will suit me, thank you in advance.

Le 18 févr. 2018 02:58, "princess_daphie" <notifications@github.com> a
écrit :

**Comment by daPhie79** [comment]
https://support.microsoft.com/en-us/help/3154518/support-for-tls-system-default-versions-included-in-the-net-framework

maybe this could help you out?

**Comment by islandmen** [comment]
hello thank you for the suggestion, I will try to remove my version 3.5 net frame to see if my pc wants to install the 3.5.1 instead

**Comment by islandmen** [comment]
ce hakchi ce runs under net frame v2 ...;

mscorlib.resources
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll

et le 3.5 do not contain the net frame 2.0 juste v3.0 and v3.5

----------here is all the error message that gives me the window----------

Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.NotSupportedException: Le protocole de sécurité demandé n'est pas pris en charge.
   à System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   à com.clusterrr.hakchi_gui.MainForm.MainForm_Shown(Object sender, EventArgs e) dans H:\hakchi2\MainForm.cs:ligne 1766
   à System.Windows.Forms.Form.OnShown(EventArgs e)
   à System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   à System.Threading.ExecutionContext.runTryCode(Object userData)
   à System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   à System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
hakchi
    Version de l'assembly : 3.0.1.0
    Version Win32 : 3.0.1.0
    CodeBase : file:///C:/Users/Moi/Desktop/hakchi%20ce/hakchi2_CE_1.0.1/hakchi.exe
----------------------------------------
System
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Version de l'assembly : 3.5.0.0
    Version Win32 : 3.5.30729.8763 built by: WinRel
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
hakchi.resources
    Version de l'assembly : 3.0.1.0
    Version Win32 : 3.0.1.0
    CodeBase : file:///C:/Users/Moi/Desktop/hakchi%20ce/hakchi2_CE_1.0.1/languages/fr-FR/hakchi.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
AutoUpdater.NET
    Version de l'assembly : 1.4.6.0
    Version Win32 : 3.0.1.0
    CodeBase : file:///C:/Users/Moi/Desktop/hakchi%20ce/hakchi2_CE_1.0.1/hakchi.exe
----------------------------------------
System.resources
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase : file:///C:/Windows/assembly/GAC_MSIL/System.resources/2.0.0.0_fr_b77a5c561934e089/System.resources.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

**Comment by islandmen** [comment]
![20180219_200854](https://user-images.githubusercontent.com/36570709/36389832-0c33f782-15ba-11e8-9595-941ed2878d11.jpg)
voici une jpeg de mon 3.5 fram net

**Comment by islandmen** [comment]
![20180219_200854](https://user-images.githubusercontent.com/36570709/36390080-1f6a127c-15bb-11e8-8c9b-1e1784e26ecb.jpg)
![20180219_212147](https://user-images.githubusercontent.com/36570709/36390082-1fbba736-15bb-11e8-9c4e-a76dc2afde19.jpg)
