### ISSUE TITLE
Lag in games

### ISSUE THREAD

**Issue by Dominator593** [TeamShinkansen/Hakchi2-CE#161]
In the games I've tried in order to test them, I discovered some lag. The 3 games I tried for lag were The Firemen for SNES, Doom for SNES, and Home Alone 2 for the Sega Genesis. The Firemen's lag was not all that serious, but it does run slightly slower than normal, and the core I used for both SNES games was the Snes9x RetroArch core. For the Genesis game, I used the Genesis Plus GX core. For Home Alone 2, I have the exact same problem with The Firemen. But when it comes to Doom, not only was the game tremendously slower than normal, but the audio was corrupted. I need a fix for this, please.

**Comment by DanTheMan827** [comment]
This isn't an issue with hakchi, this is a problem with the emulator or just plain and simple, a performance limitation of the hardware.

I would suggest trying out the different SNES9x versions, the older versions actually run some games better than the newest version

I also personally use KMFDManic's core set, you might have better luck with that if you aren't already using it, that can be found in the mod hub (not mod store)
