### ISSUE TITLE
Load .bin for .cue automatically from same folder (PSX)

### ISSUE THREAD

**Issue by bbsan2k** [TeamShinkansen/Hakchi2-CE#163]
Hi everybody,

Would it be possible to add loading image files for PSX like this:

if fileextension == '.cue':
  read cue file line by line to get .bin file names
  for bin_file in cue sheet:
   if bin_file in cue_folder
     copy bin_file to dest_dir
fi

Essentially it would make adding all multi-track disc games a lot easier, as copying of respective bin files would not be necessary.

Tell me - what do you think?

Also I think that I may be able to implement it myself, unfortunately I don't use VisualStudio, so I would not be able to compile.
Could you point me to the unit where the actual copying is invoked?

Thanks!

**Comment by DanTheMan827** [comment]
This will be included in the next Hakchi2 CE release
