### ISSUE TITLE
Can't use the retroarch cheat HMOD files

### ISSUE THREAD

**Issue by Zarkas2000** [TeamShinkansen/Hakchi2-CE#166]
Hi
I just installed hakchi2 CE 3.5.0 on my mini SNES. I also installed Retroarch for specific games.

I'm trying to load the Retroarch cheat files and Hakchi2 dosen't see them.
I put the files in the user_mods directory.
When i click on Install extra modules, the cheat HMOD files are not there but i can see other HMOD files.

The files are from github : 
https://github.com/stayupthetree/Retroarch-Cheats-for-NESC/releases

I am completly stumped, can anyone help ?

**Comment by Zarkas2000** [comment]
I just upgraded to 3.5.1 and it solved the issue for now
I will test the codes tonight

**Comment by KMFDManic** [comment]
@Zarkas2000 I have updated Cheats to be more optimal for use on the Mini.  You can grab them from my Release, as well as KMFD Mod Hub on current Hakchi2 CE.  If you have any other issues, be sure to let me know!

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases
