### ISSUE TITLE
Transferring games from cluster's hakchi2.

### ISSUE THREAD

**Issue by MisereMortem** [TeamShinkansen/Hakchi2-CE#167]
Hello. I tried to use the method described on the net, so I copied my "games_snes" folder to hakchi2 CE folder, but nothing happened. I can't see my old list of games. Only my custom folders are transferring when I use the "synchronize" button, but they're empty. And the games are inside the "games_snes" folder, I checked that.

**Comment by leolapi4** [comment]
Hello!
I think it should be a feature request to import games from Hakchi2 by Cluster. Yes, it is silly to make an application fork without the backward compatibility support.
As far as I can see the game meta-data is particullary contained in **_game-code_\\_game-code_.desktop** file in the games folders which are different in Hakchi2 (**games_snes**) and Hakchi2 CE (**games**). Next difference is H2CE rename the original files while H2 keep the filename unchanged (nevertheless H2CE store original filename in **metadata.json** file in the **_game-code_** subfolder). The path to the games save data and the path to the box art are also different between H2 and H2CE, but it is also convertable from one to another. **[X-CLOVER Game]** section of **_game-code_.desktop** file can be entirely migrated as is. The same is true for box art files which are **_game-code_.png** and **_game-code_\_small.png** for both H2 and H2CE.
It is good idea to create a small migration tool to support H2CE development and then request the developer to merge it with his project.
Thank you!

**Comment by sneslover** [comment]
Sry, i cant help with this problem, but i just wanted to say that i would love something like an migration tool/function to get my stuff from hackchi2 to hackchi 2 CE!

**Comment by DanTheMan827** [comment]
move the games_snes folder to the games folder in ce

if you use both folders, copy them into the games folder of ce
