### ISSUE TITLE
"Group games w/ no box art" option includes stock games if using their stock artwork

### ISSUE THREAD

**Issue by chocoboyeepdong** [TeamShinkansen/Hakchi2-CE#169]
![image](https://user-images.githubusercontent.com/32485188/48866408-5a43ba00-ed98-11e8-9532-635609205a42.png)

I would imagine the purpose of a "group without box art" option would be so you can easily go through and change the artwork, right?

It's made completely useless if it always includes the original games unless you manually assign new artwork to them.

While of course there are workarounds for this, such as taking the time to manually add the stock artwork as "custom artwork", the user should hella never be expected to do that.

**Comment by KMFDManic** [comment]
@chocoboyeepdong Thanks for the excellent feedback and suggestion.  This is fixed for the next Hakchi2 CE Release:)
