### ISSUE TITLE
hakchiCE NES mini black screen when loading added games.

### ISSUE THREAD

**Issue by Syntaxhead** [TeamShinkansen/Hakchi2-CE#172]
I am using the latest version of hakchiCE on the NES mini. When I try to load the the added games, I get the a black screen for about 2 seconds then back to the games menu. I am able to run the stock games. I have tried adding one game only and I still get the black screen. I have uninstalled/reinstalled hakchi to no avail. I am only adding NES games. Anyone else running into this issue?

**Comment by KMFDManic** [comment]
@Syntaxhead Are you still having any issues related to NES Classic?  Let me know, if so.

**Comment by KMFDManic** [comment]
@Syntaxhead If you use current RetroArch 1.7.5 Xtreme, and have no other RetroArch or NES Cores installed, you can manually amend first part of command line to be...

/bin/fceumm

/bin/nestopia

/bin/quicknes

You can, additionally, use latest Hakchi2 CE, and right click and select emulation Cores!
