### ISSUE TITLE
NES MINI STAY IN RECOVERY MODE...CANT UPLOAD NEW GAMES

### ISSUE THREAD

**Issue by MODJO6** [TeamShinkansen/Hakchi2-CE#173]
HI !....My NES MINI STAY IN RECOVERY MODE...CANT UPLOAD NEW GAMES
I try to reboot with  hakchi 3.5.2 REBOOT BuTTON ...but it didnt works!

[debuglog1.txt](https://github.com/TeamShinkansen/hakchi2/files/2646840/debuglog1.txt)

**Comment by david4444** [comment]
please help him and me, happens to me too. i managed to do it once, but not anymore.

**Comment by MODJO6** [comment]
USE VERSION 2.31 AND RETURN THEM AS FACTORY .... LOAD THE "CORES" YOU NEED AND LAST THE GAMES ...
