### ISSUE TITLE
hackchi2 CE 3.5.2 ISSUE

### ISSUE THREAD

**Issue by ShengJieYang** [TeamShinkansen/Hakchi2-CE#175]
I can't upload my games and display this message
"your device is taking too long times to reboot"
I already tried any functions when this issue,but no working
I already download games to my jump mini famicom,but it,s not display at my hackchi2 list
please help me

![default](https://user-images.githubusercontent.com/34790692/50035501-5c1e3780-003d-11e9-9cc7-0380d1055cb0.png)

**Comment by csthielen** [comment]
I have this exact problem, ShengJieYang! 

Can someone please assist us with this? It might be worth mentioning that, unlike ShengJieYang above, I am using VirtualBox VM to run Hakchi2 CE on my Mac.

**Comment by ShengJieYang** [comment]
Hi
Thanks your support,I already solved this problem

csthielen <notifications@github.com>於 2018年12月16日 週日，上午6:19寫道：

**Comment by csthielen** [comment]
Oh did you? How did you solve it? I still haven’t.

**Comment by ShengJieYang** [comment]
Change others usb holes or setting usb connect

csthielen <notifications@github.com>於 2018年12月16日 週日，上午10:26寫道：

**Comment by edrozenberg** [comment]
In my case, for the Kernel Install/Repair step, I had to use the Debug version of the Hakchi application. For some reason, the regular/installed Hakchi version did not work as far as having the console USB drivers recognize the console properly.

After the kernel installation, for later game update tasks I could use the regular (non-debug) Hakchi app.

**Comment by DanTheMan827** [comment]
Taking too long to reboot is usually caused by the windows firewall blocking communication between the system and hakchi2 ce

It could also be a driver issue, there are two drivers used in various stages, the fel mode driver and then a rndis network adapter driver, the latter is used for most communication with the system

If you open up network connections, do you see any additional network adapters listed?

can you ping `169.254.13.37` when that message pops up?

**Comment by KMFDManic** [comment]
One thing to note is, if on virtual machine, you will need to install drivers while powered on, as well as in FEL mode.  Then, install/repair kernel, should allow both sets of drivers to function with Hakchi.  

As far as long time to reboot, it can definitely be related to firewall/virus protection, as well as being stuck in recovery mode.  Unplugging the power cord from the back of the system, waiting a few seconds, plugging back in...then, repeat any given process, such as Modules, Synch, Export, usually does the trick.

If any of you need anything else, be sure to let us know:)
