### ISSUE TITLE
Downloading Retroarch cores not working

### ISSUE THREAD

**Issue by ElChapo1109** [TeamShinkansen/Hakchi2-CE#176]
From the mod store trying to download retroarch cores it starts downloading it but then the whole app just crashes.And it doesnt show up in modules when I reopen it again.

**Comment by DanTheMan827** [comment]
Does this still occur for you? I just tried downloading a core and it worked fine for me.

**Comment by KMFDManic** [comment]
@ElChapo1109 Mod Store is now added as its own Repo, and no longer part of Hakchi2 CE.  Support for that will be at the following link.  If you need any additional help, feel free to ask!

https://www.reddit.com/r/miniSNESmods/comments/bejo1s/new_repository_mod_store_for_hakchi_2_ce_353/
