### ISSUE TITLE
Can't make directory in /media - read-only FS

### ISSUE THREAD

**Issue by YaSoC** [TeamShinkansen/Hakchi2-CE#177]
I just got my wi-fi configured. And could easily connect to my SNES Calssic Mini by telnet.
However when i tried to mkdir at /media (my USB flashdrive) - i fail.
The mkdir reverts: 

**mkdir: can't create directory 'yas': Read-only file system
**

Most probably, i just miss something.

**Comment by bslenul** [comment]
If you're not using any USB drive, then yeah the `/media` folder on NAND is read-only.
If you're using a USB drive you can force it to be mounted with RW permission by creating a "saves" folder in `usb:\hakchi`.

**Comment by YaSoC** [comment]
thank you very much, it worked.

**Comment by KMFDManic** [comment]
@YaSoC Glad the issue was fixed to your satisfaction:)  Personal thanks to bslenul for the help!
