### ISSUE TITLE
[REQUEST] Add download and use complete NES box-art covers/thumbnails image collections/packs from a list of known sites 

### ISSUE THREAD

**Issue by Hedda** [TeamShinkansen/Hakchi2-CE#178]
I know that hakchi CE has an automated image grabber for Google but please consider adding a new 'easy-to-use' feature that automatically downloads complete sets/packs of NES Box Art Cover/Thumbnail image collections to then match and utilize once cached on your hard drive. Maybe use a known collection sites list with examples such as Libretro and/or EmuMovies which have complete front cover collections with all in 'OK' quality that already have almost all cropped images to the same aspect-ratio in similar sizes.

http://thumbnailpacks.libretro.com/

https://emumovies.com

Now those collections might not be the best collection of packs for all regions and languages, as most EmuMovies collections mostley only contain USA boxart collections in English, but you get the idea. This is just a suggestion and using the collection on those specific sites and collections/packs are just examples.

Alternatively you could do what the RetroArch/Libretro project done and create your own collection to distribute, maybe start by forking libretro-thumbnails from the libretro project on GitHub to use a base for a front box artwork collection, however, it is not complete for Europe, US and Japan, and I noticed that their images are not all of the same aspect-ratio:

https://github.com/libretro/libretro-thumbnails

https://github.com/libretro/libretro-thumbnails/tree/master/Nintendo%20-%20Nintendo%20Entertainment%20System/Named_Boxarts

Perhaps also team/partner with the EmuMovies.com community to get approval to share their members high-quality artwork collections of box cover images.

https://emumovies.com/files/file/34-nintendo-nes-2d-boxes-pack/

https://emumovies.com/files/category/1354-artwork/

Regardless, I personally I think that it most important that all cover images for a platform have been cropped to the same aspect ratio, even if they are all not of the same quality.

**Comment by KMFDManic** [comment]
This is a very sensitive area.  I have personally communicated with the individuals who have worked on several packs, and incorporated them into my Releases, Mega NZ wise.  If there are any you'd like to see added, feel free to ping me!  But, you can follow the Mega NZ Link on my Release Page, and go to Game Art!  

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases
