### ISSUE TITLE
implementation of sfromtool: different file sizes after applying patch

### ISSUE THREAD

**Issue by Bekker84** [TeamShinkansen/Hakchi2-CE#18]
Hi 

Hakchi 2 CE 1.1.0 running from USB_HOST (H:)
As an example I used rom Street Fighter Alpha 2 (U) [!].smc In settings I enabled apply sfromtool and I enable apply patch when available. Then i downloaded sfromtool and placed contents of zip in sfrom_tool-folder. I donwloaded the Street Fighter Alpha 2 | E-NTSC | SDA / PCM patches and placed in sfrom_tool/patches folder. I add Street Fighter Alpha 2 (U) [!].smc and gives me a Street_Fighter_Alpha_2_U_.sfrom uncompressed of +- 4,0 MB. Game not working.
When i manually apply the patches with SFROM_Tool_v1.1.0.4 i get a sfrom file of 8MB and the game is working just fine.

**Comment by daPhie79** [comment]
looking into it!

**Comment by daPhie79** [comment]
![sans-titre-1](https://user-images.githubusercontent.com/33412188/36348059-853483ac-1436-11e8-8edf-25f23f1a5cbb.jpg)

it works fine for me. don't know what to say. i initially thought the code was internally chopping the additional bits, but it seems to work fine.

**Comment by Bekker84** [comment]
I got the transfer part working now, and i get the same filesize as you get 10,5MB sfrom uncompressed. I didn't do anything different then yesterday (i even closed hakchi 2 to make sure settings saved). When i manually create rom with sfromtool and the patches i get a sfrom of 8,7 MB uncompressed. Both games working now.
![fromtool](https://user-images.githubusercontent.com/36577705/36350605-9447b9b2-149b-11e8-8636-02dfbfed999b.png)

**Comment by Bekker84** [comment]
I did some more testing with this and it gave me the same issue with rom Ultimate Mortal Kombat 3 (U). No patches are applied. After adding it through hakchi i get different sfrom. I also get a different game ID When i ad through hakchi i get game ID CLV-U-OGBJF. This game ID is the same one created by hakchi 2.21f. 
When manually convert with sfromtool i get game ID  CLV-U-MEEWM.
Both roms work and savestates from my old hakchi2 are working on both roms.
The rom through sfromtool manually has the information about Publisher and Release Date removed. Can that be the difference? 
![sfromtool2](https://user-images.githubusercontent.com/36577705/36351996-f5a32140-14b1-11e8-8746-d02a3c3572fb.png)

**Comment by Bekker84** [comment]
Solved

**Comment by daPhie79** [comment]
thank you!
