### ISSUE TITLE
Problem with Retroarch detecting Zero Delay USB encoder

### ISSUE THREAD

**Issue by RealAhab** [TeamShinkansen/Hakchi2-CE#181]
I am wondering if anyone has gotten a custom arcade stick with the Zero Delay usb encoder to work with Retroarch on the SNES mini. My Snes mini is running latest version of Retroach and is recognising all sorts of devices including HORI fightpads, PS3 controllers with the default udev driver but this custom arcade stick is not showing. The Zero Delay is supposed to work with the Raspberry Pi Retropie which I assume is fairly similar to the SNES mini Retroarch (correct me if im wrong). The arcade stick works fine in Windows where it is a generic USB gamepad.

BTW I have tried changing the driver from udev to linux and hdi but nothing works.

The item is listed on Amazon as: Reyann Zero Delay Arcade USB Encoder Pc to Joystick for Mame Jamma & Other Pc Fighting Games

**Comment by DanTheMan827** [comment]
If you have Wi-Fi on your classic, could you please connect to it over telnet and run the command `lsusb` with the encoder connected?

**Comment by RealAhab** [comment]
Hi DanTheMan827 unfortunately I don't have a wifi adapter on my SNES classic mini.  Is there any other way I can help with diagnosing this issue?

**Comment by KMFDManic** [comment]
@RealAhab Unfortunately, not all controllers will work, right outside of the box.  I add config files for many, and several have been accounted for.  Are you using RetroArch Xtreme, by chance?  I would suggest uninstalling any current RetroArch, installing RetroArch Xtreme, and checking to see if the controller works.  If it does not, it simply is not supported.  BUT, it would have a better shot at working on the PS Classic, if you happen to have one.

**Comment by KMFDManic** [comment]
@RealAhab If you want to continue running a few perimeter tests, feel free to respond.
