### ISSUE TITLE
hakchi2 CE stuck on boot

### ISSUE THREAD

**Issue by lapara809** [TeamShinkansen/Hakchi2-CE#182]
i am havinf an issue try so many version and the same after install custom kernal my syytem reboot and gets stuck on the hakchi green logo boot screen the only what i get it to boot is with everything back to stock no hack or with anyversion of hakchi2 but i want to use hakchi ce becuse more options and easyer please i tryed all tutorial but nothing work am stucking only modding my snes with the regualar hakchi2

**Comment by scarbo86** [comment]
i also have a similar problem. i can install the custom firmware without any problem and then check my snes mini, it works fine. after that when i try to sync some games it completes but stuck at hakchi knock knock screen. what am i doing wrong?

**Comment by DanTheMan827** [comment]
The general answer for problems like this is to download the newest version of hakchi2 ce, uninstall, re-install, and see if the problem still occurs.

When dealing with old versions, there can sometimes be incompatible mods that cause the boot process to fail which would give you that hakchi screen that doesn't go away

**Comment by KMFDManic** [comment]
@lapara809 @scarbo86 From a fresh install of Hakchi2 CE, current version, ensure that you click ok to confirm firewall permission.  Use an appropriate, preferably default micro USB cable that comes with the system, and do install/repair kernel.  Holding down power+reset on the system simultaneously should have the status bar moving, if there are no false positives relating to firewall/virus protection.  If either of you still need assistance, be sure to let me know!
