### ISSUE TITLE
Games Erased from Hakchi

### ISSUE THREAD

**Issue by ProfHeadwreck** [TeamShinkansen/Hakchi2-CE#183]
I was trying to add a game to my NES Classic and I got an error message stating that it was being denied. When I tried to delete the game, it deleted all of them and now when I open up hakchi, it show the upload games screen, then flashes to the game denied screen I had earlier. when I click ok, none of the games show up in my list. Please help!

**Comment by ProfHeadwreck** [comment]
Update. Apparently the issue resolved itself. Not sure what exactly happened, but all my games have shown back up on my games list. Of anyone could please explain how this happened I would greatly appreciate it.

**Comment by buzzcloudau** [comment]
I had a similar problem. Adding new games it said I needed to flash it first (it had already been done) when I told it to flash it went through the process in a couple of seconds. After restarting most games and all folders were gone. I thought it had restored back to original games only, but it seemed to be random games that remained. (Possibly just one of the subfolders worth)

Re-syncing restored all the games.
