### ISSUE TITLE
[feature request] rewind function on shoulder (L, R) buttons for SNES Mini

### ISSUE THREAD

**Issue by pikachurus** [TeamShinkansen/Hakchi2-CE#184]
in Steam's "The Disney afternoon collection" (https://store.steampowered.com/app/525040/The_Disney_Afternoon_Collection/) was very comfortable with that controller function.

is it possible make something like that in Hakchi2 CE?

**Comment by DanTheMan827** [comment]
This would conflict with games that actually use the L and R buttons

that and the way Canoe (the stock emulator) works, it needs to close and re-open in rewind mode.
