### ISSUE TITLE
GPL compliance

### ISSUE THREAD

**Issue by sapperlott** [TeamShinkansen/Hakchi2-CE#185]
Just a friendly reminder to keep you out of trouble in the future - it's nice that you make the sources to the hakchi GUI and FelLib available through your GitHub repos but you also ship binary blobs of components licensed under the GPL. To be in compliance with the terms of the GPL, you are required to make the sources of these components available along with all the configuration files, Makefiles, etc. necessary to re-build the exact binary blobs your releases (each of them) contain.

From a cursory glance I've identified these (there might be others):
U-Boot in data/fes1.bin, data/uboot.bin and data/ubootSD.bin (all embedded into hakchi.exe)
The Linux kernel in hakchi-v1.0.4-123.hmod/boot/boot.img (shipped in basemods.tar)

The best way to go about it would probably be to create separate GitHub repositories for those as well and tag those accordingly so it's clear what went into which hackchi2 CE release.

**Comment by madmonkey1907** [comment]
Do you need sources, or are you some sort of gpl compliance officer? Sources are in fact available on github, though maybe there are no links for them in this repo. Anyway, if you do need sources, it's much friendlier to just ask, instead of invoking gpl right off the bat.

**Comment by sapperlott** [comment]
Hi there. As I already wrote - this is just meant as a friendly hint. I have no intention to hit you over the head with the big ol' GPL bat (though others might - therefore the heads up). I chose the way of opening a GitHub issue to have this discussion in public in case other people are looking for the sources as well so everything is in one place to minimize duplicate effort (i.e. everyone interested in the sources going ahead messaging individual developers).

Also, if there is an established process, it's more transparent than individuals having to keep track of which version of the sources went into which binary in an individual release (it's easy to lose track).

So again - I'm interested in the sources because I want to tinker with this stuff myself and I'm sorry if this issue ruffled some feathers. Didn't intend to boss anyone around.

**Comment by madmonkey1907** [comment]
Alright. Uboot is here https://github.com/madmonkey1907/hakchi/tree/master/r16-uboot you only need dram values from there, as nand stuff is no longer in use. Sd stuff was done by @x0rloser I should have the patch somewhere, but can't find it right now. Kernel is here https://github.com/madmonkey1907/sun-nontendocm-kernel it's a bit outdated, but iirc there were only bugfixes, if you need it I can send you whole tar and maybe you can create pull request from there. There is more gpl stuff that is used, but it's used as-is and you can download sources for those from their respective repos.

**Comment by sapperlott** [comment]
Thanks! If you find x0rloser's SD U-Boot stuff as well as the latest kernel tarball, I'd be interested. Also, if you happen to have any documentation on your build environment, that would be greatly appreciated as well.

Am I right to assume that the kernel just uses sun_nontendocm_defconfig without additional changes?

**Comment by KMFDManic** [comment]
@sapperlott Closing the issue, as madmonkey has given you the information you needed.  If you have any additional questions, feel free to respond:)
