### ISSUE TITLE
Recovery State Issue

### ISSUE THREAD

**Issue by skirlez** [TeamShinkansen/Hakchi2-CE#186]
Hey all, I've been experiencing some issues with the latest release.
So, I've finally got my NES classic, ready to hack it. I did everything, and put on new games.
But lately i found out that i had a spelling error at one of the games i added, so i tried to fix that,
and pressed the sync button. said yes to the if i installed the custom kernel, booted the NES mini up, but i got this error:Your NES/SNES Mini is currently is recovery state, cannot proceed.
And this error shows up everytime i try to synchronize my games!
So i exited it by pressing Tools>Reboot>No (What the error tells you to do) But when i try to sync again, it keeps showing up. I've tried changing usb cables with the one that came with the system, I've tried using USB 2.0 Instead of 3.0, I Tried using a different computer, I Tried removing games, all of it didn't work. even with some time searching about the problem, i couldn't found a solution that works.
I've also tried to factory reset my NES Classic but that (And some more options) give me this error:
Session operation has timed out.
So i would really appreciate if someone tells me how to fix this.
Thanks!

**Comment by darkhippieness8up** [comment]
same here practically. wtf mates? lol  some b.s.

**Comment by skirlez** [comment]
Woops, found a fix! If you end up here by google, try the following:
Dump your original kernel with Hakchi2 CE.
Download the Portable Hakchi2 (Not CE)
In the Portable's files, Create a folder called "dump"
Put your original kernel image in there.
Uninstall The Custom Kernel (Hakchi2 NOT CE)
Get back to CE, And try to sync your games.
