### ISSUE TITLE
Softbrick, NES Classic Kernal Missing

### ISSUE THREAD

**Issue by captainjs1089** [TeamShinkansen/Hakchi2-CE#187]
So I'm attempting to restore my NES classic to factory settings and get rid of Hakchi all together. I'm facing the unfortunate scenario where my NESC kernal is missing. Im wondering if anyone can send me a link or tell me how to find it? Please let me know if you know something.

**Comment by DanTheMan827** [comment]
Best I can do is give you a list of filenames and their respective MD5 hashes

https://wiki.hakchi.net/Boot_Image
