### ISSUE TITLE
Accidentally re-added games. lost box art and possibly saves?

### ISSUE THREAD

**Issue by masterronjon** [TeamShinkansen/Hakchi2-CE#188]
I accidentally re-added all my snes games. Looks like they overwrote the originals in the hakchi menu as now there is no box art for them. Can I undo this? I haven't synchronized with my snes mini since I made this mistake. Is there a way to get my hakchi menu back to exactly what I have on my snes right now?

Thanks.

**Comment by DanTheMan827** [comment]
if you delete all the games in the games and games_snes folder in the hakchi2 ce data path, you can download all of the games from the system over FTP.

You'll find them in `/var/lib/hakchi/games`, you'll need to copy the CLV folders inside there to the games folder on your computer that CE uses, after that, quit and re-open CE and the games should populate.

The folder structure may be lost, but the games and saves will be file

You can also copy all the saves from `/var/lib/clover/profiles/0/` if you're concerned

**Comment by KMFDManic** [comment]
@masterronjon This is definitely not a fun thing to accidentally do.  Are you set on what you needed done?

**Comment by KMFDManic** [comment]
@masterronjon If this is still an issue, feel free to respond.  But, depending on whether you synched internally or exported externally, it wouldn't be overly difficult to restore the art.  But, readding it, is also not incredibly time consuming or hard.  I have several preset Artwork Packs, if you need anything related to 20+ systems, from Arcade to Consoles!
