### ISSUE TITLE
Add Option to move games_snes/games_nes...

### ISSUE THREAD

**Issue by bbsan2k** [TeamShinkansen/Hakchi2-CE#19]
Hi everybody,

I have a feature request:
As I use hakchi in a tiny Windows 10 VM that I created only for that purpose, I don't want to keep everything I want to sync within this VM.
Therefore I would suggest adding some kind of config option in order to move the "games_snes/games_nes" folders etc to another location that might not be inside the hakchi directory.
Might this make sense overall?

**Comment by daPhie79** [comment]
yes. it's a nice idea, noted!

**Comment by KMFDManic** [comment]
@bbsan2k You can easily copy and transfer the data files, or even the entire Hakchi directory and all its concurrent folders to a flash drive or external hard drive, for use when you need them again.  Using Linked Sync Option, you could essentially keep Hakchi on your flash drive and run it from there, with a Linked Export motif.  If you still need any help, be sure to let me know:)
