### ISSUE TITLE
Unable to Install/Repair Kernel due to error

### ISSUE THREAD

**Issue by Bullitt75** [TeamShinkansen/Hakchi2-CE#191]
While trying to flash custom kernel for my SNES mini when I get to the step of pressing the reset button then power button an error pops up stating "Can't open device".

Any advise on troubleshooting this issue?  Or how to verify if the SNES mini is connected to the PC?

**Comment by MiguelAraCo** [comment]
I'm having the same issue

**Comment by Bullitt75** [comment]
Just wanted to provide an update to my situation for the benefit of others that may have the same or similar problem.

I discovered that the SNES mini I purchased is a very convincing knock-off/fake.  And that some knock-offs/fakes are not able to be entered into FEL mode.  Hence the error message I was receiving when trying to mod the SNES mini.

I was able to find a good YouTube video on how to determine if your SNES mini is fake or authentic.  Hope this information helps others.

https://www.youtube.com/watch?v=cLazmI3Zj6A
