### ISSUE TITLE
Add more games gives ''A generic error occured in GDI+''

### ISSUE THREAD

**Issue by alptolga** [TeamShinkansen/Hakchi2-CE#192]
Hi,
 When I try to add games with hakchi ce v3.5.2 I get ''A generic error occured in GDI+''
This is the whole report of the problem.

ExternalException
A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.ProcessImage(Image inImage, String outPath, Int32 targetWidth, Int32 targetHeight, Boolean expandHeight, Boolean upscale, Boolean quantize)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.SetImage(Image img, Boolean EightBitCompression)
   at com.clusterrr.hakchi_gui.NesApplication.Import(String inputFileName, String originalFileName, Byte[] rawRomData, Boolean asIs)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.AddGames(Tasker tasker, Object syncObject)
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\PC\Documents\hakchi2-ce-3.5.2-release (portable mode)
Starting, version: 3.5.2
Loading libretro core info files
Building libretro core cross index
Loading C:\Users\PC\Documents\hakchi2-ce-3.5.2-release\data\nescarts.xml
Loading C:\Users\PC\Documents\hakchi2-ce-3.5.2-release\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] Checking for upgrade actions. Last run version: 0.0.0.0, current version: 3.5.2.0
[Upgrade] Running upgrade action 0.0.0.0 -> 3.0.0.0
..Executing task: GameTask.SyncOriginalGames
Loading original games data
Resetting game "????????? ????".
Resetting game "?????????II ???7?".
Resetting game "??????? ????".
Resetting game "???????3 ???".
Resetting game "???????Z ??!????".
Resetting game "????? ??????????".
Resetting game "????? ?????????".
Resetting game "??????".
Resetting game "??????II ??????????".
Resetting game "????3 ????? ????".
Resetting game "????? ????".
Resetting game "????? ???? ???".
Resetting game "???? ????????".
Resetting game "?!!?? ?????".
Resetting game "???????????? FANTASTIC WORLD!!".
Resetting game "?????BLUES".
Resetting game "????????".
Resetting game "??????".
Resetting game "???".
Resetting game "????".
Resetting game "????????????".
Resetting game "????????????3".
Resetting game "???????USA".
Resetting game "???????".
Resetting game "????????".
Resetting game "??????????".
Resetting game "??????".
Resetting game "?????? ??????".
Resetting game "?????".
Resetting game "????????".
Resetting game "??????".
Resetting game "????????".
Resetting game "????????".
Resetting game "???????".
Resetting game "?????r2 Dr.??????".
Resetting game "???r".
Resetting game "???????????rIII".
Resetting game "?????".
Resetting game "????".
Resetting game "????????".
Resetting game "??????".
Resetting game "???????".
Resetting game "??·??·????".
Resetting game "?????".
Resetting game "??????".
Resetting game "???????".
Resetting game "???????? The Revenge".
Resetting game "??????????".
Resetting game "??????????? ????????".
Resetting game "????????".
Resetting game "Super Mario Bros.".
Resetting game "Super Mario Bros. 3".
Resetting game "Super Mario Bros. 2".
Resetting game "Donkey Kong".
Resetting game "Donkey Kong Jr.".
Resetting game "Excitebike".
Resetting game "The Legend of Zelda".
Resetting game "Kirby's Adventure".
Resetting game "Metroid".
Resetting game "Balloon Fight".
Resetting game "Zelda II - The Adventure of Link".
Resetting game "Punch-Out!! Featuring Mr. Dream".
Resetting game "Ice Climber".
Resetting game "Kid Icarus".
Resetting game "Mario Bros.".
Resetting game "Dr. MARIO".
Resetting game "StarTropics".
Resetting game "MEGA MANT 2".
Resetting game "GHOSTS'N GOBLINST".
Resetting game "FINAL FANTASYr".
Resetting game "BUBBLE BOBBLE".
Resetting game "PAC-MAN".
Resetting game "Galaga".
Resetting game "Castlevania".
Resetting game "GRADIUS".
Resetting game "Super C".
Resetting game "Castlevania II Simon's Quest".
Resetting game "NINJA GAIDEN".
Resetting game "TECMO BOWL".
Resetting game "DOUBLE DRAGON II: The Revenge".
Resetting game "Super Mario World".
Resetting game "F-ZERO".
Resetting game "The Legend of Zelda: A Link to the Past".
Resetting game "Super Mario Kart".
Resetting game "Super Metroid".
Resetting game "EarthBound".
Resetting game "Kirby's Dream Course".
Resetting game "Donkey Kong Country".
Resetting game "Kirby Super Star".
Resetting game "Super Punch-Out!!".
Resetting game "Mega Man X".
Resetting game "Super Ghouls'n Ghosts".
Resetting game "Street Fighter II Turbo: Hyper Fighting".
Resetting game "Super Mario RPG: Legend of the Seven Stars".
Resetting game "Secret of Mana".
Resetting game "Final Fantasy III".
Resetting game "Super Castlevania IV".
Resetting game "CONTRA III THE ALIEN WARS".
Resetting game "Star Fox".
Resetting game "Yoshi's Island".
Resetting game "Star Fox 2".
Resetting game "???????????".
Resetting game "F-ZERO".
Resetting game "?????? ??????????".
Resetting game "??????????".
Resetting game "?????????? ????".
Resetting game "?????????".
Resetting game "???????????".
Resetting game "?????? ?????????".
Resetting game "??????????????? ? ???????????".
Resetting game "?????X".
Resetting game "????".
Resetting game "???????RPG".
Resetting game "????2".
Resetting game "???????????VI".
Resetting game "????????".
Resetting game "???????? ???????".
Resetting game "????????????????".
Resetting game "????????".
Resetting game "??????? ?????????".
Resetting game "????????2".
Resetting game "??????".
Resetting game "Super Mario World".
Resetting game "F-ZERO".
Resetting game "The Legend of Zelda: A Link to the Past".
Resetting game "Super Mario Kart".
Resetting game "Super Metroid".
Resetting game "EarthBound".
Resetting game "Kirby's Dream Course".
Resetting game "Donkey Kong Country".
Resetting game "Kirby Super Star".
Resetting game "Super Punch-Out!!".
Resetting game "Mega Man X".
Resetting game "Super Ghouls'n Ghosts".
Resetting game "Street Fighter II Turbo: Hyper Fighting".
Resetting game "Super Mario RPG: Legend of the Seven Stars".
Resetting game "Secret of Mana".
Resetting game "Final Fantasy III".
Resetting game "Super Castlevania IV".
Resetting game "CONTRA III THE ALIEN WARS".
Resetting game "Star Fox".
Resetting game "Yoshi's Island".
Resetting game "Star Fox 2".
Tasker completed all tasks, conclusion: Success
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
[Upgrade] Running upgrade action 3.0.0.0 -> 3.1.0.5
[Upgrade] Running upgrade action 3.1.0.5 -> 3.2.2.0
[Upgrade] Running upgrade action 3.2.2.0 -> 3.3.0.0
[Upgrade] All actions executed successfully
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-123
Downloading motd file, URL: https://teamshinkansen.github.io/motd.md
Service added:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 87200048 9d877787 6c118000, type=snes, region=eur
Motd timestamp: 2018-11-17T16:49:00.0000000-05:00
Attempting to connect to 169.254.13.37...
SSH shell connected
IP Address: 169.254.13.37
Encryption: aes256-ctr
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code 2
hakchi hwid # exit code 0
Detected device unique ID: 0461872a872000489d8777876c118000
[ -f /var/version ] && echo "yes" # exit code 0
source /var/version && echo "$bootVersion $kernelVersion $hakchiVersion" # exit code 0
Detected versions: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-123
hakchi eval 'echo "$sftype-$sfregion"' # exit code 0
hakchi currentFirmware # exit code 0
hakchi findGameSyncStorage # exit code 0
hakchi get gamepath # exit code 0
hakchi get rootfs # exit code 0
hakchi get squashfs # exit code 0
Reading p0000_config file
cat /etc/preinit.d/p0000_config # exit code 0
df "$(hakchi findGameSyncStorage)" | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code 0
mount | grep /var/lib/clover/profiles # exit code 1
du -s "$(readlink /var/saves)" | awk '{ print $1 }' # exit code 0
du -d 1 "/var/lib/hakchi/games" | head -n -1 | awk '{ print $2 " | " $1 }' # exit code 0
Storage size: 290,6MB, used: 27,0MB, free: 248,6MB
    Used by all games: 0,0MB
    Used by non multi-boot games: 0,0MB
    Used by current games collection: 0,0MB
    Used by save-states: 0,1MB
    Used by other files (mods, configs, etc.): 26,9MB
    Reserved memory: 30,0MB
    Available for games: 218,6MB
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
.Executing task: GameCacheTask.UpdateLocal
hakchi eval 'echo "$squashfs$gamepath"' # exit code 0
[ -d "/var/squashfs/usr/share/games" ] && echo YES || echo NO # exit code 0
ls "/var/squashfs/usr/share/games" -p -1 | grep '/' # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAAE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAABE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAEE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAFE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAHE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAJE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAKE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAALE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAQE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SAAXE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SABCE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SABDE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SABHE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SABQE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SABRE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SABTE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SACBE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SACCE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SADGE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SADJE && tar -c * # exit code 0
cd /var/squashfs/usr/share/games/CLV-P-SADKE && tar -c * # exit code 0
Tasker completed all tasks, conclusion: Success
Done refreshing local original games cache.
Success!
.Executing task: AddGamesTask.AddGames
Saving application "CLV-Z-COFYR" as CLV-Z-COFYR
Saving application "ffightu" as CLV-Z-COFYR
ffightu.zip: A generic error occurred in GDI+.   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.ProcessImage(Image inImage, String outPath, Int32 targetWidth, Int32 targetHeight, Boolean expandHeight, Boolean upscale, Boolean quantize)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.SetImage(Image img, Boolean EightBitCompression)
   at com.clusterrr.hakchi_gui.NesApplication.Import(String inputFileName, String originalFileName, Byte[] rawRomData, Boolean asIs)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.AddGames(Tasker tasker, Object syncObject)
A generic error occurred in GDI+.   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.ProcessImage(Image inImage, String outPath, Int32 targetWidth, Int32 targetHeight, Boolean expandHeight, Boolean upscale, Boolean quantize)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.SetImage(Image img, Boolean EightBitCompression)
   at com.clusterrr.hakchi_gui.NesApplication.Import(String inputFileName, String originalFileName, Byte[] rawRomData, Boolean asIs)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.AddGames(Tasker tasker, Object syncObject)
Tasker completed all tasks, conclusion: Error
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Saving selected games
Saving configuration
.Executing task: GameTask.DeleteGames
Tasker completed all tasks, conclusion: Success
..Executing task: AddGamesTask.AddGames
Saving application "CLV-I-YTMKX" as CLV-I-YTMKX
Saving application "Enduro" as CLV-I-YTMKX
enduro.zip: A generic error occurred in GDI+.   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.ProcessImage(Image inImage, String outPath, Int32 targetWidth, Int32 targetHeight, Boolean expandHeight, Boolean upscale, Boolean quantize)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.SetImage(Image img, Boolean EightBitCompression)
   at com.clusterrr.hakchi_gui.NesApplication.Import(String inputFileName, String originalFileName, Byte[] rawRomData, Boolean asIs)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.AddGames(Tasker tasker, Object syncObject)
A generic error occurred in GDI+.   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.ProcessImage(Image inImage, String outPath, Int32 targetWidth, Int32 targetHeight, Boolean expandHeight, Boolean upscale, Boolean quantize)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.SetImage(Image img, Boolean EightBitCompression)
   at com.clusterrr.hakchi_gui.NesApplication.Import(String inputFileName, String originalFileName, Byte[] rawRomData, Boolean asIs)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.AddGames(Tasker tasker, Object syncObject)
Tasker completed all tasks, conclusion: Error
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Saving selected games
Saving configuration
..Executing task: GameTask.DeleteGames
Tasker completed all tasks, conclusion: Success
.Executing task: AddGamesTask.AddGames
Saving application "CLV-Z-COFYR" as CLV-Z-COFYR
Saving application "ffightu" as CLV-Z-COFYR
ffightu.zip: A generic error occurred in GDI+.   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.ProcessImage(Image inImage, String outPath, Int32 targetWidth, Int32 targetHeight, Boolean expandHeight, Boolean upscale, Boolean quantize)
   at com.clusterrr.hakchi_gui.NesMenuElementBase.SetImage(Image img, Boolean EightBitCompression)
   at com.clusterrr.hakchi_gui.NesApplication.Import(String inputFileName, String originalFileName, Byte[] rawRomData, Boolean asIs)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.AddGames(Tasker tasker, Object syncObject)
--- End of DEBUGLOG.TXT content ---

**Comment by DanTheMan827** [comment]
Is this all games or specific ones?

**Comment by DanTheMan827** [comment]
Is this all games or specific ones?

**Comment by alptolga** [comment]
It happens in all games. I found a way to fix the issue. Before adding game from the application, I change language from settings menu. It is necessary to change language before adding game, if you open hakchi new.

**Comment by DanTheMan827** [comment]
What is the language for your computer set to?

**Comment by alptolga** [comment]
Turkish.

**Comment by DanTheMan827** [comment]
Did you extract a fresh copy of 3.5.2, or was it upgraded from an old version?

Do you have Turkish listed in the available languages?

**Comment by alptolga** [comment]
Available languges are English, French and German in 3.5.2
 I first used self extract package but after I lived the problem, I tried installer release. I didn't upgrade it from an older release.
 I think someting was broken many release before. Because 1.1.0 is working properly.

**Comment by SqRpEr** [comment]
@alptolga dostum çok sağol ya sayende 2 senedir kullanamadığım hakchi ce problemimi çözdüm. tek derdim windows dilimmiş. 

I told him that my only problem was my windows language.
