### ISSUE TITLE
Problem when assigning core mame2003-plus to roms from UI

### ISSUE THREAD

**Issue by superurbi** [TeamShinkansen/Hakchi2-CE#193]
I'm not sure if this issue has been fixed or not, but I just wanted to address an error seen for you guys:
Using Hackchi2 CE V3.5.2

When I select a ROM in the left pane I can assign a core to be run with. OK, when you assign the mame2003-plus core the command line is modified with /bin/mame2003_plus command and not with /bin/mame2003-plus one, that is the good one (as is reported by the core help info).

So it does not work until you fix it manually.

**Comment by KMFDManic** [comment]
@superurbi Thanks for the heads up on the Emulation Core Selection not using /bin/mame2003-plus  This is fixed and will show up in the very next Hakchi.  For now, you can manually amend it, directly within hakchi, just by simply changing the hyphen to an underscore.  It will be automatic, next Update!
