### ISSUE TITLE
Retroarch 1.7.4a not recognizing Clovercon controllers on Snesmini after game sync. 

### ISSUE THREAD

**Issue by Addest3** [TeamShinkansen/Hakchi2-CE#195]
When starting a game with the Snex9x core on an SnesMini, an error pops up saying Clovercon 0% not configured 0/0 and I have no input controls other than the return to Snesmini menu combination. It appears that reinstalling the module fixes it but only temporarily.

**Comment by DanTheMan827** [comment]
This happens consistently?

Do you have any other mods installed like external retroarch?

looks like #153 is the same issue

**Comment by Addest3** [comment]
> 
> 
> This happens consistently?
> 
> Do you have any other mods installed like external retroarch?
> 
> looks like #153 is the same issue

I can't get it to replicate the issue 100%, it is seemingly random. I've tried tracing my steps as much as I can but it will randomly show up as not configured after plugging the SNES mini up to a service like Hakchi to update cores/games for Retroarch. I've tried fresh installs as well. It hasn't happened in a few days at this point. I was however able to find the version available to SNES mini users:

Built on: Thu 20 Sep 17:24:27 BST 2018
Git commit: 169dc22c68

Maybe this will help going forward. 

Edit: And no other mods.

**Comment by KMFDManic** [comment]
@Addest3 Do you still have this issue?

**Comment by Addest3** [comment]
@KMFDManic Unsure, haven't booted the system in a few weeks. Last I could tell, no, I wasnt having the issue still but it was random before. Let me do some updates and testing today and I will report back soon.

**Comment by KMFDManic** [comment]
If you can, uninstall current retroarch and any NES Cores and try with retroarch 1.7.5 Xtreme from KMFD Mod Hub.  It should auto configure controllers fine.  Keep me posted!

**Comment by Addest3** [comment]
Alright, I will try that release today and let you know as soon as I can. Might be later.

**Comment by KMFDManic** [comment]
Fantastic! I will help you sort things out. I will check back with you once you test.

**Comment by KMFDManic** [comment]
@Addest3 If you are on the latest Hakchi, do kernel install/repair, and that should reinstall clovercon.  As far as controllers, many are accounted for if you install the latest RetroArch 1.7.6 Xtreme, which can be gotten directly via Hakchi, from KMFD Mod Hub, under Modules Tab.  If you need any further assistance, be sure to let me know!
