### ISSUE TITLE
hakchi  CE automatically deletes the games im trying to add

### ISSUE THREAD

**Issue by hunatae** [TeamShinkansen/Hakchi2-CE#197]
i downloaded all the different hakchi doom games. i unzipped them, then dragged the folders to the hakchi games folder. then when i open up hakchi to add the games to my snes, it says game is invalid- deleting...
i had to use the download link on the actual hakchi games website to get the games; because doing the download directly from the mod store in Hakchi CE would always give me an error at some point through the download and the download would fail. 

i will add the exact message when i get a chance to access the other computer i use for hakchi.

**Comment by DanTheMan827** [comment]
The zip files aren't meant to be extracted, just drag them onto hakchi and it'll handle them

**How to Use:**
- Make sure you have Hakchi CE installed and RetroArch installed on your mini
- Download the Hakchi DOOM zip
- Drag the zip over to Hakchi CE and export/sync it to your mini.
- Shoot stuff.

As far as the mod store failing to download, that could be a hiccup with the server or your internet connection.  I was able to download the games without issue.

**Comment by hunatae** [comment]
yes i have slow internet. i figured 200 kb/sec is too slow for mod store to download correctly without failing.
i did get the doom extracted folder added once, but i will try adding the whole zipped folder.

**Comment by DanTheMan827** [comment]
I'm going to close this issue then, if you still have the problem, just comment on this issue again

**Comment by hunatae** [comment]
![doomerror_files-min](https://user-images.githubusercontent.com/34247354/53835861-b0093000-3f4b-11e9-9540-80c0d3f6b667.png)

i got 1 doom to work. all the others give me this message. just looking in the folders. they're all missing the main game file....

**Comment by DanTheMan827** [comment]
you have to provide the wad files, this doesn't include them

**Comment by hunatae** [comment]
i did add the wad files. and i did the command line --load-base-wad 
i tried all the wads i have doom1 doom2 tnt plutonia, none work.

**Comment by hunatae** [comment]
unless the wads i downloaded are no good. it's possible...

**Comment by DanTheMan827** [comment]
keep in mind, the wad file names are case sensitive, they have to be named exactly as expected.

**Comment by DanTheMan827** [comment]
keep in mind, the wad file names are case sensitive, they have to be named exactly as expected.

@swingflip could better help with this than me though

**Comment by hunatae** [comment]
i copied and pasted the exact name of the wad rather than type it out. i have an idea to try though. after reading installation instructions, i've been adding the wads AFTER adding the game to hakchi. so i will add the wad to the zipped folder before even adding the game to hakchi. will see if that works.

**Comment by hunatae** [comment]
if not, i will talk to swingflip then. thanks for your help though

**Comment by bslenul** [comment]
Hakchi Doom from the Mod Store?

* Once its added to hakchi CE, right click it > Show in Windows Explorer.
* Go to DOOM_1_files\ folder.
* Rename your full game wad into DOOM1.WAD (all caps) and replace the existing one.
* Sync/export.

Go to Mod My Classic Discord or miniSNESmods subreddit if you're still having trouble, but this is not a hakchi CE issue ;)

https://discord.gg/8gygsrw
https://reddit.com/r/minisnesmods

**Comment by hunatae** [comment]
@bslenul thank you, yes i i know the error is somewhere on my end. i'll get it eventually. my doom wad i have is doom1.WAD so i will try changing it to all caps then add it. might be that simple.

**Comment by hunatae** [comment]
![HRlogo-min](https://user-images.githubusercontent.com/34247354/54301402-17dafe80-457c-11e9-80d7-6364acd7aaea.png)
![zDoomcred-min](https://user-images.githubusercontent.com/34247354/54301403-17dafe80-457c-11e9-8ad2-ad4c5dd317b2.png)
![zDoomsplash-min](https://user-images.githubusercontent.com/34247354/54301399-17426800-457c-11e9-9a51-3a331539ba6f.png)

so i get these 3 images then it goes back to the game select screen on the snes. this is the best i got with brutal doom. all the other ones gives the cannot find files error.

**Comment by bslenul** [comment]
People had trouble with some WAD files on Reddit, I'm using the ones I got on Steam and they work fine. Try grabbing the WAD from another source maybe.

But please, come to Discord or Reddit if you're still having trouble (links in previous reply), again this has nothing to do with hakchi CE :p

**Comment by hunatae** [comment]
this is everything....
![Screenshot (854)](https://user-images.githubusercontent.com/34247354/54307910-19abbe80-458a-11e9-9f6e-96b572e9b802.png)
![Screenshot (855)](https://user-images.githubusercontent.com/34247354/54307912-1a445500-458a-11e9-8fcc-b26f4b4f5138.png)
![Screenshot (856)](https://user-images.githubusercontent.com/34247354/54307914-1b758200-458a-11e9-9b20-1c33290ce0a8.png)
![Screenshot (857)](https://user-images.githubusercontent.com/34247354/54307916-1c0e1880-458a-11e9-8966-518d73797812.png)
![Screenshot (859)](https://user-images.githubusercontent.com/34247354/54307917-1ca6af00-458a-11e9-8d2e-ed2ff9e6402a.png)
![Screenshot (860)](https://user-images.githubusercontent.com/34247354/54307920-1d3f4580-458a-11e9-8a6e-df2105801787.png)
![Screenshot (861)](https://user-images.githubusercontent.com/34247354/54307921-1dd7dc00-458a-11e9-91fd-2d326bf98557.png)
![Screenshot (862)](https://user-images.githubusercontent.com/34247354/54307923-1e707280-458a-11e9-9237-195e1581fddb.png)
![Screenshot (863)](https://user-images.githubusercontent.com/34247354/54307924-1fa19f80-458a-11e9-8cc8-85e15da3e95e.png)
![Screenshot (864)](https://user-images.githubusercontent.com/34247354/54307928-216b6300-458a-11e9-8951-aa2d9b86c15c.png)
![Screenshot (865)](https://user-images.githubusercontent.com/34247354/54307930-216b6300-458a-11e9-80f5-a76b6238aaf6.png)
![Screenshot (866)](https://user-images.githubusercontent.com/34247354/54307933-2203f980-458a-11e9-85af-4d8e0259735b.png)

**Comment by hunatae** [comment]
i posted it on your sites as well
