### ISSUE TITLE
Hakchi2 asks to boot in fel mode when installing modules

### ISSUE THREAD

**Issue by Shinryuken** [TeamShinkansen/Hakchi2-CE#20]
Hi,

i noticed that when the nes mini is off and you try to install new modules the program asks you to boot in fel mode.

Instead, if the nes mini is online (no fel) then hakchi2 just upload the modules as it should

hakchi2 CE v1.1.0

**Comment by DanTheMan827** [comment]
This is by design, that way you could remove a misbehaving mod that may be preventing the system from booting

**Comment by Shinryuken** [comment]
I see, thx

i'm closing it
