### ISSUE TITLE
Request for more grouping options

### ISSUE THREAD

**Issue by igoticecream** [TeamShinkansen/Hakchi2-CE#21]
Hello guys.

I´d like to request a way to group wich roms have been compressed and which havent, aditionally, group by box art: which have boxart and which have the default one.

Thanks you for your work

**Comment by daPhie79** [comment]
the group by boxart is added. group by compressed, i'm questioning the usefulness and for every option i add, it increases complexity of the sorting code. i'll be thinking about it!
