### ISSUE TITLE
Link to add more games doesn't work

### ISSUE THREAD

**Issue by jamescastells** [TeamShinkansen/Hakchi2-CE#210]
The top part of the GitHub page states:

Tool that allows you to add more games to your NES/SNES Classic Mini http://teamshinkansen.github.io/

But the link doesn't work.

**Comment by DanTheMan827** [comment]
Yeah... there was never really a proper website for this project...

So now I just changed it to the discord server that most people go to for help (https://discord.gg/79MVzAn)
