### ISSUE TITLE
Access to the path is denied

### ISSUE THREAD

**Issue by Redfield1225** [TeamShinkansen/Hakchi2-CE#213]
Hello, I am currently running hakchi CE v3.5.2 (Debug) on my SNES classic, I never had a problem with the hakchi program until recently and I changed nothing. 

I cannot add, edit, any games, or core files, when I attempt to do any of these I get a message saying "Unhandled exception has occurred in your application. If yoiu click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
Access to the path is denied."

at the top of the debug window it says "..Could not find file hakchi 2_CE\debuglog.txt' at System.IO.__Error.WinIOError(Int32, String maybe fullPath)

at the bottom of the window it also says:

Downloading motd file, URL:https://teamshinkansen.github.io/motd.md
Access to the path is denied.

I read on a forum to uncheck "Read only" on the games folder in the hakchi 2 CE folder and that did nothing.

**Comment by DanTheMan827** [comment]
have you ever run the application as administrator?

**Comment by Redfield1225** [comment]
Yes, same thing happens.

**Comment by Redfield1225** [comment]
I also went into my Admin settings and made sure all permissions were allowed, still nada.

**Comment by DanTheMan827** [comment]
try making a copy of the folder to a new location and see if that fixes anything

**Comment by Redfield1225** [comment]
The entire hakchi 2 folder?

**Comment by Redfield1225** [comment]
I moved the entire Hakchi 2 folder from my desktop to my documents and still the same thing.

**Comment by KMFDManic** [comment]
@Redfield1225 Follow this video:

https://www.youtube.com/watch?v=mGooTybpodM

Essentially, hakchi is false positived by firewall/virus protection, and leads to denial of the specific file you attempted to use.  It is very easily fixed and my video has helped several thousand people.

**Comment by KMFDManic** [comment]
@Redfield1225 by your lack of response, I am going to assume the issue is resolved.  Feel free to respond if you are still having any problems whatsoever:)
