### ISSUE TITLE
Select core is disabled for stock games

### ISSUE THREAD

**Issue by DanTheMan827** [TeamShinkansen/Hakchi2-CE#215]
**Describe the bug**  
Select core is disabled for stock games

**To Reproduce**  

Right click on a stock game, select core is grayed out

**Expected behavior**  
Right click on stock game, be able to select core

**Comment by daPhie79** [comment]
didn't i code this behaviour by design? it doesn't make much sense to use a different core on stock games...

**Comment by DanTheMan827** [comment]
Netplay and retroarch shaders

But in the case of SNES, I think audio would have a problem...

**Comment by bslenul** [comment]
Yes SNESC games have trouble with audio because of the PCM format Nintendo used or something.

For the NES however I compared a few with a no-intro set and it seems to be the same roms. But there are a couple FDS games in .qd format that are not supported by RA NES cores.

**Comment by daPhie79** [comment]
oh, you're right. it should be left available for nes games. it only makes sense for snes stock games.
