### ISSUE TITLE
Display isn't 4/3

### ISSUE THREAD

**Issue by famicom01** [TeamShinkansen/Hakchi2-CE#217]
Hello
I come to install hakchi 3.52.When I
lance launches a game, the game display is not
not in 4 / 3.The size of the screen is no longer
small. If anyone has an idea of ​​the problem[20190406_234328](https://user-images.githubusercontent.com/49367186/55684547-4ade9b00-594c-11e9-9f4b-e206616c854e.jpg)
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by KMFDManic** [comment]
RetroArch Settings, Video Integer, toggle on/off, depending on preference.  It is best off for a majority of Cores, so I have as default off.

**Comment by famicom01** [comment]
Hi

Thank you for answer

**Comment by KMFDManic** [comment]
@famicom01 Glad to have been of help!
