### ISSUE TITLE
Mod  Store Not There

### ISSUE THREAD

**Issue by dan626** [TeamShinkansen/Hakchi2-CE#218]
I have updated to 3.5.3 and can see that the Mod Store is no longer available in modules 

I have clicked on modules and the only option is KMFD's Mod Hub

Is there a reason it has been removed?

**Comment by madmonkey1907** [comment]
More like multiple reasons really. swing and his followers bullied kmfdmanic for a long time, which made me seething with rage, but still we tolerated it. That didn't really help matters, only made it worse, as he branched out into attacking other people. Sometimes you have to draw the line. I can't force swing to be less of a dick, no one can. What I can do, is stop him from using my code to be a dick. As such I made it very clear I won't tolerate my code and swing code in the same app.

Patton explains it better than I can here https://www.youtube.com/watch?v=ttCIcyxOX3c

All that shouldn't affect users too much, missing hmods will be migrated to km hub in the coming days.

**Comment by pathartl** [comment]
So much for not throwing shit around anymore. Ya'll really need to tone it down.

**Comment by DNA64** [comment]
I've remained quite neutral on this whole thing, but I'm growing tired of the childish drama on both sides of the fence and am in agreement with pathartl. 

I'll just say this, **this hurts nobody but the end users** (As you may have noticed by everyone in support asking where the store is). And I think **it's very deceiving to not mention that the update will remove the ModStore**, and instead simply state "This release adds help links and removes some **unneeded code**".

That said, the project can be forked (As it already has countless times) if someone really wants to,and the end users can simply stay on the older version as I'm sure many will do for now. Truth be told, the ModStore wasn't a long term plan anyways as the entire system is in need of a major overhaul imo.

Finally, I will be releasing a temporary solution shortly until we have something better in place.

**Comment by darkdev1** [comment]
The madmonkey's rage against swingflip is mad. Removing the mod store wasn't a dick move? Swingflip isn't there anymore since he bullied by blind youtubers and madmonkey still has to insult him? I never bullied kmfdmanic but he's adult and madmonkey doesn't have to protect him. It's pathetic. I always speak by myself and I never let anyone direct me.
It's not madmonkey's code since it's a fork and it was daphie and DTM who coded the windows part. The mod store wasn't made by swingflip either.
It's Patton Play's, not Patton Explain's. Patton Play's doesn't understand GPL licenses. He's neither a coder nor a hacker and he made insane videos for his benefit. That's all I have to say about this bullshit.

**Comment by KMFDManic** [comment]
@dan626 You can re-add the Repo with the instructions detailed at:

https://www.reddit.com/r/miniSNESmods/comments/bejo1s/new_repository_mod_store_for_hakchi_2_ce_353/

Issue now closed, as you should have no trouble re-adding it.  Feel free to respond if you have any issues, and I will personally assist you in getting back in action.

**Comment by pathartl** [comment]
I've started providing alternate builds that has both the mod store + KM's mod repo added:
https://github.com/pathartl/Hakchi2-CE

There's some other stuff that's been changed as well. These builds may not be super stable in the future, as I'll be going through the application and changing things to be more user friendly where I see fit.
