### ISSUE TITLE
Blue Screen Windows 10 1809

### ISSUE THREAD

**Issue by impeeza** [TeamShinkansen/Hakchi2-CE#220]
Every time I open hakchi2-ce-3.5.3 got a BSOD With STOP Code WDF_VIOLATION 

The extra codes are:
0x000000000000000D
0xFFFFAB05AC69EDF0
0xFFFFAB05BEB0A1E0
0xFFFFAB05AC5E68A0

Happen even if the NES Classic Mini is turned off or not connected to Computer:

![image](https://user-images.githubusercontent.com/41979604/56818385-25d39e80-680d-11e9-8c32-86c39f575e7f.png)

Drivers are right:
![image](https://user-images.githubusercontent.com/41979604/56818770-f5d8cb00-680d-11e9-80f2-c42595d1877a.png)

And the only way to use Hakchi is in a VMWARE virtual Machine with the same version of Windows.

Any toughs or help, thanks a lot.

**Comment by DanTheMan827** [comment]
This isn't a problem with CE per-se, this is a problem somewhere else in the chain.

The only way I could possibly help with this is if you can give me a minidump for that BSOD

`C:\Windows\Minidump` should have the crash information for Windows

But it might be caused by just having old drivers for some of your devices (probably chipset)

**Comment by impeeza** [comment]
Hi, yes I think is a Driver Issue but I have no idea where to start to look,  the system is recently fresh installed using latest versions of drivers in MSI, Intel and other pages :(

This is a minidump recently created.  Thanks a lot for your help.

[042619-38453-01.zip](https://github.com/TeamShinkansen/hakchi2/files/3122020/042619-38453-01.zip)

**Comment by impeeza** [comment]
Update:

Looking for old drivers, and making some diagnostics,  I did disconect EVERYTHING with a cable from my computer, and just connect the NES Mini and run Hakchi, IT Works!  so repeat connecting each device one at time and find the offending device.  Is a Generic USB 3.0 Hub:
![IMG_20190426_112417](https://user-images.githubusercontent.com/41979604/56822805-d2b31900-6817-11e9-91c1-3002e78de914.jpg)
The estrange thing is the driver is the one of the Operative System:
![image](https://user-images.githubusercontent.com/41979604/56823110-946a2980-6818-11e9-8193-02fb142b4a29.png)
So I have no idea how to update/change the driver.
If Hakchi is running and I connect the External USB Hub the system runs fine and even when I synchronize new games or connect via SSH to Mini all works fine.

Could be a unhandled exception when listing devices which is get lost with the two USB 3.0 Hubs? (I am just thinking crazy)

Regards

**Comment by impeeza** [comment]
any clue on get this working?

regards

**Comment by impeeza** [comment]
Hi, if worth, these are  debuglog.txt compared when run with the USB Hub connected and disconnected
![image](https://user-images.githubusercontent.com/41979604/58441785-6e030c80-80aa-11e9-94c0-a165598028db.png)

**Comment by impeeza** [comment]
I can confirm the Issue still happen on Windows 10 1903 and Hakchi 3.7.0 ;(

**Comment by impeeza** [comment]
Hi Update:

I just buy a New 4 ports USB 3.0 Hub, and the same problem, when the hub is connected to system and use Hakchi 3.8.0 Debug the system go to the same BlueScreen, disconnecting the Hub all works fine.
