### ISSUE TITLE
hidden folders / child safety

### ISSUE THREAD

**Issue by yepyepyep4711** [TeamShinkansen/Hakchi2-CE#221]
**Is your feature request related to a problem? Please describe.**
I'm a dad, and I gleefully introduced my kids to the nes mini. But for that, I had to excise the bloodier games from the console (and the roms I added later on), although some of them I would really like to play myself.

**Describe the solution you'd like**
A somehow hidden folder that could be activated with a button combination or another trick. For example, I'm using select+start during games to reset to the menu. During the menu, this thus does nothing and could be used to make the folder appear. Plus, tiny fingers will hardly press this by mistake (I hope :) ). The shortcut could have a duration to it, like press select+start for two seconds, just to be on the safe side.

**Describe alternatives you've considered**
I guess I could put all those roms on a flash drive and only put it in when I want to play. Hmmm.

**Additional context**
Cheers from a happy retrogaming family :)

**Comment by yepyepyep4711** [comment]
I've just checked the install USB host mod how-to https://nesclassicmods.com/how-to-install-usb-host-mod-to-nes-classic-mini-increase-storage-with-external-usb-flash-drive-or-hard-drive/

This sounds like it wouldn't do what I want. If the drive is not connected, the games would still show up in the menu, right? They just wouldn't run?

**Comment by ghost** [comment]
I would suggest to build a modificator on each game which can be set for 18+ 
and after a logon within snes mini (pin code) all that games could be accessed. otherwise not.
2 modes for just not accessible games and do not show games unless 18+ logon.

that would be great ;)

**Comment by KMFDManic** [comment]
@yepyepyep4711 A method can probably be worked out for you.  But, if you do go the USB-HOST route, you simply can have a flash drive with your specific set of games, and one for theirs.  It is a very reasonably priced investment, and will also allow you to run many more systems, such as PS1, etc.  It only requires an inateck OTG device, along with at least a recommended 32 GB Sandisk Flash Drive, formatted to NTFS/FAT32/Ext4.  Just shut system down, pull the drive, replace with theirs.  Nice and simple.  

It can still be an interesting scenario to have it where you would need to input Up Up Down Down Left Right Left Right B A Start, to access the "Content".

**Comment by yepyepyep4711** [comment]
@KMFDManic an on-board solution would be preferable, since I only intend to use the nes mini for nes games, and as such, I'll never run out of space. Also, the idea is for the kids to operate the console themselves, so any obligatory additional step to start-up is another thing potentially going wrong, which I'd like to prevent. So a secret combo would be fine, or a new item in the settings of the menu (as far as I'm concerned there would be no need for a pin, just "show hidden folders", but that's just me). What method do you have in mind? I thought since we already had folder management, I'd be lucky and hidden folders would be not too big a jump? Maybe? :)
On the USB idea: I can't test, because I don't have an OTG device yet, but are you saying the nes mini reads the storage at boot and dynamically displays what it finds? I thought the menu was built while connected with the software on the computer. Bonus question: so it would be possible to leave the "kids' games" on the console, and put the "big kids' games" on usb, and the relevant folder and icons would only show up when the USB is actually plugged in?

**Comment by KMFDManic** [comment]
One little problem @yepyepyep4711 Going this entire route would open up a whole new can of worms, much akin to telling a lie, then needing to come up with more lies to cover up that lie, heh.  Even if you "hid" the games, you would have to essentially clear the tracks and record that you currently have run them, as they would show up in recent history, and so on.  

As far as your question about kids games on system, and yours on USB, that "is" possible.  But, it can lead to other conflicts, which you are probably best off avoiding.  I would strongly suggest you opt for an Inateck OTG device, and set up 2 flash drives, one for the kids, and one for you.  You simply pop in the drive you want to load into the OTG, boot up, and are golden.  Trying to hide stuff from the kids might annoy you in the long run.

Another option is to get a Playstation Classic, which is quite cheap now, and let the kids use that, or you use it.  And, of course, there is an HMOD, that locks the system down, and makes it so the Konami Code needs typed in, in order to play it:)

Up Up Down Down Left Right Left Right B A Start.  

No matter the case, I can help you find a solution.  But, even if you hide them, you will still need to clear the recent history.  Keep me posted, and we will go from there.  

PS:

There is a slightly more technical way we can pull it off.  But, it would just require you to do 2-3 quick steps each time you want to load up your personal collection.

**Comment by yepyepyep4711** [comment]
@KMFDManic the OTG is on my list for my next order, so I'll try that eventually. In my head I'll not be using two sticks, though, but one for me and the kids get whatever is on the console when no OTG and no sticks are present. That would work, right?
But please do tell me about that method you mentioned last. I'm curious :) and I don't mind two three steps more for me, as long as it doesn't add complexity for the kids

**Comment by yepyepyep4711** [comment]
So I mit OTG arrived today, and it works nearly as I hoped. No stick: kids can play and only see their games. Stick in: only my games (I had hopes for my games plus theirs). So may end up doing a reduced (kids) and a complete (me) set, but that's not a big thing.

One thing though I would wish would be easier, it's the list management.
Managing different repositories of roms, like I'm doing, depends on some form of saving who gets what. In Hackchi, it's through the "File->Selection presets" items. Sadly, it's not very user friendly at the moment. For example, there is no way to update a preset. You have to overwrite it, which means typing its name again (better choose a short name!).  Also, presets are not lists you can edit, so if you want to create different presets, you'll be swapping back and forth to check what's in this one, what's in the other, and if you forget to overwrite the preset you're working on to check on some other, you've lost your changes and have to do them again. Maybe this could be improved?

Anyway, thx @KMFDManic for your help so far :)

**Comment by KMFDManic** [comment]
@yepyepyep4711 I knew you'd much prefer that solution with OTG.  If you want to keep games separate, the easiest thing to do is just have "another" hakchi directory!  I have several on my PC for various test set-ups.  Just make a folder with hakchi, and rename is hakchi_kids, or similar.  Whatever works to keep you better organized without conflict of mixing up libraries.  You should have no trouble synching/exporting games from either directory.  If you do, simply install/repair kernel again, and you will be good to go!  Hope this helps out!  Let me know if you need any further assistance:)

**Comment by yepyepyep4711** [comment]
@KMFDManic so under "Team Shinkansen", copy-paste the "Hakchi2 CE" folder and add an additional shortcut to the start menu to "Hakchi Kids", or something like that. I can do that. As a matter of interest, where are the settings, presets, game lists, etc, saved? I can't seem to find a file or folder that's younger that the date of installation, it doesn't make sense?
