### ISSUE TITLE
deprecated FAQ about the kernel?

### ISSUE THREAD

**Issue by yepyepyep4711** [TeamShinkansen/Hakchi2-CE#222]
**Describe the bug**  Does documentation fall under bugs?
The FAQ states:

Q: I missed my original kernel image :( Where I can find it?

A: You can easily find it on torrent trackers.

Could it be that's deprecated? The software itself hides the function to download the original kernel from the machine under Advanced -> Dump original kernel (legacy). I assume there is a reason for that? Maybe that is not really needed anymore? Maybe the software made a backup of the original when flashing the new one? Maybe it's still there, just bypassed? I don't know.

**To Reproduce**  
Look it up in the FAQ and software menus
https://github.com/TeamShinkansen/hakchi2/wiki/FAQ

**Expected behavior**  
A clear explanation either in the FAQ or software so that I do not worry whether or not I will need this piece of software later on :)

**Comment by DanTheMan827** [comment]
That function is there only for users that would want to go back to an older version of hakchi2

The system makes a backup copy on the nand directly so the user doesn't run the risk of mixing them up

**Comment by yepyepyep4711** [comment]
Thx for the answer, but then where is it? I would want to put it somewhere safe

**Comment by yepyepyep4711** [comment]
sorry, I guess I read over the "nand" part the first time I read your answer. So you're telling me it's on the console itself. Great stuff. Cheers
