### ISSUE TITLE
emulate two game boys for two player tetris

### ISSUE THREAD

**Issue by yepyepyep4711** [TeamShinkansen/Hakchi2-CE#226]
**Is your feature request related to a problem? Please describe.**
I want to emulate two Game Boys simultaneously, split the screen in to vertically and map one GB to each controller. I know some emulators offer that (e.g. No$gba), would it be possible on the nes mini?

**Describe the solution you'd like**
I'm not sure. I guess starting a game, going into some options dialogue and then adding the second console, which would be automatically linked to the first one and mapped to the second controller?

**Describe alternatives you've considered**
Finding a tetris version for the nes that allows two players in a competitive mode and where you send garbage to the opponent when you make lines. It doesn't seem to exist.

**Additional context**
The goal is to play the game boy version of tetris. The reason for that is that it's the only version where you can send garbage to your opponent when make more than one line. Plus, it's the one with Korobeiniki for music :)

**Comment by DanTheMan827** [comment]
You'd have to contact libretro about this, all we do is use their cores and frontend

**Comment by yepyepyep4711** [comment]
@DanTheMan827 that would be the retroarch repo?

**Comment by yepyepyep4711** [comment]
@DanTheMan827 and anyone who would be looking for this, here's the solution I found: add the experimental core TGB Dual through KMFD's Mod Hub in Hakchi, then add regular Game Boy Nintendo Tetris to your collection. Right-click on it in Hakchi and go to the dialogue to specify a core. There, pick TGB Dual. Then start the game on your mini, go to the emulator options (it's start+select on my console), under options in the quick menu you'll find link cable emulation. Enable, reload and you should be set. Left and right display will be mapped to controller one and two, respectively. Now if I can find a way to add a nice looking Game Boy bezel, I'm set ;)

**Comment by yepyepyep4711** [comment]
aaaand, I answered this one as well. :D
KMFD's Mod Hub has a shader pack under Addons. Some will slow down the machine too much, but you'll probably find what you want there nevertheless. Once installed, run the game, go to emulation options and look for shaders -> load shader preset. There's a folder called "handheld"
