### ISSUE TITLE
Boot splash option not working when booting from usb

### ISSUE THREAD

**Issue by Shinryuken** [TeamShinkansen/Hakchi2-CE#23]
I noticed that when you select:

Settings > Boot splash > Disable boot splash

the splash image still shows when booting from usb.

**Comment by daPhie79** [comment]
this is by design. the boot splash option on usb is a file you put on your usb key. you control it! 👍

**Comment by Shinryuken** [comment]
oh i understand now, thx.

closing

**Comment by igoticecream** [comment]
Actually, he´s right, i have found this bug too

1. Settings > Boot splash > Disable boot splash and start the nesc from the nand: No boot screen
2. Without touching the config, turn off the nesc and start it from the usb: Default boot screen appears (the ugly one that says toc toc hakchi)
3. Without touching the config, turn off the nesc and start it from the nand: The default boot screen appears once again.

if you could please reopen this and take a look, we´ll be grateful :D

**Comment by daPhie79** [comment]
hmm I'll try to take a look at this. this would be a hakchi script feature or issue

**Comment by daPhie79** [comment]
any update if this still happens with 1.2.1 ?

**Comment by b0mb4rm4n** [comment]
It still happens with 1.2.1...
Same thing - when booting with usb stick the „disable boot splash“ option does not work and it shows the knock-knock-screen...

**Comment by b0mb4rm4n** [comment]
Still exists in v1.2.2 :-(

**Comment by hauptstadtkind83** [comment]
In v1.2.5 the error still exists...

**Comment by daPhie79** [comment]
does the same thing happen when you also put a blank image on your USB drive in /hakchi/boot.png? I think when a USB drive is connected hakchi tries to get its boot image from there. otherwise I'll talk to madmonkey about this.

**Comment by hauptstadtkind83** [comment]
In newest hakchi2 CE 3.4.1 when you choose no splash screen it works as it has to work - no boot screen with and without usb stick 👍

**Comment by daPhie79** [comment]
happy to hear!
