### ISSUE TITLE
Can't add folder icons

### ISSUE THREAD

**Issue by asdqqq33** [TeamShinkansen/Hakchi2-CE#230]
**Describe the bug**  
Can't add folder icons.  Making any changes to the files in the folder_images folder does not affect the folder icons available in the program.  I can alter any of the files that are in the folder, add new ones, or even delete the whole folder and it has no affect on the icons that are available to choose for folders in the program.  Tried uninstalling and reinstalling program, no change.  

**To Reproduce**  
1. Change anything in the folder_images folder.  
2. Click on Structure in the program.  
3. Open the Folders Manager.  
4. Select a Folder.
5. Click on Menu Icon.
6. Available options do not change to reflect any changes to the folder_images folder.  

**Expected behavior**  
The Menu Icons available would reflect the content of the folder_images folder.

**Comment by DanTheMan827** [comment]
Did you install the program or extract from the zip file?

If you installed, make sure you're modifying the folder images in the hakchi2 folder in documents and not the one in program files

**Comment by asdqqq33** [comment]
That was it, thank you.
