### ISSUE TITLE
Incorrect window size on Linux

### ISSUE THREAD

**Issue by renom** [TeamShinkansen/Hakchi2-CE#233]
The latest version (v3.5.3) runs on Linux using Mono without crashes, but the main window contents only partially fit to the window. It's possible to force window resizing on KDE even if it's disabled on app level, but it'd be better if that could be fixed without such tricky methods. Also, not sure if GNOME and other DEs and WMs allow to change window settings.

<a href="https://user-images.githubusercontent.com/4979122/59463367-7f7c4080-8e2e-11e9-8fbb-f3444f69fb8d.png"><img src="https://user-images.githubusercontent.com/4979122/59463367-7f7c4080-8e2e-11e9-8fbb-f3444f69fb8d.png" width="50%" height="50%" /></a>

**Comment by DanTheMan827** [comment]
For a workaround, you can change the language and then change it back to make the window size properly
