### ISSUE TITLE
uninstall Clovershell daemon

### ISSUE THREAD

**Issue by Chris-Annin** [TeamShinkansen/Hakchi2-CE#236]
when trying to synchronize I get an error "Your hakchi installation is running Clovershell daemon.  It is not safe to sync games with Clovershell.  Please uninstall this module in order to sync games safetly."  I cant find any information on how to uninstall modules.  does not appear in the modules uninstall list.

**Comment by DanTheMan827** [comment]
If upgrading from an old version of hakchi2, it's recommended to uninstall the custom kernel with that version and install with hakchi2 ce.

**Comment by Chris-Annin** [comment]
thank you
