### ISSUE TITLE
Feature Request: Option to unlock the extra 30mb for more hmods

### ISSUE THREAD

**Issue by haywire27** [TeamShinkansen/Hakchi2-CE#24]
I use USB HOST for the game collection and snes flash memory for hmods only.

Since there is no need for save states on the snes classic flash memory, will you consider adding an option to release the extra 30mb for more hmods?

Thanks in advance guys!

**Comment by TarkinMX** [comment]
I would like to see this as a feature as well. Just unlock the extra flash memory for users to be able to use it for more than just game saves, i.e. games or hmods, whatever suits the user's needs.

**Comment by daPhie79** [comment]
are you talking about the 30mb that is set as "reserved memory" in the app? if that's so, you can reduce that reserved memory if you're also using external saves! normally it should reduce to 5mb reserved memory then.

**Comment by haywire27** [comment]
I actually migrated libretro folder to USB HOST to get around the space issues with NAND.  Please disregard!
