### ISSUE TITLE
I Feel Lucky! search of images doesn't seem to go for direct system and filename match

### ISSUE THREAD

**Issue by JON99999** [TeamShinkansen/Hakchi2-CE#249]
**Is your feature request related to a problem? Please describe.**
I have populated many folders in the standard prepared art folders, but when a match to files is attempted, there are many roms where I have an exact name match in the exact system folder, but the "I Feel Lucky!" seems to get confused.

**Describe the solution you'd like**
When you try to get lucky, it prioritizes the exact name / exact folder combination.

**Describe alternatives you've considered**
I just have to manually edit them when I find the wrong ones.

**Additional context**
Thanks again for this awesome tool.

**Comment by DanTheMan827** [comment]
I'm feeling lucky searches google and uses the first image found.

What you're looking for is the "Scan for new box art of selected games"
