### ISSUE TITLE
Doesn't show hmod size when install

### ISSUE THREAD

**Issue by u4113057** [TeamShinkansen/Hakchi2-CE#25]
Doesn't show hmod size when install

**Comment by u4113057** [comment]
if you can combine install and uninstall hmod to the same page it would be easier for user to decide which one is already install or not

**Comment by gingerbeardman** [comment]
@u4113057 that is a great idea

**Comment by KMFDManic** [comment]
@u4113057 @gingerbeardman This is done for my Next Release.  You will be able to view install sizes via the ReadMe window, whilst each Core/HMOD is viewed.  I had been planning on doing this one for awhile.
