### ISSUE TITLE
Allow Retroarch switching between built in core and alternate core

### ISSUE THREAD

**Issue by JON99999** [TeamShinkansen/Hakchi2-CE#251]
**Is your feature request related to a problem? Please describe.**
I would like to be able to switch between Nintendo's standard core and one of the Retroarch Cores

**Describe the solution you'd like**
When you do start/select to open Retroarch, retroarch allows you to change cores.  Would like the functionality to include the standard core provided by Nintendo in that list.  Would like the functionality to open Retroarch within games opened with the standard Core, to switch to a RetroArch core also.

**Describe alternatives you've considered**
Right now, switching between default core and a retroarch core requires shutting everything down and going back to the laptop and Hakchi 2 to change the default core.  This works, but it is so tedious.

**Additional context**

**Comment by madmonkey1907** [comment]
iirc, you can hold up to disable retroarch and down to enable it, but canoe/kachikachi is not a core

**Comment by JON99999** [comment]
Yes, I understand it's not a core.  

What I'm envisioning is some sort of customization as follows.  While in Canoe/kachikachi, a customization similar to select-down for "home" is inserted.  Just like retroarch is pulled up by select-start, in c/k, select-start would pull up a "switch to retroarch", menu with a list of available cores".  Selecting a core would change the command line/pointer to retroarch and the core and reset the game.  

Then, in retroarch, one of the cores could be essentially a dummy core for c/k.  When you select it, when it launches, it would actually launch a core which sets the game's preferences to run on c/k.  And then after that is set, triggers a relaunch of the game.

I don't know what settings are flipped when you change in the windows hakchi interface to go from the standard emulator to a retroarch core.  Or vice versa.  But those settings are all I'd envision being rewritten with the start-select insert when in c/k.  Or the false retroarch core.  And then a relaunch of the game.

**Comment by JON99999** [comment]
(I will try the up/down functionality tonight.)

**Comment by KMFDManic** [comment]
@JON99999 Since saves can be a conflict when switching from Default Emulator to RetroArch Core, this is not a recommended thing to do currently.  Best to use latest hakchi, and right click, select emulation Core on games for Default or RetroArch Core, apply, Synch or Export.  This way, you can retain "new" saves on either/or.
