### ISSUE TITLE
Bricked after update to 3.6.0

### ISSUE THREAD

**Issue by Franky6581** [TeamShinkansen/Hakchi2-CE#257]
**Describe the bug**  
Updated Hackci from 3.5.3 to 3.6.0 via the app (w10) and now snes mini no longer boots.
Snes mini does not come 'online'

**To Reproduce**  
Update thru app.  At end of update snes mini gives message 'shutting down', then no longer boots

**Expected behavior**  
Have version 3.6.0 running

**Screenshots**  
n/a

**Additional context**  
n/a

**Comment by DanTheMan827** [comment]
as a test, could you try pressing CTRL+F12 to enable the developer menu and then going to  Settings > Developer tools > Download Latest Hakchi and then trying Kernel > Install again?

![image](https://user-images.githubusercontent.com/790119/67593555-04099480-f728-11e9-8c74-2e1b732aab85.png)

**Comment by jlepthien** [comment]
Sure everything is okay with that build? Tried using the zip file and instead of folders I find only files with name art/xxx for example in it. Looks broken to me.

**Comment by ghost** [comment]
fyi, got connection issues on upgrading, it got no boot to pc, tried it several times and then it worked.
reflashed kernel then, now its ok for me.
