### ISSUE TITLE
Can the stock NES mini emulator emulate 50hz PAL mode?

### ISSUE THREAD

**Issue by VadimOsovsky** [TeamShinkansen/Hakchi2-CE#258]
when I set --nes-version=pal flag the game is still 60 hz, however the sound gets glitchy. Is there a way to play games in 50hz? (don't ask why lol)

**Comment by KMFDManic** [comment]
@VadimOsovsky ONLY if you use RetroArch and a Core, such as Nestopia.  You can go into Core Options, and set to PAL:)
