### ISSUE TITLE
Problems after upgrade 3.6.0

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#259]
after upgrading to 3.6.0 the system need several reboots to get connected to pc.
i need to shut it down sometimes 5 times to get a successfully connection.

**Comment by ghost** [comment]
Update: Now its better.
It seems the no connection issue appears after installing kmfd plugins.
later on , without installing its connecting directly.

Update:
after uninstaling _km_mupen64plus_next, snes mini does not connect to hakchi.
need to shutdown and start again.

Update:
if boot.png and menue_music is in usb stick root and not .\hakchi\ (I GUESS) this cause SNES mini to start after a retroarch (OC crash while Dreamcast test) to boot into original SNES Menue.
The games were actually loadable, i thought the nand would overwritten with hakchi... (hum.???)
I had to several times reboot/unplug snes mini from power supply to get hakchi menue again. 
_After I switched that back to correct dirs a C8 error pops up instead ;-)_

Update:
almost every time after uninstalling anything the snes mini does not connect to hakchi again.
the system sound is still popping up. 

Update:
After enable or disable OC setting over telnet the system almost everytime boots up failure or into original snes menue. which takes several tries to boot into hakchi menue again.

**Comment by madmonkey1907** [comment]
oc is better left disabled if you have any other issues. rndis(no connection) is being looked into.

**Comment by ghost** [comment]
yup i directly disable viatelnet for the moment.
problems are popping up anyway..
