### ISSUE TITLE
Some synced games get ".tarstreamref" appended to filename in 1.1.0

### ISSUE THREAD

**Issue by VitalNonsense** [TeamShinkansen/Hakchi2-CE#26]
Ran into something weird when using the new version 1.1.0
I updated my hakchi folder, updated a couple games with new patches/boxart and resynced. Nothing interesting. Then I powered it on, ran a particular game and it wouldn't launch. It's a gbc rom set up to run through gambatte, and the other gbc games still seemed to work fine. 

This one was previously working great and not a game I had made changes to, so I was surprised. After digging around in retroarch menus I found that after my latest sync, the filename had suddenly changed on the console for some reason. On the left below you see a normal entry ending in gbc.7z as it should, on the right you see gbc.7z.tarstreamref. I double checked the games folder under hakchi and everything looked normal in there, the change only happened in the console. 

I went through the whole list and found that one more game also suddenly ended in tarstreamref. Through FTP I simply changed the filenames to remove the extra junk and now they work fine again.
Any idea what caused this issue?

![tarstrea](https://user-images.githubusercontent.com/36638789/36387666-6b56ab72-154e-11e8-995d-c1549dd160f8.jpg)

**Comment by skogaby** [comment]
@VitalNonsense Seems like a bug in some of the new sync logic. We added the concept of tarstreamref files to reduce the space consumption of the temp folder to a few hundred KB. It seems like there may be some case where the extension isn't being removed after sync.

Did this happen for *every* new file you added, or just a couple of files?

**Comment by VitalNonsense** [comment]
Only to a couple of files, not every file.

**Comment by daPhie79** [comment]
it seems to be related to the length of the filename. we'll look into it

**Comment by daPhie79** [comment]
i've been working on the tar stream recently and found the reason for this bug. it happens if the length of the filename exceeds exactly 99 characters. for now, just don't use such long file names. it will be fixed in next major release.
