### ISSUE TITLE
usb now not working after loading extra games

### ISSUE THREAD

**Issue by jjkjjk69** [TeamShinkansen/Hakchi2-CE#260]
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by jjkjjk69** [comment]
after the update , I;ve loaded a few more extra games , export to usb , but now usb doesn't work on my mini snes

**Comment by DanTheMan827** [comment]
run a disk check on the usb drive
```
chkdsk /F x:
``` 
where x is the drive letter of your usb

you'll need to run that in a command prompt run as administrator

**Comment by jjkjjk69** [comment]
I've able to get my main USB showing games I reformatted it  but how ever,  it's weird for example  Captin America not working on the main  USB,  then put  a different USB in which I usually use to test games  and then the game is working
