### ISSUE TITLE
Ok, now i'm stuck. Bricked?

### ISSUE THREAD

**Issue by xylkz** [TeamShinkansen/Hakchi2-CE#268]
Hi everybody.
This is the message i get  when i'm trying to flash original kernel.
Like it said "This is not good" \(^_^)/
Thks for the help.

Exception
Verify failed :O This is not good.
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.FlashKernel(Tasker tasker, Object syncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\Nicol\Desktop\Hackchi\hakchi2-ce-3.5.3-release (portable mode)
Loading configuration
Starting, version: 3.5.3
Loading libretro core info files
Building libretro core cross index
Loading C:\Users\Nicol\Desktop\Hackchi\hakchi2-ce-3.5.3-release\data\nescarts.xml
Loading C:\Users\Nicol\Desktop\Hackchi\hakchi2-ce-3.5.3-release\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
.......Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-123
Downloading motd file, URL: https://teamshinkansen.github.io/motd.md
Motd timestamp: 2019-04-28T12:19:00.0000000-05:00
Saving selected games
Saving configuration
...............Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
.................Executing task: MembootTasks.WaitForFelOrMembootableShell
Executing task: <>c__DisplayClass69_0.<TaskIf>b__0
Executing task: MembootTasks.WaitForShellCycle
Service added:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 873c80c0 9d883627 6c118000, type=, region=
Attempting to connect to 169.254.13.37...
SSH shell connected
IP Address: 169.254.13.37
Encryption: aes256-ctr
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code 0
hakchi hwid # exit code 0
Detected device unique ID: 0461872a873c80c09d8836276c118000
Success!
Executing task: ShellTasks.ShowSplashScreen
uistop # exit code 0
gunzip -c - > /dev/fb0 # exit code 0
Executing task: <>c__DisplayClass25_0.<ProcessNand>b__0
[ -f /key-file ] # exit code 1
hakchi umount_base # exit code 0
umount /newroot # exit code 1
Shell command "blockdev --getsize64 /dev/nandb" returned exit code 1 blockdev: can't open '/dev/nandb': No such file or directory
   at com.clusterrr.ssh.SshClientWrapper.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.<>c__DisplayClass25_0.<ProcessNand>b__0(Tasker tasker, Object sync)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
ls /user-recovery.flag # exit code 1
..........Executing task: MembootTasks.WaitForFelOrMembootableShell
[ -f /proc/atags ] # exit code 0
Executing task: <>c__DisplayClass69_0.<TaskIf>b__0
uistop # exit code 0
mkdir -p /tmp/kexec/ # exit code 0
cat > "/tmp/kexec/kexec" && chmod +x "/tmp/kexec/kexec" # exit code 0
cat > "/tmp/kexec/detached-fallback" && chmod +x "/tmp/kexec/detached-fallback" # exit code 0
cat > "/tmp/kexec/boot.img" # exit code 0
Executing task: MembootTasks.WaitForShellCycle
SSH shell disconnected
A service was removed:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 873c80c0 9d883627 6c118000, type=, region=
DNS Resolution returned IPs: 169.254.13.37
Attempting to connect to 169.254.13.37...
Service added:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 873c80c0 9d883627 6c118000, type=, region=
SSH shell connected
IP Address: 169.254.13.37
Encryption: aes256-ctr
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code 0
hakchi hwid # exit code 0
Detected device unique ID: 0461872a873c80c09d8836276c118000
Success!
Executing task: ShellTasks.ShowSplashScreen
uistop # exit code 0
gunzip -c - > /dev/fb0 # exit code 0
Executing task: <>c__DisplayClass4_0.<ShellCommand>b__0
touch /user-recovery.flag # exit code 0
Tasker completed all tasks, conclusion: Success
ls /user-recovery.flag # exit code 0
.........Executing task: <>c__DisplayClass25_0.<ProcessNand>b__0
[ -f /key-file ] # exit code 1
hakchi umount_base # exit code 0
umount /newroot # exit code 1
Shell command "blockdev --getsize64 /dev/nandb" returned exit code 1 blockdev: /dev/nandb: Inappropriate ioctl for device
   at com.clusterrr.ssh.SshClientWrapper.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.<>c__DisplayClass25_0.<ProcessNand>b__0(Tasker tasker, Object sync)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
ls /user-recovery.flag # exit code 0
.........Executing task: MembootTasks.GetStockKernel
Executing task: MembootTasks.EraseBackupKernel
sunxi-flash log_write 68 1 </dev/zero # exit code 1
Tasker completed all tasks, conclusion: Error
ls /user-recovery.flag # exit code 0
.........Executing task: <>c__DisplayClass23_0.<HandleHakchi>b__0
echo "cf_install=y" >> /hakchi/config # exit code 0
echo "cf_update=y" >> /hakchi/config # exit code 0
mkdir -p /hakchi/transfer/ # exit code 0
Executing task: <>c__DisplayClass6_0.<TransferBaseHmods>b__0
mkdir -p \/hakchi\/transfer # exit code 0
tar -xvC \/hakchi\/transfer # exit code 0
Tasker completed all tasks, conclusion: Success
ls /user-recovery.flag # exit code 0
..........Executing task: <>c__DisplayClass23_0.<HandleHakchi>b__0
Shell command "hakchi mount_base" returned exit code 255 mount: mounting /dev/nandc on /newroot/var/lib failed: No such file or directory
   at com.clusterrr.ssh.SshClientWrapper.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.<>c__DisplayClass23_0.<HandleHakchi>b__0(Tasker tasker, Object sync)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
ls /user-recovery.flag # exit code 0
.Executing task: MembootTasks.GetStockKernel
hakchi getBackup2 # exit code 1
Executing task: MembootTasks.FlashKernel
cat > /kernel.img # exit code 0
sntool check /kernel.img # exit code 0
sntool kernel /kernel.img # exit code 0
hakchi flashBoot2 /kernel.img # exit code 1
--- End of DEBUGLOG.TXT content ---

**Comment by madmonkey1907** [comment]
It's never bricked...
update to 3.6, then in ce main window press ctrl+f12, then settings -> developer tools -> download latest hakchi
switch to fel mode, kernel -> uninstall, save log
check if it works as stock
fel mode again, kernel -> install, save log
attach logs here

**Comment by xylkz** [comment]
The console doesn't reboot with hackchi 3.6.0.
When i try to uninstall Kernel, i'm stuck on " Please wait while your mini is rebooting" on 3.6 only.

...

WAIT!

Ok I put the langage to english (it was in French) and now reboot's function works.
Everything works, The Snes is save    ¯\_(ツ)_/¯
