### ISSUE TITLE
there is no /hakchi directory message on boot

### ISSUE THREAD

**Issue by jokokucing** [TeamShinkansen/Hakchi2-CE#270]
when booting with usb I get the message "mounted /dev/sda1 () type , but there is no /hakchi directory... are you pulling my leg?' then boots up normally with all games from usb. just annoying.

**Comment by DanTheMan827** [comment]
it's likely due to the partitioning of the drive.

GPT a lot of the time creates a small partition you can't see before the ones you can, hakchi sees this and searches it, doesn't find anything, then searches the next until it finds something or runs out of partitions to search

**Comment by jokokucing** [comment]
I will try to reformat with windows ntfs and see if it goes away

**Comment by DanTheMan827** [comment]
change the partitioning to MBR if it's on GPT, then it should go away

**Comment by jokokucing** [comment]
problem resolved after using the following commands in windows 10. Please mind you this will delete the disk so you will need to export your games again
`diskpart`
`list disk`
`select disk #` (replace # with the number of the USB drive you want to repartition)
`clean`
`create partition primary`
`format fs=NTFS quick`

**Comment by DanTheMan827** [comment]
glad you figured it out

it's mostly just a cosmetic issue, but it does add a tiny bit of time since it's another thing to scan
