### ISSUE TITLE
My SNES Classic isn't being detected

### ISSUE THREAD

**Issue by xxNinTwinDoxx** [TeamShinkansen/Hakchi2-CE#271]
I'm having trouble connecting my SNES mini. 

I downloaded Hackchi 3.6.0 and started the flashing process. I installed the driver, but when I begin to initiate the Reset+ Power commands, Hackchi doesn't detect my SNES and the process bar doesn't begin at all. I tried it on 2 different computers and it's not working. I need help.

**Comment by caspericia** [comment]
Hi. The version of Hakchi ce 3.6.0. was some errors like the conectivity with the computer. The version of Hakchi ce 3.7.0 is early new and they have solved that trouble. Try It.

**Comment by xxNinTwinDoxx** [comment]
I just tried it and it still doesn't work. It's weird, I tried it with my friends SNES classic with v3.6.0 and it worked no problem on the same computer. But mine just won't work, even with 3.7.0. I just mine brand new and my friend had his since launch, could it be my model is too new?

**Comment by bslenul** [comment]
When you hold reset button and power ON, does the light on the console stays OFF?

**Comment by xxNinTwinDoxx** [comment]
No, it stays on. My computer makes the *connected* sound, then disconnects 2 seconds later.

**Comment by bslenul** [comment]
Hmm that's not a good sign... could be a fake unit :/

And when you turn it ON normally (without holding Reset I mean), do you hear the little Windows sound too, and does it appear in Device Manager?

**Comment by xxNinTwinDoxx** [comment]
Yes, it shows up for a second then disconnects a right after. But my friends SNES mini stays connected. It's only mine that disconnects.

**Comment by bslenul** [comment]
Yeah that doesn't sound good :(

Best way to tell is to open up (carefully) the console and compare with legit board (look for "snes classic teardown" on google images or youtube for example). Fake have sometimes red board instead of green, a heatsink, a SD card slot, etc.

**Comment by xxNinTwinDoxx** [comment]
I doubt mine is fake. I got it fresh brand new sealed. But I'll check anyways.
