### ISSUE TITLE
Randomizers

### ISSUE THREAD

**Issue by fshenouda** [TeamShinkansen/Hakchi2-CE#272]
I'd love to see a feature that let you run randomizers on mini SNES classic itself to generate seeds from base roms.  As it stands, you have to run randomizers on PC then transfer the seeded rom to SNES which is not really ideal since you'd have to repeat this to generate another rom on PC again if you want a new seed.

**Comment by KMFDManic** [comment]
@fshenouda This wouldn't be a hakchi issue or true possibility for a feature request.  This is entirely handled by RetroArch and the Cores, and is already possible to run randomizers, as long as you appropriately set them up for use with the aforementioned.  I would probably be able to do a Video Tutorial and minor write-up to help some who have more difficulty getting these up and running.  But, this wouldn't be relative to hakchi, at all.
