### ISSUE TITLE
Incorrect Mame save states

### ISSUE THREAD

**Issue by caspericia** [TeamShinkansen/Hakchi2-CE#274]
Hi, first of all I´m using:
* hakchi2 CE version: 3.7.0
* RetroArch used (filename): KMFD Retroarch 1.8.1. Extreme OZone
* hmod(s) used by the game you are having problems with (filenames): mame2003 Xtreme

All of my intalled Mame 2003 roms are working fine for me. The problem is the save states created within the snes mini...when you load these save games there isn´t sound at all and sometimes the games crashes. Is there any trick to correct this trouble? Thanks a lot.

**Comment by KMFDManic** [comment]
MAME suspend saves never worked, to begin with, due to eeprom issues.  Use FBA Cores for those, and you should be fine:) But, the glitched saves for MAME can certainly have some fun end results!
