### ISSUE TITLE
Pal Games Mini Sega Genesis

### ISSUE THREAD

**Issue by codzon** [TeamShinkansen/Hakchi2-CE#283]
Pal games won't run on US Sega Mini , I couldn't find a feature in Hackchi CE to force them run , please help, thanks #279

**Comment by bslenul** [comment]
When you select a game, there's a "Region" box on the right side of hakchi CE where you can chose to force the game running from Europe/USA/Japan.

**Comment by codzon** [comment]
> When you select a game, there's a "Region" box on the right side of hakchi CE where you can chose to force the game running from Europe/USA/Japan.

It works fine now :) , thanks for your help
