### ISSUE TITLE
SNES mini is not detected with OTG adapter

### ISSUE THREAD

**Issue by forsgear** [TeamShinkansen/Hakchi2-CE#286]
Hello , 

I have not used SNES mini from Hakchi 3.5.1 revision.
Today I updated Hakchi to 3.7.0 version and  now it doesn't detect SNES mini if I use OTG adapter. 
I have two model.  Octopus and another one , they both were working well in past.
Now SNES mini is detected only with direct connection.   
After first direct connection hakchi has updated some scripts or something on Snes Mini. 
as result I cannot run any games those were uploaded on SD card or flash memmory of snes mini

**Comment by DanTheMan827** [comment]
You cannot connect the classic via usb to the computer through an OTG adapter.
