### ISSUE TITLE
Spine art displays incorrectly for European Mega Drive UI

### ISSUE THREAD

**Issue by therourke** [TeamShinkansen/Hakchi2-CE#287]
When the European Mega Drive UI is enabled in HakchiCE, the spine art only shows for one game (in my case Castlevania) on the Mega Drive itself. 

My machine is a Japanese Mega Drive, and the spine art shows fine for Japanese and USA UI versions when enabled in Hakchi.

**Comment by DanTheMan827** [comment]
Which region system do you have?

**Comment by madmonkey1907** [comment]
What is shown in place of other spines?

**Comment by therourke** [comment]
I have a Japanese region Mega Drive Mini. 

Every single spine art shows as Castlevania The New Generation :)

Even if I remove that game then the spines are still that game

As I said, it works fine set in USA or Japanese UI modes

**Comment by madmonkey1907** [comment]
This should be fixed now. update hakchi and try:
* Press Ctrl+F12 in hakchi CE to unlock the Developper menu.
* Settings > Developper tools > Download Latest Hakchi.
* And finally Kernel > Install / Repair.
