### ISSUE TITLE
Cant dump kernel

### ISSUE THREAD

**Issue by tifya** [TeamShinkansen/Hakchi2-CE#29]
I try to dump kernel from a usb setup and cant do it it say error usb file alrdy exist !
I did try to reset unistall and doesnt work.
I did try to flash custom wasnt working
Seems to work after all those try with custom flash now

**Comment by daPhie79** [comment]
we would need more information to help you out. at first glance this looks like a tech support request. maybe you'd get more help on reddit /r/miniSNESmods/

**Comment by tifya** [comment]
I been able to dump it finnaly after a couple of try and i about to wait a new update cuz i cant get able to put every roms on usb stick its load Nothing only bypass de usb stick when i put it with too much roms.
Maybe ill try with a better usb stick 3.0 and get a chance i did try a Msd card on a usb reader card and its wasnt able to load anything probly too much adapter to pass true before the console.


Provenance : Courrier pour Windows 10

De : princess_daphie
Envoyé le :20 février 2018 13:32
À : TeamShinkansen/hakchi2
Cc : tifya; Author
Objet :Re: [TeamShinkansen/hakchi2] Cant dump kernel (#29)

we would need more information to help you out. at first glance this looks like a tech support request. maybe you'd get more help on reddit /r/miniSNESmods/

**Comment by daPhie79** [comment]
it is important to keep the number of games per page/folder to around 30. maybe that's your issue?

**Comment by tifya** [comment]
Yeah i did custom for folder split equaly to get at least 30 per page and i even try to split in two folder due to a 20 folder per folder to less lag with too much folder but seems to isnt working too i start to think the usb key isnt able to load fast enough to get it load in the ram maybe i got one too cheap is a 3.0 usb would work i got some vid on net that was saying usb 3.0 isnt working would like to know before try.


Provenance : Courrier pour Windows 10

De : princess_daphie
Envoyé le :20 février 2018 15:12
À : TeamShinkansen/hakchi2
Cc : tifya; Author
Objet :Re: [TeamShinkansen/hakchi2] Cant dump kernel (#29)

it is important to keep the number of games per page/folder to around 30. maybe that's your issue?

**Comment by daPhie79** [comment]
hope you got this fixed!
