### ISSUE TITLE
Since 3.7.0 Upgrade Options Menu v1.3 by CompCom Stops Working

### ISSUE THREAD

**Issue by impeeza** [TeamShinkansen/Hakchi2-CE#291]
Hi, I just Upgraded to Hakchi 2 CE 3.7.0 but when I press L+R the system appears to freeze, the funny part is Hakchi still show the mini as connected and even I can connect using telnet, ftp and sync games.

Download everything again from net, restore to factory settings and install all but no luck

Actually I am using an internally soldered 4 GB SD card.

1. Download Options Menu v1.3.0 HMOD
2. Copy it to UserMod folder
3. Install Options Menu v1.3.0 and WPA Supplicant HMODs
4. Press and hold L + R

**Expected behavior**  
The Options Menu should appears and allow to change themes, manage wifi network, etc.

But using Hakchi 3.7.0 you only get the main menu frozen.

Resetting to Factory and installing Hakchi 3.5.3 all works fine.

**Comment by bslenul** [comment]
https://cdn.discordapp.com/attachments/499532327869743125/637695462123634718/options_deluxe_v1_3_2.hmod

That one updated by CompCom should work partially at least, I know the "Uninstall hmod" menu make the system freeze.

I hope someone will try to fix it completely in the future...

**Comment by impeeza** [comment]
Thanks, I will be looking for the new release.

**Comment by impeeza** [comment]
Capcom just release the version 1.3.3, and yes version 1.3.2 frozen using the Uninstall Module option. the new version 1.3.3 works fine

**Comment by DanTheMan827** [comment]
https://github.com/CompCom/OptionsMenu/releases/download/1.3.3/options_deluxe_v1_3_3.hmod
