### ISSUE TITLE
http request returned status 522

### ISSUE THREAD

**Issue by alejandrol29** [TeamShinkansen/Hakchi2-CE#292]
**Describe the bug**  
After installing the kernel successfully on my NES classic mini, when I try to enter to the menu Modules > KMFD’s Mod Hub I'm getting an error message

**To Reproduce**  
1. Connect the NES classic mini
2. Try to enter Modules > KMFD’s Mod Hub

**Expected behavior**  
It should open a new window with more options

**Screenshots**  
Error:
![image](https://user-images.githubusercontent.com/31321710/74203978-2cbe8700-4c50-11ea-92d3-7d255ea0402e.png)

Expected
![image](https://user-images.githubusercontent.com/31321710/74203963-216b5b80-4c50-11ea-8f29-35589ad25a5a.png)

**Additional context**  
I'm following this tutorial: https://nesclassicmods.com/how-to-play-snes-games-on-the-nes-classic-mini/
I want to add SNES games to my NES classic mini edition.

**Comment by DanTheMan827** [comment]
The website is down at the moment

**Comment by alejandrol29** [comment]
Thanks for answering so fast. Is there any website that I can check to realize when it's up again?
