### ISSUE TITLE
Non US Games Internal Saves Not Working...

### ISSUE THREAD

**Issue by scoobs851** [TeamShinkansen/Hakchi2-CE#297]
Mega Drive Mini problem this one.

US games such as Sonic 3 & Knuckles save just fine as the cartridge would have done however non US games dont. This appears but is not limited to:

Micro Machines 2, 96 and Military - Player progress and names not saved. MM96 Tracks on the Track Editor not saved. This works fine on both the SNES and NES. Details are not lost until game is completely reset.

Sensible Soccer - Team Name Changes lost mid game. For example rename Norwich - Bournemouth and they will revert back after their first league game. Does not happen on NES and SNES with same Rom.

Fifa 98 - Same as Micro Machines does not hold a save

Premier Manager - Again does not hold a save. Due to being a data intensive game it goes a little strange but still playable despite this

**Comment by KMFDManic** [comment]
@scoobs851 These would generally be EEPROM relative.  The best way to handle this is to fall back to "RetroArch" saves, where applicable, particularly on the MD Mini.
