### ISSUE TITLE
Problems using External Storage on SNES Classic 

### ISSUE THREAD

**Issue by henriquewicz** [TeamShinkansen/Hakchi2-CE#298]
When i use a OTG cable with a USB storage on my snes classic, i have problems like "sometimes after the hakchi logo screen the system halt". If i try again, works. Without the usb its all ok. Tjis using the original cable controller.

I'm using the original powersupply and usb cable.

If i'm using the 8bitdo receptor, the system halts ALWAYS. I think this can be something related to energy. As the power cord and supply as the originals, maybe is the otg cable?

Has anyone problems like this?

**Comment by impeeza** [comment]
Hi, I did have similar problem too many times, and the solution was using a different USB cable and power source (brick) and all get fixed like magic

**Comment by henriquewicz** [comment]
Did you change the otg? Or change The power supply + USB cable?

Os is The second option (supply + USB of suplly) Can you give a tip of USB
cable? The original Nintendo isnt a good cable? And the power supply really
can be better. But i try another wit more amperage and not solves here. But
o disnt change the USB cable.

Thanks

Em seg, 24 de fev de 2020 22:30, impeeza <notifications@github.com>
escreveu:

**Comment by impeeza** [comment]
Hi, sorry for confusing. When i have trouble wasn't using original Nintendo power brick. And the OTG cable was faulty.  The working setup was: original Nintendo power brick and cable and a OTG+Power cable from my Raspberry.  Later replaced the OTG cable by a high quality one and still working fine.

**Comment by henriquewicz** [comment]
I'm using the original Nintendo power and cable. And the OTG i was
searching in the net for some tips and i saw this tip: AuviPal 2-in-1 Micro
USB to USB Adapter (OTG Cable + Power Cable) - 2 Pack.

So I've bought in Amazon (
https://www.amazon.com/gp/product/B07FY9Z9GD/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1
).

But the 3 units in package just one works... And not all the times. So I've
talked with Amazon and they send another package to me. 3 units and just
one works. The first one stop works too. Conclusion. I have 6 units, just
one works fine. I think this crap will stops too coming... I need a best otg.
Can you say what is yours?

Thanks for your help
Henry


Em ter., 25 de fev. de 2020 às 11:00, impeeza <notifications@github.com>
escreveu:

**Comment by impeeza** [comment]
Hi the first OTG I did use was the one on the Raspberry original Kit, the second one was made locally by a team of hobbyist, (I live on Colombia) The OTG-cable is made from high quality USB cable and terminals, hand soldered and sealed using shrink tube, the schematics used are:
![image](https://user-images.githubusercontent.com/41979604/75256443-790dd900-57b1-11ea-8942-4af2befc7fcc.png)

**Comment by henriquewicz** [comment]
Thanks man!

Em ter., 25 de fev. de 2020 às 11:31, impeeza <notifications@github.com>
escreveu:
