### ISSUE TITLE
RetroArch is not working?

### ISSUE THREAD

**Issue by otorcatf** [TeamShinkansen/Hakchi2-CE#3]
Hello, first of all excellent fork of hakchi2, really cool new features which make even more comfortable using hakchi2

I can't get RetroArch working with your version of hakchi2, the steps I'm following are:

1. Uninstall and flahs the original kernel
2. Flash custom kernel
3. Install RetroArch module (I tried with KMFDManic and ClusterM versions of RetroArch)

When I execute any NES game I only get a black screen and I must restart the console.

Any advice to get this working?

Thanks

**Comment by daPhie79** [comment]
you're sure you're using km's last version?
the file name in his core set: **_km_retroarch_170_1_29_18.hmod**

i tested it personally yesterday because i was trying to see if i could run other versions and that's the one that works. 1.6.7 for now is a no go. i know km's working on this!

**Comment by otorcatf** [comment]
Yes that's the module I'm using, I tried with
_km_retroarch_167_1_29_18.hmod but didn't work either.

When I reflash the custom kernel with 2.21f and install the ClusterM
RetroArch version the NES games works fine again.
.

**Comment by gingerbeardman** [comment]
make sure you download KM pack again, as there was a problem with retroarch some days ago. filename has not changed for that retroarch core but the contents have been updated.

also, what is your command line for the NES game?

**Comment by KMFDManic** [comment]
@otorcatf /bin/fceumm OR /bin/nestopia

**Comment by daPhie79** [comment]
have you tried /bin/nes maybe?

**Comment by otorcatf** [comment]
Ok after using the latest version of KM cores (2-1-18) and change the command line to /bin/fceumm the NES games are working (Also works with /bin/nestopia)

Looks like the specific reason of my problem was the command line, because if I change it to /bin/nes I get the black screen again.

Thanks for your help and excellent work @daPhie79 @gingerbeardman @KMFDManic 

If you need help with any developing, testing or translate (To spanish) thing, you can count on me, just let me know.

**Comment by daPhie79** [comment]
happy you've got it running!
