### ISSUE TITLE
V3.7.0 - Install - Reboot not executed

### ISSUE THREAD

**Issue by Christophedlr** [TeamShinkansen/Hakchi2-CE#300]
Hello,

My European SNES Mini is flashing with the last hakchi2 ClusterM version. I would flash with the Hakchi2-CE 3.7.0 (last version of TeamShinkansen Hakchi2 version) for install new games.

After connected my SNES Mini, Hakchi2 inform me the firmware requiert upgrade. OK, I valid the action, but after display message: "wait for restarting your mini..." (excuse me, I used Hakchi2 in French language ^^), in console debug the command : ShellTasks.Reboot is not executed.

After the progressbar is end, the program display message: "Your device is talinkg a long time to reboot.", but I test stop the Comodo Firewall and Avira Antivir (no VPN used) and the problem persist.

After click the Tools > Reboot, the console debug display: "Executing task: ShellTasks.Reboot".
Therefore, for reboot SNES Mini, the program must executed the task, but during installation/repair, reintilisation or uninstall (or other commands in the Kernel menu), not executed the task.

Impossible for me upgrade firmware and install other games.

**Comment by Christophedlr** [comment]
I just tested in version 3.5.3 and once I have HAKCHI which appeared on my TV, Comodo Firewall to detect a new network, which I authorized. The installation then went very well.

**Comment by DanTheMan827** [comment]
you cannot install the ClusterM version and use the Team Shinkansen version for synchronizing games.

you will need to install and use the Team Shinkansen version for that

**Comment by Christophedlr** [comment]
@DanTheMan827 In use Team Shinkansen version 3.7.0 : install does not work, install work with 3.5.3 version.

**Comment by KMFDManic** [comment]
@Christophedlr As of currently, you must go back to stock kernel before updating to the latest hakchis.  If you have any firewall, virus protection, vpn, wifi issues, that can conflict with proper updating to newest hakchi.  You can hold down left shift, while uninstalling kernel, select the appropriate kernel to go back to stock on, and then install/repair kernel to get onto newest hakchi.  Hope that explains things!
