### ISSUE TITLE
GB/GBC/GBA Games

### ISSUE THREAD

**Issue by Christophedlr** [TeamShinkansen/Hakchi2-CE#301]
Hello,

I have flash SNES Mini with Hakchi2-CE 3.7.0. After install GB/GBC & GBA emulator, It's not possible run games: SNES Mini return to menu or block in black screen. I've test gambatte and gearboy for GB/GBC emulator ; mgba and vba-next for GBA emulator.

I just saw the same thing with the SNES emulator for games not passing with clover-canoe-shvc-wr emulator.

**Comment by KMFDManic** [comment]
@Christophedlr this wouldn't necessarily be a bug.  You'd need to ensure you have RetroArch installed in order for these to properly load, for starters.  Then, the appropriate cores selected.  Install RetroArch, and retest, and show me command lines on any games that are not working for you.

**Comment by Christophedlr** [comment]
I have reinstall RetroArch 184 Xtreme RGUI Themed and problem is resolved. Thanks ^^ ; I didn't think reinstall RetroArch ;).
