### ISSUE TITLE
Updated NES mini to 3.7 and now all games EXCEPT NES give me a C7 error

### ISSUE THREAD

**Issue by kwise1** [TeamShinkansen/Hakchi2-CE#306]
Any ideas?  I have been scouring the Internet trying to find a solution for a couple days.  I have reinstalled, fixed, selected emulation cores.  Not sure what to do.  Was working great until update. Any help would be great.

**Comment by KMFDManic** [comment]
Kernel reset, reinstall latest retroarch and cores and bios, then specify appropriate cores. Try some of the modules, kmfd mod hub, games.

**Comment by kwise1** [comment]
Thanks for the quick reply. I are talking the KMFD Retroarch and KMFD BIOS on the Mod Hub?  If so, which do you recommend?  Thanks for helping.  Was going to catch up on gaming during the quarantine here.

**Comment by kwise1** [comment]
Reinstalled Retroarch 1.7.  Games now seem to open, but kick right back out to the home screen.  Kind of like they are "skipping."  Getting closer!

**Comment by KMFDManic** [comment]
Download an NES game from Mod Hub and test that, for now.

**Comment by DanTheMan827** [comment]
Since there hasn't been any activity on this issue, I'm closing it.
