### ISSUE TITLE
Snes mini soft brick

### ISSUE THREAD

**Issue by MicheleMaccagnani** [TeamShinkansen/Hakchi2-CE#309]
I have a problem with my snes mini:
I was upload a new rom, when the cable popped off and the snes mini turned off.
Now the console is still working, BUT, a lot of rom doesen't show up anymore on the menu, a lot of games doesen't work anymore, and the console isn't recognized anymore from any version of hackchi2, so i cannot reset or reupload the original kernel or new roms.
What can i do now?

**Comment by DanTheMan827** [comment]
Reset the kernel, it will have you enter FEL mode like you did when you initially hacked it

**Comment by MicheleMaccagnani** [comment]
I cannot enter in FEL mode anymore.
Even if i try, hackchi2 continue to trying finding the console without results.

**Comment by impeeza** [comment]
Please do not open a bug ticket for support. To get support please use the correct channels, discord or wikis

**Comment by MicheleMaccagnani** [comment]
Ok, i will try discord then, thanks.
