### ISSUE TITLE
nes mini all games quit instantly on launch

### ISSUE THREAD

**Issue by BlasterRaz** [TeamShinkansen/Hakchi2-CE#310]
when trying to use anything other than stock emulator, my hackchi is also now displaying a blank list when I try to change default emulator for all roms this worked fine until just now

I'm trying to set all nes roms to open using one of the retroarch emulators because I have a few games the stock emulator won't play, I'm using Hakchi CE 3.7.0 and retroarch 1.1.d (i also tried 1.1c same issue)

**Comment by DanTheMan827** [comment]
Sounds like you're using an incompatible retroarch.

Be sure to get both the cores and retroarch itself from KMFD's Mod Hub accessible from the Modules menu in Hakchi2 CE

**Comment by BlasterRaz** [comment]
I have done that now after completely wiping the whole thing and starting again. both issues still persist, and I can't even change the emulator back to stock because the select emulation core box is still completely blank

**Comment by BlasterRaz** [comment]
even if i completely remove retroarch and all cores it still quits instantly on launch for all games
