### ISSUE TITLE
Unable to connect to my SNES (in normal and FEL mode)

### ISSUE THREAD

**Issue by timothyparez** [TeamShinkansen/Hakchi2-CE#313]
**Describe the bug**  
If you live or work in an area where google.com is blocked then basically  
every action you execute in this app will fail.

**To Reproduce**  
1. Go to any action, for example update the kernel
2. Click on 'yes' when asked to update the kernel
3. The software then automatically tries to download art for the games from google.com
4. This results in a crash (title: cannot connect) but details show it's the web requests to google that failed.

**Expected behavior**  
- Don't crash if Google is unreachable

**Possible solutions (features)**
- If possible do not rely on Google alone
- Do not try to download game art every time
- Allow download failure
- Add a ability to disable automatic downloads

**Comment by timothyparez** [comment]
I will take a look at this issue myself as well

**Comment by DanTheMan827** [comment]
Could you please download the debug version and provide the error message along with the trace?

**Comment by timothyparez** [comment]
[debuglog.txt](https://github.com/TeamShinkansen/Hakchi2-CE/files/4438431/debuglog.txt)
So here is the funny part.  
When using the debug version I get no errors related to Google because it does not seem to 
try and connect to Google.

I still get the device connection issue though (debuglog attached, no temp folder found and  
my connection to Github is too unstable to upload the entire directory.

Would you like me to close this issue and create 2 separate issues instead?
One for my connection issue and the other for Google dependencies?

Also, are there any instructions as to how to build this project on Windows 10 with Visual Studio 2019? If I could get it to build I could add support for Bing myself but right now when I try to rebuild the solution is just sits there and waits forever.

**Comment by DanTheMan827** [comment]
What were you doing in that log?

It looks like you were trying to do something that was making it wait for FEL or a shell connection?

As for building the project, you need git.exe in the path, then I think it should work.

There are some files that the build scripts download as needed, is it possible that it could be hanging on downloading one of these?

Also, you have an old version, try 3.8.0, I wasn't able to recreate your issue exactly, but I did put in some checks.

**Comment by timothyparez** [comment]
So I start the application and then I connect the SNES.
At that point it tells me the kernel is outdated and asks me if I want to update it.
Then the error occurs.

As for the build: If it needs to download files then it is indeed quite likely that
it hangs there. So many internet resources are blocked here.

Will try to download that latest version and let you know what happens.

**Comment by timothyparez** [comment]
[debuglog.txt](https://github.com/TeamShinkansen/Hakchi2-CE/files/4454275/debuglog.txt)  
This is the debuglog with 3.8.0-debug.

**Comment by DanTheMan827** [comment]
that error isn't due to not being able to download something, that's due to a communication error with the system that isn't handled in a user-friendly way.

Turn the system off, then turn it on while holding the reset button to enter fel mode, then try the kernel update.

If that still doesn't work, try a different cable and/or usb port on your computer.

**Comment by timothyparez** [comment]
Yes, the google issue is unrelated. That is why I think I should create a separate issue for that
once I manage to update the kernel. 

I have tried a few different cables and USB ports. This is a fresh Windows 10 install on a laptop.
(I do not have any other Windows systems, I basically run Ubuntu everywhere).
I installed the driver that came with Hackchi2.

What else could I try?

**Comment by DanTheMan827** [comment]
Well, part of your problem is that you're running an ancient version of hakchi on the system, my suggestion would be to run the uninstall procedure with the system powered off completely, then turn it on while holding reset to enter fel mode.

What's happening in the log appears to be that the system is on the waiting screen, it sees the old version of hakchi operating in clovershell mode, and it thinks that's fel mode and tries sending incorrect data and just getting confused completely.

**Comment by timothyparez** [comment]
Okdoing a full uninstall seemed to do the trick. I can connect to the console now.
Now it crashes while uploading games, but I'll play around with it first and open a new issue if need be and for the Google issue as well.

Thnx for the help.
