### ISSUE TITLE
updating/installing cores after using External Retroarch do not work

### ISSUE THREAD

**Issue by impeeza** [TeamShinkansen/Hakchi2-CE#315]
**Describe the bug**  

Hi after I install External Retroarch Hakchi module, if I add new cores or update existing ones. the changes are saved on REAL /etc/libreto but not replicated to hakchi/libreto so the efective running cores do not include the just installed ones.

I have to manually copy the content of \etc\libretro inside of the .hmod file to the running NES Classic Mini by FTP and manually restart Retroach in order to get it Working.

There is a way of the overmount works in the installation process of new cores so I haven't to copy manually the files?

**Expected behavior**  
Installing new cores or updating new cores should work fine if you have or not have External Retroarch module installed.

thanks a lot

regards from Colombia

**Comment by KMFDManic** [comment]
Not necessarily a bug.  If you have disk drive corruption, the transfer won't properly work. I wouldnt really recommend using external retroarch because if u do get improper shutdowns, u may need to reinstall retroarch and cores, etc, as well as do a disk check.  Cores are very small, 75 percent smaller than they used to be. They run far more optimally from NAND.

**Comment by impeeza** [comment]
Hi. I have no disk corruption and the transfers still not working.  If the external retroarch mod isn't recommend, then should be removed from the official repository

Thanks a lot

**Comment by KMFDManic** [comment]
If the transfer isnt working, you still have a conflict of some kind, as it still works. I maintain it for those who really do want to use it.  But, it is still not recommended for most users.  Another thing u can do to test is create hakchi/transfer and copy any hmod into there, and you should get a double splash screen to signify it installed on boot up.  If u do not see double splash, that is a surefire sign of corruption.

**Comment by DanTheMan827** [comment]
The external retroarch mod was made with the intention of using the transfer folder on USB to install additional cores, the USB has to be inserted when installing the cores.
