### ISSUE TITLE
Game running under menu

### ISSUE THREAD

**Issue by micker** [TeamShinkansen/Hakchi2-CE#325]
Hello i dont understand why when i load a game i am return to menu and i listen music and game in background....
Snes game and mega drive game too
Thanks for ant help

**Comment by micker** [comment]
Nobody ?

**Comment by impeeza** [comment]
Hi, please use Discord or Wiki to get Support, first you need to ensure you have the correct cores need and assigned to the game.

**Comment by micker** [comment]
Sorry little newbe on discord can you share an invite URL ?
Regards

**Comment by impeeza** [comment]
You can Go to official site:  
https://hakchi.net/ and at the very bottom of page on "Where can I find help?" section you can get the official Links:


    Rockin' The Classics Discord Server (https://discord.gg/C9EDFyg)
    /r/hakchi on Reddit (https://reddit.com/r/hakchi/)


![image](https://user-images.githubusercontent.com/41979604/79591338-fcef8d80-809d-11ea-9f54-f025d9bb08b3.png)

**Comment by micker** [comment]
tha,nks

**Comment by DanTheMan827** [comment]
For clarification, ModMyClassic is not the official website or discord server for hakchi or Team Shinkansen

**Comment by impeeza** [comment]
Ok, sorry for the confusion, but the site https://hakchi.net/ is the oficial point of information?
