### ISSUE TITLE
Hakchi 3.8.0 Genesis games issues (Genesis mini, core emulator)

### ISSUE THREAD

**Issue by Studyingsoul** [TeamShinkansen/Hakchi2-CE#327]
Hello !

Some problems with the original emulator of Genesis Mini with Hakchi 3.8.0 :

Not working : 
- 3 Ninjas Kick Back (U) [!]
- 3 Ninjas Kick Back (USA)
- Mamono Hunter Yohko - Makai Kara no Tenkosei (J) [p1][!]
- Mamono Hunter Yohko - Makai Kara no Tenkosei (J) [t2]
- Puggsy (U) [!]
- Rockman X3 (Unl) [f1]
- Samurai Shodown (U) [!]
- Super Bubble Bobble (Unl)
- Super Skidmarks (E) [h1]
- Virtua Racing (U)

Unplayable and glitches : 
- General Chaos (UEJ) [!]

Glitches on game : 
- Burning Force (U) [!]
- Dashin' Desperadoes (U) [!] (many glitches)
- Panorama Cotton (J) [h1C]
- Turrican (U) [b1]

Sound problems (not sound) : 
- Midnight Resistance (U) [!]
- Teenage Mutant Ninja Turtles - Return of the Shredder (J)
- Teenage Mutant Ninja Turtles - The Hyperstone Heist (U) [!]
- Truxton (JU) [!]
- Verytex (Japan)

Thank you for all what you did and do !

**Comment by HardDie** [comment]
I have a problem with Rock 'n' Roll Racing in 2 player mode.
In a race, only the first player screen is displayed.
I checked Linux Sega emulator dgen, it has the same problem.

Just in case:
```
╰─$ dgen -v                                                                                                                                                                                                   2 ↵
DGen/SDL version 1.33
```

**Comment by KMFDManic** [comment]
@HardDie @Studyingsoul As of newest hakchi 3.9.1, a few of these games have been fixed up.  But, unfortunately, for now, any of the non-fixed ones, you will need to run with RetroArch and a Core, such as Genesis Plus GX or PicoDrive:)
