### ISSUE TITLE
Hackchi CE 3.8.0 not install Kernel

### ISSUE THREAD

**Issue by TheTr25** [TeamShinkansen/Hakchi2-CE#328]
On a last stage of flashing "Waiting for reboot", snes not reboots.
After manual reboot, console stuck on Hackchi screen.
And i can't flash to original state, same problem.
Using Hackshi 2 from Cluster, i get my snes to original state, and easy install hackchi 2.
Hackchi CE asking to update Hackshi on SNES and stuck on the same bug.

**To Reproduce**  
1. Get non hacked SNES
2. Go to Kernel - Install\ repair 
2. Unplug USB, switch on position, holding Reset connect SNES mini 
3. Waiting till "Waiting for mini reboot"
4. .......
5. Have a text in software about firewall and Hackchi screen on console

**Comment by DanTheMan827** [comment]
If hakchi2 ce is asking for an update, that means you didn't actually uninstall hakchi2 before trying to install hakchi2 ce.

Kernels can easily get mixed up in hakchi2 and what you think is the original may actually be an already modded kernel or the wrong kernel for your system entirely if you've hacked multiple systems.

**Comment by TheTr25** [comment]
May be my bad english caused misunderstending :) I try 2 methods 1) clean SNES hack by CE - no luck 2) claster's hackchi - update by CE - no luck  
I going to record a video later ;)

**Comment by TheTr25** [comment]
https://youtu.be/f3ITEb6KgyE
5 min live action horror =)

**Comment by Matvey81** [comment]
Я не смог запустить файлы ATARI c расширением .ATR, .XEX, A52/ для ATARI 5200

**Comment by Matvey81** [comment]
Может быть это невозможно?

**Comment by ArieKindicator** [comment]
I have a similar/the same issue "Waiting for the device to boot..." but this has nothing to do with a mix up of different Hakchi2 flavours CE vs non-CE. See my message https://github.com/TeamShinkansen/Hakchi2-CE/issues/308
