### ISSUE TITLE
Interface idea for Most played, Most recently played, and Favorited folder

### ISSUE THREAD

**Issue by JON99999** [TeamShinkansen/Hakchi2-CE#330]
**Is your feature request related to a problem? Please describe.**
As a user with a lot of files, I would like to be able to have folders for Most Played, Most Recently Played, and a Favorited Folder.  I would like to be able to toggle adding/removing a game in the favorited folder by pressing "Select-Up" while in the game.

**Describe the solution you'd like**
Concept for folders and interface.
1. 3 Top level folders on the main default folder interface.  
- Most Played
- Most Recently Played
- Favorites
--These would be enabled/disabled by a check box under the Structure menu or similar to the "add home" check option Under Structure>>Custom.
--There would be 30 titles per folder.  (Or possibly the number selected in the "maximum games per page/folder" default.)
--These folders would essentially be empty placeholders added by the Structure code.

**Solution Concept Preface**
I don't know linux or the guts of how these games are launched.  I have written the information below with the assumption 
A. That the mini can "Save Playcount".
A.i By editing .desktop files.
A.ii By editing some other .xml or list.
And 
B. That the mini can "Edit Locations".
B.i By writing/deleting/copying/renaming the entire directory of each game's files OR 
B.ii OR By writing/editing .desktop tags with /var/ to hard coded locations 
B.iii. OR that you can write a symlink or alias for each of the files in the folder to point to the original location.
C. That the mini can "Review/Maintain the List" of 30 items.
C.i. By maintaining a text or xml file.
C.ii By parsing all of the .desktop files in each subfolder to create a list/array of current items on the fly.
--------------------------
**Solution concept**
-----------------
2. Most Played - "30 most played titles"
- Save "PlayCount" flag as Playcount+1 on each game launch.  
- "Review/Maintain the list" of the 30 most played titles, in descending order.
- "Edit location" of game each time "Play Count" of launched game changes order of the list.
-- "Edit location" of displaced game.  
--- If Launched game is new to list, delete reference to displaced game.  (Game with MinPlaycount.)
--- If Launched game is on list, and "Playcount + 1" changes position, then "Swap Location" of displaced game.)
-- Bonus Points - Append the number of plays to the title as displayed in "Most Played" folder.   <title> (<PlayCount>)
--------------
3. Most Recently Played - "30 most recently played titles." 
Use same code as 2. Most Played. Except...
-- Only, instead of using the actual "PlayCount", "Review/Maintain the List" of "Top 30 most recently played", and find the max PlayCount in the list.  +1 that and write it as your "MostRecentPlayCount".  (For first run, you'd find no items and use 0.)  
---That would also provide a neat tracker for the number of times playing games on the system. Bonus points - You could add a dummy game and icon which is "number of system plays" where the title of the dummy icon is rewritten each time a game is launched.  "You've launched <MaxMostRecentPlayCount> times."
-----------------
4. Favorites - 30 most recently favorited titles.
- While playing game, add/remove favorite by pressing "select-up".
-  If the running game is not found when you "Review the List" of favorites, "Select-up" would run the same code as 3. Most Recently Played... only, with the Favorites folder as the location.
- If the running game is on "The List", it would be removed via the "displaced" subroutine from 2.
--BonusPoints - A small text overlay indicates if Favorite was added or removed.

**Additional context**
I wish I knew Linux coding !  But, dammit Jim, I'm a business analyst, not a coder.  If this was, *cough* *cough* VBA, I'd write it myself and submit! Thanks again for all you do on Hakchi!

**Comment by DanTheMan827** [comment]
This is possible at least for the NES and SNES, but it would require a custom tool that ran on the system and scanned the json file containing the play count information and created a virtual page (or pages) by creating a temporary filesystem and linking the actual games to it.

I toyed with this idea but found that the classic also likes to reset the file containing this information every so often.

**Comment by KMFDManic** [comment]
@JON99999 All 3 of these things are possible as long as you run games with RetroArch and the appropriate Cores.  Once in RetroArch Settings, you can see favorites, history, can access total amount of time played on any given game, etc.  Being that RetroArch already has this quite handled, it wouldn't be as high a priority to have it set up for the default emulator.  But, if someone puts together a script or a tool that doesn't conflict with hakchi in a bad way, we could certainly try to adapt things for the "default" emulator:)
