### ISSUE TITLE
 Я не смог запустить файлы ATARI 

### ISSUE THREAD

**Issue by Matvey81** [TeamShinkansen/Hakchi2-CE#331]
Я не смог запустить файлы ATARI c расширением .АТР, .XEX, A52/ для ATARI 5200. Может кто-нибудь пробовал и поможет с советом

**Comment by JON99999** [comment]
Did you install the 5200.rom BIOS?

Prerequisite BIOS: system/5200.rom, ATARIBAS.ROM, ATARIOSA.ROM, ATARIOSB.ROM, ATARIXL.ROM

Вы установили 5200.rom BIOS?

Необходимый BIOS: system / 5200.rom, ATARIBAS.ROM, ATARIOSA.ROM, ATARIOSB.ROM, ATARIXL.ROM

**Comment by Matvey81** [comment]
Я не знаю как это сделать. Подскажите пожалуйста!



> Это вы установили 5200.rom BIOS?
> 
> Обязательное условие BIOS: system / 5200.ром, АТАРИБАС.РОМ, АТАРИОЗА.РОМ, АТАРИОСБ.ROM, ATARIXL.ЦЫГАН
> 
> Вы установили 5200.rom BIOS?
> 
> Необходимый BIOS: system / 5200.ром, АТАРИБАС.РОМ, АТАРИОЗА.РОМ, АТАРИОСБ.ROM, ATARIXL.ЦЫГАН

Я не знаю как это сделать! Подскажите пожалуйста!

**Comment by Matvey81** [comment]
Я поставил  BIOS  - RA BIOS Master Module в Hakchi. Проблема не решилась

**Comment by KMFDManic** [comment]
@Matvey81 This wouldn't be a hakchi issue.  This would be relative to you simply needing to ensure you have BIOS installed.  Install latest RetroArch, copy the 5200.rom, at a minimum to Master BIOS Module/system/5200.rom (navigate to that folder).  Then, with the Core installed, right click, select emulation Core, and run games with .a52 extension.  Being that this is a very commonly missed thing, "bios" not being properly installed, and/or improper "roms", this would not be relative to hakchi, itself.  This is something you merely need to double check, on your end.  Open up the Core, with NO games running, RetroArch Settings, Information, Core Information, Bios Present Or Missing.  Feel free to bump this issue if you still need help!
