### ISSUE TITLE
constant errors when attempting to hack a nes/snes mini...

### ISSUE THREAD

**Issue by matt91080** [TeamShinkansen/Hakchi2-CE#339]
So, I've done many of these in the past with hakchi version 2.31 with zero issues.  I get on today to attempt to do the same thing i've done countless times before and all I get are error messages.  First one is Critical Error: could not find part of the path... that pops up before hakchi starts.  Then when I go to flash custom kernal, I get Unhandled exception has occurred in your application.
Then if I try to dump kernal I get a .bin not found error. Everything worked PERFECTLY before, what the hell happened to hakchi!!?  After deleting hakchi from my computer, I decided to follow the link to the updated ce version.  It gives me the same errors and won't allow me to do anything.  VERY VERY ANNOYING !!   please help me figure out the hakchi program, and why this Junk CE version exists if all it does is cause problems.

**Comment by DanTheMan827** [comment]
extract a fresh copy from the zip file and copy your data over from the old one, it sounds like your install is damaged.

**Comment by matt91080** [comment]
ok, looks like that worked so far.  At least I didn't get a bunch of errors this time.  Thanks
