### ISSUE TITLE
"Unhandled exception has occurred in your application" when opening app

### ISSUE THREAD

**Issue by AJDon78** [TeamShinkansen/Hakchi2-CE#34]
First off, great new Hakchi from you guys. Thanks for working so hard for all of us to enjoy!

Now, as to the actual use of the software,  I upgraded my NESC running Hakchi 2.21f to CE ve 1.1.0. I'm seeing a few issues, so will open an thread for each one. Hope that's the correct way of dealing with it. :)

The first thing, is that every time I open the CE application, I get an error message "Unhandled exception has occurred in your application". 

The full message is:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NotSupportedException: The requested security protocol is not supported.
>    at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
>    at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
>    at com.clusterrr.hakchi_gui.MainForm.MainForm_Shown(Object sender, EventArgs e) in C:\hakchi2\MainForm.cs:line 1925
>    at System.Windows.Forms.Form.OnShown(EventArgs e)
>    at System.Windows.Forms.Form.CallShownEvent()
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.runTryCode(Object userData)
>    at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
> ----------------------------------------
> hakchi
>     Assembly Version: 3.1.0.0
>     Win32 Version: 3.1.0.0
>     CodeBase: file:///F:/Google%20Drive/Hakchi%20CE%20Edition/hakchi.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8686 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.5495 (Win7SP1GDR.050727-5400)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.5494 (Win7SP1GDR.050727-5400)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 3.5.0.0
>     Win32 Version: 3.5.30729.5420 built by: Win7SP1
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> AutoUpdater.NET
>     Assembly Version: 1.4.6.0
>     Win32 Version: 3.1.0.0
>     CodeBase: file:///F:/Google%20Drive/Hakchi%20CE%20Edition/hakchi.exe
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 

I see that someone else is getting the same message, when deleting games, but i wasn't sure if this would be considered the same error or something different, so opened this issue thread just in case.

**Comment by daPhie79** [comment]
same as #32 indeed. what is you windows version?

**Comment by AJDon78** [comment]
Good to know. :) I'm running Windows 7.

**Comment by daPhie79** [comment]
have you tried the recommended fix in the FAQ?

Q: On app start, I receive an error about System.NotSupportedException: The requested security protocol is not supported.
A: You are most likely on an older version of .NET, or a version of Windows older than Windows 10. Microsoft has provided a hotfix for this issue, please download it here: https://support.microsoft.com/en-us/help/3154518/support-for-tls-system-default-versions-included-in-the--net-framework

**Comment by AJDon78** [comment]
I've installed the MS hotfix, now just need to restart my computer. As soon as I've done that, I'll report back with an update. Thanks!

**Comment by daPhie79** [comment]
hope it was fixed!
