### ISSUE TITLE
"Could not find part of path" SNES Classic

### ISSUE THREAD

**Issue by Cobbitus** [TeamShinkansen/Hakchi2-CE#349]
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by DanTheMan827** [comment]
Sounds like you have an incomplete or damaged copy of hakchi2 ce

**Comment by Cobbitus** [comment]
> 
> 
> Sounds like you have an incomplete or damaged copy of hakchi2 ce

What would you suggest?

**Comment by Cobbitus** [comment]
Fixed the issue by re-downloading Hakchi.
