### ISSUE TITLE
DOS dialog box stays open when starting Hakchi app

### ISSUE THREAD

**Issue by AJDon78** [TeamShinkansen/Hakchi2-CE#35]
I'm not sure if this is an error, or by design, but the DOS dialogue box that pops up when you open CE, stays open (on previous Hakchi, it would close after a few seconds). If you close the dialog box, the whole app shuts down as well.

Not a huge issue of course, but just wanted to find out if it should be doing this, or if there was a way to keep it out of the way without the whole app shutting down.

**Comment by daPhie79** [comment]
this is intended for debugging purpose as the app is ever evolving. just minimize it and forget it as long as you don't have issues to report :)

**Comment by AJDon78** [comment]
Understood. Thanks daPhie79!
