### ISSUE TITLE
Support To Add Games To Turbografx 16 Mini And Neo Geo Mini.

### ISSUE THREAD

**Issue by Darkshack1980** [TeamShinkansen/Hakchi2-CE#354]
I would like to see turbografx 16 mini and neo geo mini support added to hackhi to add more games to those systems, modmyclassics mods adds too much stuff, i prefer hackchi because it keeps it basic.

**Comment by KMFDManic** [comment]
@Darkshack1980 Thanks for the request.  This is something we would all like to see.  And, if and when it happens, information on it will be updated to THIS post:)  Thanks!]

https://github.com/TeamShinkansen/Hakchi2-CE/issues/402
