### ISSUE TITLE
Genesis mini menu no run 

### ISSUE THREAD

**Issue by Maxv33** [TeamShinkansen/Hakchi2-CE#355]
install hakchi 3.8 all good. no problem. Then I try to install Project Lunar because I wanted to see what it was like. thinking that the Hakchi was erased. I realized that I could not install the PL. It told me that my system was neither an MD nor a Genesis. and then leave it even try to install the Hakchi again and everything is fine but when I turn off the console and disconnect from the PC everything disappears. as if the console didn't have Kernel. I'm confused. Is my genesis damaged? Help me! brothers

**Comment by impeeza** [comment]
You should. Remove completely the Hakchi before try to install any other personalization

**Comment by KMFDManic** [comment]
@Maxv33 Yes, if you've previously used another modification, you must go back to stock kernel, to avoid issues.  Use the backup that was made when first installing Lunar, go back to stock, then you should be safe to use hakchi.  And, same thing going from hakchi to Lunar, go back to stock:)  Hope you have things sorted, and that explains things for you!
