### ISSUE TITLE
Cannot add psx bios

### ISSUE THREAD

**Issue by growlanser** [TeamShinkansen/Hakchi2-CE#356]
I used Hachcki CE2 3.8.0 to hack my SNes Mini. I finally managed to install some games and even run them on my System. I used the Tool "Open FTP client" in Hackchi to copy the bios files (scph5500, scphp5501 and scph5502) to "etc / libretro/ system". I saved the changes to my snes mini. While running a game i press "start + select" to switch to the RetroArch Menu. I check the Core information and it indicates that the bios are still missing. How can i solve this problem?

**Comment by impeeza** [comment]
Hi, Check the case of the names,  in the discord and official FAQ page there is a spreadsheet indicating the names and case for all BIOSes

**Comment by growlanser** [comment]
Thanks, i think i got the right files, f.e. scph5501.bin, i need a guide how to succesfully install the bios

**Comment by impeeza** [comment]
The filenames are case-sensitive

**Comment by growlanser** [comment]
Ok, thanks, i got it
