### ISSUE TITLE
Portion of listed games not being categorised/recognised correctly

### ISSUE THREAD

**Issue by AJDon78** [TeamShinkansen/Hakchi2-CE#36]
While the majority of games are sorting correctly in the 'view by app' UI list, several aren't being categorized correctly, and are showing at the bottom i.e. "/bin/gba" or "/bin/md". I have the correct updated cores installed, and the command lines are the same as games categorized correctly, but they still show up like this.

It seems the games that appear in the unsorted categories at the bottom of the Games List are all zip files (same as most of the ROMs I use) but appear as a different icon in the 'folder selection' box, when uploading to the system. Seems CE is seeing them as some other kind of file, and so isn't categorising them correctly.

**Comment by daPhie79** [comment]
this is the way i've implemented it, and with the way apps (games) are categorized and handled in the code right now, i didn't invest more time to improve further. you can still rename the folders manually. it is slated for improvement!

**Comment by AJDon78** [comment]
Thank you for the reply, @daPhie79. 

May I trouble you to ask though, if you know why just a few games are being 'sorted' into the  "/bin/gba" or "/bin/md" on the app list? That is, why does the program see them as different? When i look at the files in Windows Explorer, it just says they are zip files, that same as all the other ROMs, so I'm just wondering why the few aren't listed together with the others.

i can understand why, for example, my C64 roms don't have a nice headed listing, as perhaps they are too niche, but it just seems strange that a few Megadrive, or NES games, are listed separately, as opposed to with their respective groups.

Of course, I'm sure you are very busy, so my apologies if answering my question would take too much of your time. But if you did have time to help me understand the difference, I would very much appreciate it. :)

**Comment by daPhie79** [comment]
this just happens when the file extension is not recognized correctly. pretty sure there is a bug in the regex to detect this. i think i've got it fixed for next release. however i've reworked this whole section of the code, so it needs time! thanks for your input and nice comments!!!

**Comment by AJDon78** [comment]
It's great to know the likely cause has been identified and worked on. Again, it wasn't a huge deal, but these little touches really make for a wonderful user experience. 

Thank you again for the hard work, and taking the time to reply. As always, it is sincerely appreciated. ^_^
