### ISSUE TITLE
I Cant Find Game ROMS WIth Hakchi 2

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#360]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
I Cant Find Game ROMS With Hakchi2 What To Do

**Comment by DanTheMan827** [comment]
You need to obtain the rom files yourself, then you drag them into hakchi2 ce

**Comment by ghost** [comment]
Ok How

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 30, 2020 at 6:24 PM, DanTheMan827<notifications@github.com> wrote:   


You need to obtain the rom files yourself, then you drag them into hakchi2 ce

**Comment by ghost** [comment]
How To Find The ROMS File 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 30, 2020 at 6:24 PM, DanTheMan827<notifications@github.com> wrote:   


You need to obtain the rom files yourself, then you drag them into hakchi2 ce

**Comment by ghost** [comment]
Can You Show Me How To Put Games On My SNES 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 30, 2020 at 6:36 PM, Romario Glover<romario_glover@yahoo.com> wrote:   How To Find The ROMS File 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 30, 2020 at 6:24 PM, DanTheMan827<notifications@github.com> wrote:   


You need to obtain the rom files yourself, then you drag them into hakchi2 ce

**Comment by niZ31** [comment]
Do some research and stop being lazy. It's not that hard

**Comment by DanTheMan827** [comment]
https://www.youtube.com/watch?v=l-S8Qd5gl64
