### ISSUE TITLE
Install and repair for snes classic not working

### ISSUE THREAD

**Issue by BigRob3185** [TeamShinkansen/Hakchi2-CE#361]
When ever I try to install hakchi2 3.8 to my SNES classic I get an error message saying that the system is taking to long to reboot and that it may be my firewall 
![IMG_20200817_111526](https://user-images.githubusercontent.com/69810204/90418799-3ef40480-e07b-11ea-9f2d-63f23929d6c0.jpg)

**Comment by Snaki99** [comment]
same problem here on SNES Classic Hakchi2 v3.8.0

**Comment by sonartica** [comment]
Same problem here on SNES Classic Hakchi2 v3.8.0

**Comment by cutie-suzuki** [comment]
Same problem... SNES Classic Hakchi2 v3.8.0
I've tried so many different things that the community has suggested, to no avail

**Comment by stewpan** [comment]
The discord states the following comment:

Are you using Hakchi, but you're getting a message saying "Your system is taking too long to reboot"? Try the following suggestions:

- Use the original USB Cable if using a NES/SNES Classic. The OEM cable has a white sticker.
- Turn off Windows Firewall
- Turn off your VPN (if you have one) (In some instances, VPN may need uninstalled)
- Turn off WiFi (if using a laptop)
- Turn off your Antivirus (Uninstall sometimes necessary, if conflicts arise that prevent hakchi usage...especially if "additional services" are installed)
- If using a Virtual Machine on a Mac/Linux, go to USB Settings and enable in both FEL/Powered On Mode
- Also, If using Virtual Machine, make sure you have the virtual box extension pack and usb set to at least 2.0
- You may need to install or update RNDIS Drivers
- Unplug power from back of system, wait 30 seconds, plug back in, try again!
- Restart Computer and/or hakchi

-----------------------------------------------------------------
Uninstalling my vpn and using the original usb seemed to help my problems.

**Comment by KMFDManic** [comment]
@Stvdputten Thanks for posting the most commonly needed solution to bypass this issue:)  Anyone else, who has posted in this issue, can use these steps, to 99.95 percent get back in action, unless any other conflicts exist:)

@Snaki99 @BigRob3185 @cutie-suzuki
