### ISSUE TITLE
Fix "Read Only" Files causing "Access Denied" Errors

### ISSUE THREAD

**Issue by KMFDManic** [TeamShinkansen/Hakchi2-CE#367]
**Describe the bug**

Files that are Read Only will potentially and generally trigger "Access Denied" Errors when attempting to add to Hakchi.  This can cause Hakchi to be unable to synch/export, until the problem file is deleted, and/or Read Only Permissions changed.  This is particularly a problem if someone tries to install, for example, Master BIOS Module (with Read Only BIOS Files inside!).

"Replication of the bug"

Throw anything into "Master BIOS Module, right click on it, set properties to "Read Only".  Attempt to install, you will likely trigger the "Access Denied" error.  And, you will be unable to do anymore synching/exporting, until that file is deleted or accounted for and the "Read Only" resolved.

**Comment by DanTheMan827** [comment]
Caused likely by trying to open a file read/write unnecessarily when marked as read-only.
