### ISSUE TITLE
Some characters have disappeared from game titles

### ISSUE THREAD

**Issue by AJDon78** [TeamShinkansen/Hakchi2-CE#37]
Some characters have disappeared from game titles, when displayed on my NESmini. 

These aren't special characters, but normal ones, such as ',' (commas) or '5' or 'x'. Deleting and retyping the character in Hakchi made no difference.

They appear normally in app, in file names, and in the 'transfer' screen. It's only once you actually go to the console, that you see they are missing.

**Comment by DanTheMan827** [comment]
Try installing [font remount](https://github.com/DanTheMan827-Hakchi/font_remount.hmod/releases/download/1.1.1/font_remount-0352cb4.hmod)

**Comment by AJDon78** [comment]
Bless you Dan! Yes, that fixed it. Thank you so much!
