### ISSUE TITLE
kernal not working

### ISSUE THREAD

**Issue by Dkmickel** [TeamShinkansen/Hakchi2-CE#371]
When I go the do the kernal it gets to the steps on what to do and that is all the farther it goes. Does not give me an error or anything but it will not do the kernal at all.  Not sure what to do. can you help me. Please email me at **[email removed]**. Thank you. Deborah

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by KMFDManic** [comment]
@Dkmickel Feel free to bump this post if you still have issues.  But, from the very brief information you gave, it appears you may very well have a "fake Mini" Classic.
