### ISSUE TITLE
"Can't Open device"

### ISSUE THREAD

**Issue by tamaleman** [TeamShinkansen/Hakchi2-CE#372]
**Any time I try to get the kernal installed or repaired, i keep getting the same message "Can't open device"**  
I just picked up the system yesterday. Tried getting the kernal intalled and i get Can't open device with the debug

FelException
Can't open device
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\Admin\Documents\hakchi2 (non-portable mode)
Loading configuration
Loading spine templates
Starting, version: 3.8.0
Loading libretro core info files
..Executing task: ModTasks.GetHmods
Tasker completed all tasks, conclusion: Success
Building libretro core cross index
Done, 5 cores loaded
Loading C:\Program Files (x86)\Team Shinkansen\Hakchi2 CE\data\nescarts.xml
Loading SNES Cartridge Cache
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
..Executing task: <>c__DisplayClass0_0.<DownloadFile>b__0
Executing task: <>c__DisplayClass1_0.<MoveFile>b__0
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.3, kernel 3.4.113.29-madmonkey, script v1.0.4-126
.Executing task: <>c__DisplayClass16_0.<WaitForFelOrMembootableShell>b__0
Can't open device   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
..Executing task: <>c__DisplayClass16_0.<WaitForFelOrMembootableShell>b__0
--- End of DEBUGLOG.TXT content ---

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by ReyVGM** [comment]
You have a fake mini or are using the wrong USB cable.

**Comment by KMFDManic** [comment]
@tamaleman If you still have an issue, feel free to respond.  But, you have telltale signs of a fake Mini Classic.  If you have SNES games on Main UI, and they say "instruction manual", or Star Fox 2 is missing, "not locked", also fake.  Closing this issue, for now, as all red flags point to a Fake Mini, in this case.  Good luck finding a legitimate one, if you hadn't already!  And, feel free to bump this issue, if anything else changes.

**Comment by adaptPerception** [comment]
I had the same problem. I was reasonably sure mine was not a fake. It turns out, for me, the problem was the old hakchi kernel I had install from version 2.0.21.32. I removed it by following the instruction here

https://snesclassicmods.com/how-to-switch-from-hakchi2-to-hakchi2-ce/

Summed up as,

1. Open the old hakchi2 and go to Kernel > Uninstall and hit Yes.
2. Once completed, go to Kernel > Flash original kernel and hit Yes.
3. Proceed to install Hakchi2-CE
