### ISSUE TITLE
gamegnu compatibly 

### ISSUE THREAD

**Issue by Clay5298** [TeamShinkansen/Hakchi2-CE#374]
hello not really a bug but was wondering does hakchi2 work on a non-Nintendo snes classic, i have a gamegnu bought on ebay. looks the same as the snes, but i dont know the software

**Comment by KMFDManic** [comment]
@Clay5298 Unfortunately, non-official Mini Classics do not work with hakchi.  There are sometimes other means you can utilize to modify them, even as simple as copying and pasting roms to SD cards that go into their slots.  Each "fake" is a different ballgame.  But, alas, hakchi does not support these.  It would affect quality of hakchi to try to take on 20+ clone systems, in addition to the half dozen Mini Classics we are already focusing on:)
