### ISSUE TITLE
No more cover and metadata added when i add new game

### ISSUE THREAD

**Issue by Slywars** [TeamShinkansen/Hakchi2-CE#376]
Hi all please excuse my bad english, i use hakchi2 ce 3.8.0 everything was fine when I added a game cover and metadata were added automatically, but now when I add games no more covers and metadata are added... I uninstalled and reinstalled hakchi still no cover and metadata added anymore, please someone would have a solution for this problem?

**Comment by impeeza** [comment]
Local firewall is almost always the cause

**Comment by Slywars** [comment]
i desactive windows and videtron firewall and nothing change about it, is there a possible limit, because I took several covers this way and suddenly no more covers or info added automatically (like befoore). Without changing anything its really weird :(

**Comment by DanTheMan827** [comment]
GamesDB has a limit of 5,000 requests per month per IP address, it's possible that this limit may have been reached, especially if your connection is shared in the case of something like a VPN.

If you have a way to get a new internet IP address that would give you another 5,000 requests for that IP, a VPN would be one way to do this.

**Comment by Slywars** [comment]
> 
> 
> GamesDB has a limit of 5,000 requests per month per IP address, it's possible that this limit may have been reached, especially if your connection is shared in the case of something like a VPN.
> 
> If you have a way to get a new internet IP address that would give you another 5,000 requests for that IP, a VPN would be one way to do this.

It make sense now i know why, thank you verry much i wasn,t know about it
it doesn't seem to work for arcade mame games, too bad :(

**Comment by KMFDManic** [comment]
@Slywars It would only work for games that are available to draw from in their database.  Glad you understand the limit and to wait once it overreaches said limit.  Let us know if you need any additional assistance!
