### ISSUE TITLE
sega mini retroarch problems

### ISSUE THREAD

**Issue by yang560831** [TeamShinkansen/Hakchi2-CE#379]
my  sega mini is asia version

i can play md game perfectly.

but when i install  retroarch to play some gamegear or mastersystem games.some problems happen.

the emulation works  but the controllers don't work.they just don't

so i can't play these games.

worst of all, I can't even turn off the power,so i have to shut it down rudely.

i have no idea how to fix it.

plz help.

**Comment by KMFDManic** [comment]
@yang560831 The cable that comes with the MD won't work.  With hakchi, you'd install repair kernel, then install JUST one RetroArch, and Genesis PLUS GX, and right click, select emulation Core, to run those games.  Default Controllers should work fine, as of the latest Update.
