### ISSUE TITLE
FuzzyCoverSearch match problem

### ISSUE THREAD

**Issue by u4113057** [TeamShinkansen/Hakchi2-CE#38]
when i start hakchi2 if i had following boxart in art folder it just replace original image of original games

in debug windows show below.

Resetting game "???????????".
Resetting game "?????? ?????????".
Resetting game "??????????????? ? ???????????".
Resetting game "?????X".
FuzzyCoverSearch matched "?????X" with "C:\hakchi2_CE_1.1.0\art\X Zone (Japan, USA).png".
Saving application "?????X" as CLV-P-VABCJ
Resetting game "????".
Resetting game "???????RPG".
Resetting game "????2".
FuzzyCoverSearch matched "????2" with "C:\hakchi2_CE_1.1.0\art\2020 Super Baseball (USA).png".
Saving application "????2" as CLV-P-VABRJ
Resetting game "???????????VI".
FuzzyCoverSearch matched "???????????VI" with "C:\hakchi2_CE_1.1.0\art\Virtual Bart (USA).png".
Saving application "???????????VI" as CLV-P-VABTJ
Resetting game "????????".
Resetting game "???????? ???????".
Resetting game "????????????????".
Resetting game "????????".
Resetting game "??????? ?????????".
Resetting game "????????2".
FuzzyCoverSearch matched "????????2" with "C:\hakchi2_CE_1.1.0\art\2020 Super Baseball (USA).png".
Saving application "????????2" as CLV-P-VADKJ
Resetting game "??????".

**Comment by daPhie79** [comment]
i'm guessing the games are in Japanese? there's some difficulty matching foreign characters, and the search algorithm makes some false matches sometimes. when resetting original games, it's just like deleting them and re-adding them to hakchi2.

**Comment by daPhie79** [comment]
this should be fixed in the next release, or at least the behavior should be completely different as i've completely rewritten the matching algorithm!
