### ISSUE TITLE
Program not loading the classic or original roms

### ISSUE THREAD

**Issue by onesimo93** [TeamShinkansen/Hakchi2-CE#380]
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by onesimo93** [comment]
Here is the error code>

UnauthorizedAccessException
Access to the path 'Mario_Party_2.zip' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at com.clusterrr.hakchi_gui.Tasks.LoadGamesTask.LoadGamesFromFiles(Tasker tasker, Object syncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\Ivanho\Documents\hakchi2 (non-portable mode)
Loading configuration
Loading spine templates
Starting, version: 3.8.0
Loading libretro core info files
..........Executing task: ModTasks.GetHmods
Tasker completed all tasks, conclusion: Success
Building libretro core cross index
Done, 7 cores loaded
Loading C:\Program Files (x86)\Team Shinkansen\Hakchi2 CE\data\nescarts.xml
Loading SNES Cartridge Cache
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
....Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Game directory "C:\Users\Ivanho\Documents\hakchi2\games\CLV-Z-UZXTD" is invalid, deleting
Access to the path 'Mario_Party_2.zip' is denied.   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at com.clusterrr.hakchi_gui.Tasks.LoadGamesTask.LoadGamesFromFiles(Tasker tasker, Object syncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
....Executing task: <>c__DisplayClass0_0.<DownloadFile>b__0
Executing task: <>c__DisplayClass1_0.<MoveFile>b__0
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.3, kernel 3.4.113.29-madmonkey, script v1.0.4-126
Saving selected games
Saving configuration
.....Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Game directory "C:\Users\Ivanho\Documents\hakchi2\games\CLV-Z-UZXTD" is invalid, deleting
--- End of DEBUGLOG.TXT content ---

**Comment by KMFDManic** [comment]
@onesimo93 Access Denied error has been fixed as of latest hakchi 3.9.1  If you still get it in an older hakchi, you simply need to right click on games folder, properties, uncheck read only, apply, and then hakchi should no longer have the read only error:)
