### ISSUE TITLE
My mega drvie mini get a black screen

### ISSUE THREAD

**Issue by alluget** [TeamShinkansen/Hakchi2-CE#381]
Can any one help , after install the retroid to the mini, it hold at the Hakchi screem, if I use hakchi to reset , it can boot.But if I reboot it again , it only come with music, but no video can seen, help
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by DanTheMan827** [comment]
Did you happen to install the overclock mod too?

**Comment by KMFDManic** [comment]
@alluget Are you still having issues?  You need to make sure you have appropriate power source, NOT using the cable that comes with the MD Mini, and not plugged into a port on TV...But, into a wall outlet.

**Comment by KMFDManic** [comment]
@alluget If you still have issues, feel free to bump this post.  For now, it will be closed.  We have no problem trying to help you resolve, if you still have a problem.  But, a response will be quite helpful in getting that underway, in the event you do still need fixed up:)
