### ISSUE TITLE
User_data.tar, restore hakchi game list from console backup. Snes Mini USA.

### ISSUE THREAD

**Issue by Xeddius** [TeamShinkansen/Hakchi2-CE#384]
My original hard drive with Hakchi was damaged a few years ago, I recently decided I would like to update my snes mini, I have downloaded the newest hackchi2-ce made a user_data dump/backup, however I'm unable to restore my games to the hakchi menu, copying `hakchi/games` from the tar to the games folder for hakchi is possible but reloading makes the folders disappear and nothing **ever** shows up inside of hackchi2-CE aside from "original games". Is there really no simple way to restore my hakchi setup from the snes mini itself? WTF am I doing wrong here?

Why does Hakchi delete anything in the games folder on startup?

And if there isn't such a thing can we possibly get a nice option in the advanced menu for this?
Something like: "recover/import games from user_data.tar backup."

**Comment by KASMonkey595** [comment]
In a similar situation here, would love to see some kind of solution other than starting all over!

**Comment by Xeddius** [comment]
> 
> 
> In a similar situation here, would love to see some kind of solution other than starting all over!

I asked on discord and was informed that this might be fixed in the future. They said to FTP in and copy the CLV folder to Hakchi.
I wasn't able to get it working, but others might have success.

"full importing of game libraries from minis, especially if you had them in folders, is not guaranteed to yet work.  But, it is actually an idea being tossed around as a fix up in near future."

**Comment by KMFDManic** [comment]
@KASMonkey595 @Xeddius This feature is now a reality in latest hakchi 3.9.1:)  Have fun!
