### ISSUE TITLE
Snes Mini - Roms not working after Hakchi upgrade

### ISSUE THREAD

**Issue by hoagie12** [TeamShinkansen/Hakchi2-CE#385]
Hi everyone,

I'm using my Snes Mini with Hakchi / Retroarch for 2 years almost, and it was working great.
I just upgrade my Hakchi to the 3.8 version, and connected my Snes mini to upload a new game.
I was requested to reinstall kernel on my snes, the process seemed to work fine, but since I'm not able to launch roms on it except the original ones that came with it.
When I try, I just have a quick "loading" screen, and then I'm coming back to the games selection screen. Sometimes I can see the first screens and menu of the game I have launched, and move into the first menus, but the sounds are those of the selection games screen... And when I choose an item, the game is crashing.
Any ideas ?

**Comment by DanTheMan827** [comment]
When going from a version that old to the newest you're bound to have incompatible mods, including retroarch.

Uninstall any retroarch and cores you may have on the classic, download the newest versions from KMFD's Mod Hub, and install those.

You'll probably have to change the command line for the launchers too, select the games that need to be changed, right click on them, and choose "Select emulation core"

**Comment by hoagie12** [comment]
I just tried this and it works great!
I thought it was something like that, but I wasn't able to process it...
Thanks a lot for your support! Hope you have a nice holiday season by the way...

**Comment by KMFDManic** [comment]
@hoagie12 Glad all is ok on your end!  And, stay safe:)
