### ISSUE TITLE
Hakchi 3.8 - moving from internal memory to SD Card

### ISSUE THREAD

**Issue by hoagie12** [TeamShinkansen/Hakchi2-CE#387]
Hi,

I just bought an OTG cable and a USB stick for my Snes Mini. The USB stick has been NTS formatted.
I installed new games from cores I never used before : ScummVM, Commodore Amiga.
Once they are recognized by hakchi, I clicked on export to USB.
The games do appear in the games selection screen, but they cannot been launched properly.
I expect I have to reinitialize the whole system so that the USB stick can be used... How can I do that ?

Thanks a lot for your help...

**Comment by impeeza** [comment]
Hi. The bug section is not a support channel, please read the readne, de wiki or go to the official support site

**Comment by hoagie12** [comment]
Thank you, sorry for the wrong post, will post it in the right place.
