### ISSUE TITLE
SEGA MEGADRIVE MINI -ERROR 255

### ISSUE THREAD

**Issue by sere69sp** [TeamShinkansen/Hakchi2-CE#391]
Hello,

this is my first time here.

I have a problem with Sega Megadrive Mini ... I have tried to  install hakchi kernel a few times and it's impossible. Yesterday I installed  the true blue flaser software and after it I just can see Assy Test Program (MOON-mass-moon-es1-v0.8.3-1085€-1f2365d)

but I can't install hakchi kernel or project lunar. I always have error 255 (image attached) 
![2021-01-19_0-11-19](https://user-images.githubusercontent.com/77646961/104970599-5a798780-59ec-11eb-93e7-244319d744c9.jpg)

Does anyone knows how to fix this bricked console? thanks in advance

[Technical Information.txt](https://github.com/TeamShinkansen/Hakchi2-CE/files/5832754/Technical.Information.txt)

**Comment by DanTheMan827** [comment]
Restore a backup or try to format the user data partition

**Comment by sere69sp** [comment]
> Restore a backup or try to format the user data partition

I have format the user data partition and DONE!!!!! you are my best friend right now!!!!! thank you so much
