### ISSUE TITLE
SNES & NES classics not recognised by 3.8

### ISSUE THREAD

**Issue by TheDantastic** [TeamShinkansen/Hakchi2-CE#394]
**Describe the bug**  
previously used SNES and NES not being detected by Hakchi, used 2 laptops, 1 desktop, multiple cables and ports. 

**To Reproduce**  
Run Hakchi,
Connect NES/SNES to Laptop/desktop.
Switch on NES/SNES
Windows confirms connection with audible signal.
Hakchi continues to display red dot.
Driver downloaded as per FAQ's. Installed and device manager identifies NES/SNES
Hakchi still showing red dot and will not identify device.

**Expected behavior**  
Hakchi to recognise device

**Screenshots**  
![image](https://user-images.githubusercontent.com/78379740/106507302-bf3fe200-64c2-11eb-8503-e2a9bde090d6.png)
![image](https://user-images.githubusercontent.com/78379740/106507408-eac2cc80-64c2-11eb-8aa2-1304dc94d8ce.png)
![image](https://user-images.githubusercontent.com/78379740/106507551-1fcf1f00-64c3-11eb-85e6-5646b303b6e0.png)
![image](https://user-images.githubusercontent.com/78379740/106576840-7ffea900-6535-11eb-8728-4a9e0e4ded94.png)

**Additional context**

**Comment by DanTheMan827** [comment]
The SNSY device only shows up when you turn the system on without hakchi installed, install hakchi from the Kernel menu and follow the instructions

Use the [latest hakchi2 ce](https://www.github.com/TeamShinkansen/Hakchi2-CE/releases/latest) (3.8 at the time of this message)

**Comment by impeeza** [comment]
The evidence shows you haven't installed Hakchi nor the drivers please read the documentation and if you need help or support please go to the appropriate sources, the Bug report is not for support instead for real problems

**Comment by TheDantastic** [comment]
The screen shot was taken before the driver was installed. 
As per the comments. An older version of Hakchi has previously been used and additional Roms loaded and used. I’m looking to add more games and remove some that are less than perfect. 
I updated Hakchi to add more roms to my Genesis. Now the NES and SNES are no longer recognised.

**Comment by DanTheMan827** [comment]
Since you updated hakchi and it isn't being recognized, you'll need to go through the install process again, `Kernel > Reset` will re-install a clean copy of hakchi onto the system.
