### ISSUE TITLE
Device Reboot Too Slow

### ISSUE THREAD

**Issue by Bluekerman** [TeamShinkansen/Hakchi2-CE#395]
Hello There My Mini's Are Taking Too Long To Reboot
I've Tried Both The SNES And NES And It Keeps Saying "Device Taking Too Long To Reboot"
I Haven't Modded My Mini's Since 2019 I Belive
I've Done It On Previous Versions But Not CE 3.8
Help!
![image](https://user-images.githubusercontent.com/78433470/106628070-6e260180-6547-11eb-8279-2576284a74db.png)

Maybe It's Because I Was Previously Running Hakchi2 CE 2.3

**Comment by KMFDManic** [comment]
@Bluekerman Firewall, Virus Protection, VPN, WiFi, "wrong cable", are some reasons this issue may occur.  Best to unplug cable from back of system, wait a few seconds, plug back in, retry process, if no other conflicts exist.  And, yes, if on hakchi 2.3, you CANT just jump right onto a newer hakchi, without first fully going back to stock with the kernel that was dumped with 2.3.  Jumping to the new one, which handles things differently, can create conflicts.  You can go to hakchi, uninstall kernel, hold left shift, select "kernel", then it will go back to stock on that kernel.  Then, with new hakchi, install/repair kernel, to be back in action.

Follow the steps outlined here: at bottom of post, to better clarify things:)

https://github.com/TeamShinkansen/Hakchi2-CE/issues/361
