### ISSUE TITLE
SMS games won't play on SNES mini with Hackchi CE V3.9.1

### ISSUE THREAD

**Issue by Boyki007** [TeamShinkansen/Hakchi2-CE#399]
I have downloaded the latest version of Hackchi CE V3.9.1 for my SNES mini.
I already have been able to download additional ROMS for SNES and Sega Megadrive and they all work fine.
However the Sega Mastersystems with the SMS Plus module do not seem to work.
The games appear in the library of the SNES mini, but won't boot.

**Comment by DanTheMan827** [comment]
You've made sure the command line is correct and installed both retroarch and the appropriate core?

**Comment by KMFDManic** [comment]
@Boyki007 Use Genesis Plus GX, which can be selected via a right click, select emulation Core, apply.  Also have RetroArch AND said Core installed.  SMS Plus, I will check into, and fix if it needs fixed.  But, as of right now, Genesis Plus GX AND Genesis Xtreme GX Command Lines function fine.  Not only that, if you run SMS games with Xtreme Command Line, depending on the game, you can pump out some nice FM, additional channel, sound audio!

**Comment by Boyki007** [comment]
> You've made sure the command line is correct and installed both retroarch and the appropriate core?

I can not select a command line when righ clicking.
Retroarch Ozon is installed together with the SMS Plus and Genesis Extreme GX module.
The Genesis games load fine. Only Mastersystem will not load.

**Comment by KMFDManic** [comment]
If you can't select the Genesis Plus Command Line, the Core is NOT installed, or not properly downloaded.  The Command Lines are pulled, only once the hmod exists in user_mods folder with current Hakchi.  Install via Modules, Install Additional Modules Tab, NOT via download and install on Mod Hub.  This will be more reliable, as long as you use the Modules installation method.  Report Back:)  Additionally, one final note...If you have TOO much installed to your internal memory, anything else you attempt to install, simply will not work.  You can try this, as well...Kernel, Reset, Install RetroArch+Genesis Plus GX, synch ONE single game from KMFD Mod Hub, Games Tab, that is set for MD, and test.  If that works, go ahead and resynch with the additional games you want to run for SMS and such:)

**Comment by Boyki007** [comment]
> If you can't select the Genesis Plus Command Line, the Core is NOT installed, or not properly downloaded. The Command Lines are pulled, only once the hmod exists in user_mods folder with current Hakchi. Install via Modules, Install Additional Modules Tab, NOT via download and install on Mod Hub. This will be more reliable, as long as you use the Modules installation method. Report Back:) Additionally, one final note...If you have TOO much installed to your internal memory, anything else you attempt to install, simply will not work. You can try this, as well...Kernel, Reset, Install RetroArch+Genesis Plus GX, synch ONE single game from KMFD Mod Hub, Games Tab, that is set for MD, and test. If that works, go ahead and resynch with the additional games you want to run for SMS and such:)

Are you talking about hackchi V3.9.1? None of the above makes sense...
Where can I find the Genesis Plus GX?

**Comment by Boyki007** [comment]
Meanwhile I have found out that Genesis Plus GX = Genesis Extreme GX module.

**Comment by Boyki007** [comment]
Problem solved!
My roms were not the right ones...

**Comment by KMFDManic** [comment]
@Boyki007 Bad roms would do it:)

**Comment by Gaetan-dc** [comment]
I had the issue. The problem was that the SMS Plus module wasn't linked to .sms roms, When I select my games in the list and press "select emulation core", the "Core" is unassigned. If I assign "SMS Plus GX" then it works.
