### ISSUE TITLE
Unknown systems when using "group by app type"

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#4]
this is just what I have installed on my SNESC.

Maybe @KMFDManic can help with a complete list?

Also, should it be called "Group by app type" maybe "Group by platform/system/emulator"?

`/bin/32x` (Sega 32x)
`/bin/dosbox` (MS-DOS)
`/bin/fceumm` (Famicom)
`/bin/gme` (Game Music Emulator)
`/bin/lutro` (Lutro)
`/bin/msx` (MSX)
`/bin/pc98` (PC-98)
`/bin/psx` (PlayStation)
`/bin/retroarch-mini` (RetroArch stub)
`/bin/sg` (Sega SG-1000)
`/bin/snes05` (SNES)
`/bin/wsc` (WonderSwan)

**Comment by KMFDManic** [comment]
COMMANDS folder in my Core Set has appropriate Command Lines for All Cores.  I have worked with system separation before.  There will be a few odd ones that share same extensions.

I will work with the Team to devise the best calculated way of Employing them.

**Comment by igoticecream** [comment]
/bin/sh -> Shell
/bin/retroarch-mini-> RetroArch
/bin/psx-> PlayStation 1

**Comment by gingerbeardman** [comment]
Disappointing to not see the full list in 1.1.0

**Comment by daPhie79** [comment]
this requires extensive rework of the app handling code, which i am working on, but it's not small feat.

**Comment by daPhie79** [comment]
there will certainly be much less unknown systems in 1.2. i will close this issue!
