### ISSUE TITLE
Linked export text disappears when using French language

### ISSUE THREAD

**Issue by DanTheMan827** [TeamShinkansen/Hakchi2-CE#401]
**Describe the bug**  
When using French as the language the linked export checkbox is not visible.

**To Reproduce**  
Change the language to French, export to USB

**Expected behavior**  
The export checkbox should be visible

**Screenshots**  
![image](https://user-images.githubusercontent.com/790119/115738397-a1ac4700-a352-11eb-8614-ea8b8588b1ea.png)

**Comment by Narkoa** [comment]
I tested all other languages, on Arabic, English, German, Portuguese, Spanish and Swedish it works fine.
