### ISSUE TITLE
Installing Wolfenstein3D does not work as intended

### ISSUE THREAD

**Issue by Narkoa** [TeamShinkansen/Hakchi2-CE#404]
**Describe the bug**  
Issue when installing Wolfenstein 3D game, it does not shows up in UI after game syncing.
Seems due to a desktop file issue : **a "/" is misplaced at the end of the line Code=CLV-G-WOLF3D/ **

**To Reproduce**  
1. Check in the Mod Hub > Games for ECWOLF: Wolfenstein 3D
2. Install prerequisite Retroarch + core ECWolf
3. Sync games with mini
4. See error --> The game is not added to mini's UI. 

**Expected behavior**  
This ending slash "/" should not be there so the game is actually displayed on UI.

**Screenshots**  
N/A

**Additional context**  
__bslenul__ discussion on Discord : https://discord.com/channels/364927341429784576/365280250109755413/835964953927090176
Link to the corrected file : https://cdn.discordapp.com/attachments/365280250109755413/836161337113444362/CLV-G-WOLF3D.desktop

**Comment by KMFDManic** [comment]
@Narkoa I actually fixed this with the last Release.  If you go to Mod Hub, Games Tab, redownload the game, you should see the desktop file displays the CODE correctly:)

Code=CLV-G-WOLF3D

Is what I see just rechecking from Mod Hub, right now.  Please confirm on your end, thanks!

**Comment by Narkoa** [comment]
Tested and acknowledged : "Code=CLV-G-WOLF3D" found in CLV-G-WOLF3D.desktop file.
Closing the issue. 
Thank for the fix!
