### ISSUE TITLE
Filenames exceeding 64 characters cause c7 error

### ISSUE THREAD

**Issue by Jon8RFC** [TeamShinkansen/Hakchi2-CE#42]
64 characters (including the extension but excluding the period of the extension) is the absolute limit.  Hakchi should alert users to change the file names of files which are too long, and not allow files with names which are too long.  I would think that having hakchi manually rename files during the copy process could work, but be a burden for too many files.

To clarify, the issue isn't the display within the console (I haven't tested what the limit is there), but the original filename when it's selected to be added as a new game.

For example, the following file causes a c7 error upon launching the game:
ALttP - VT_no-glitches-29_normal-standard_randomized-ganon_422562252.sfc

I tested with a generic Aladin rom, renamed it to the above, and it causes a c7 error.

**Comment by daPhie79** [comment]
didn't know about this actually, i fixed this in the mainline branch now, it will be in next release

**Comment by daPhie79** [comment]
is it possible the spaces in the filename might also cause issues? the current (new) file generation code allows for a max filename of 64 characters and no spaces and no funny characters. should be fixed.

**Comment by Jon8RFC** [comment]
Thanks, this will be great!
