### ISSUE TITLE
Hakchi v3.9.2 no google images

### ISSUE THREAD

**Issue by edmaul69** [TeamShinkansen/Hakchi2-CE#420]
**Describe the bug**  
when you click the google button no images show up. Just a blank white screen

**To Reproduce**  
<!-- Steps to reproduce the behavior:
1. If you click the google button it brings up a white empty box.

**Comment by impeeza** [comment]
It's True, for my running on Windows 10 in debug mode, the error is:

`Web request: https://www.google.com/search?q=Balloon+Fight+(fds+%7c+nes+%7c+famicom)+(box%7ccover)+art&source=lnms&tbm=isch
No results found`
but if i put the URL on a google tab images are find:
![image](https://user-images.githubusercontent.com/41979604/155643361-b78e27ce-24c3-4161-ae69-aa36b1dff585.png)

**Comment by tails101** [comment]
the issue is back
