### ISSUE TITLE
help me. my genesis mini

### ISSUE THREAD

**Issue by jimi222dfff** [TeamShinkansen/Hakchi2-CE#424]
![캡처](https://user-images.githubusercontent.com/106525217/170964735-adbb3a31-3eb4-4652-a681-0815fbfd2aab.PNG)

![vvvvv](https://user-images.githubusercontent.com/106525217/170966474-05929448-3daa-4227-95ff-e7cd3f90865a.PNG)

**Comment by jimi222dfff** [comment]
It's not working anymore. no vpn. no virus . no fire wall. 85percent to twenty minutes have passed

**Comment by KMFDManic** [comment]
The problem could very well just be your cable.  Best to use the original one that comes with the system.

**Comment by jimi222dfff** [comment]
The Mega drive original cable did not work, and the Nes mini cable and the Android cable were used. It's still not working 
-----Original Message-----

**Comment by impeeza** [comment]
Remember the Original Mega Drive cable is only for charge, use a know good working data cable, check the drivers on your PC (if needed remove and reinstall the drivers) and restar the console.

**Comment by jimi222dfff** [comment]
I didn't understand which driver to install 
-----Original Message-----

**Comment by impeeza** [comment]
Ok, your problem could be no following the instructions, please read the page of the README.MD and follow all the instructions. this is no space for help support, this is a Bug an Issue reporting zone.
