### ISSUE TITLE
USB hmod management

### ISSUE THREAD

**Issue by PerraDJ** [TeamShinkansen/Hakchi2-CE#43]
Hi!

I would like to have the feature to add and replace hmods on USB with Hakchi2 CE 1.1.0?
It would be very much appreciated.

Thank you so much for a super good job!

/PerraDJ

**Comment by KMFDManic** [comment]
@PerraDJ This sort of management can be a double edged sword.  The best way to do this, currently, is to use my current set (which easily replaces each previous version) at:

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases

After initial installation of any HMODs, you can easily Update them simply by creating on your flash drive...

hakchi/transfer and copying the updated hmods into transfer, booting up, and you will get a double splash screen!  If you have any more questions, let me know:)
