### ISSUE TITLE
Italian.

### ISSUE THREAD

**Issue by Leonardo5681** [TeamShinkansen/Hakchi2-CE#440]
Hi, I would like to have the Italian language on Hakchi2CE, if you want I can do the translation, but I only do the translation

**Comment by DanTheMan827** [comment]
Fill out the attached file with the new translations and send it back to me.

Some strings may contain multiple lines.

If you come across things like `{0}` or `{1}`, they can be moved around in the phrase, but they can not be removed.  They will be replaced with various values as the program runs and uses them.

The translations will also need updates periodically,

[2022_11_08_14_50.xlsx](https://github.com/TeamShinkansen/Hakchi2-CE/files/9965215/2022_11_08_14_50.xlsx)

**Comment by Leonardo5681** [comment]
emh I thought it was much simpler, but is there already someone working on it? Or can I take the language pack from hakchi2 and put it in hakchi2CE?

**Comment by DanTheMan827** [comment]
It's not really that simple

Much of the text in ce either wasn't in hakchi2, or things have changed.

**Comment by Leonardo5681** [comment]
the problem is that it takes more than two hours in my opinion to do it then tell me if it doesn't take much, since today I'm free I try ok

**Comment by Leonardo5681** [comment]
I'm working on the translation I'm on line 150 within this week maybe I'll send it to you

**Comment by Leonardo5681** [comment]
Hey, I'm done translating. I'll send you the file, tell me if it's okay.
[2022_11_08_14_50_compiled.xlsx](https://github.com/TeamShinkansen/Hakchi2-CE/files/9995646/2022_11_08_14_50_compiled.xlsx)

**Comment by Leonardo5681** [comment]
hey?

**Comment by DanTheMan827** [comment]
Sorry, I'll get you a build tomorrow.

**Comment by Leonardo5681** [comment]
Okok

**Comment by Leonardo5681** [comment]
Sorry, I realized that I made a mistake, instead of automatic I wrote the folder management thing. So instead of that file use this, and sorry again.
[2022_11_08_14_50_compiled.xlsx](https://github.com/TeamShinkansen/Hakchi2-CE/files/10003502/2022_11_08_14_50_compiled.xlsx)

**Comment by Leonardo5681** [comment]
it looks the same but I fixed the error
