### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by impeeza** [TeamShinkansen/Hakchi2-CE#446]
Last release was from Mar 2022, there has been several commits since then, will be a new release soon?

Thanks for your help.

**Comment by Leonardo5681** [comment]
It could, but I am in contact with the developer and he said that due to personal commitments he is not working on it at the moment, so for hakchi2CE 3.10 you will have to wait a bit. Have a nice day

**Comment by impeeza** [comment]
Thanks a lot for your quick response,  and thanks a lot for your great work.

**Comment by Leonardo5681** [comment]
Thank you❤️
