### ISSUE TITLE
NES mini: Uncorrect FEL device/mode

### ISSUE THREAD

**Issue by nmrugg** [TeamShinkansen/Hakchi2-CE#463]
I'm not able to install the kernel. When I try to connect the NES mini in FEL mode, I get this error:

```
Checking USB endpoints...
IN endpoint found: 129
IN endpoint maxsize: 512
OUT endpoint found: 2
OUT endpoint maxsize: 512
Uncorrect FEL device/mode
```

<details>
<summary>Full error log</summary>
<pre>
FelException
Can't open device
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired) in D:\a\1\s\Tasks\MembootTasks.cs:line 293
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.<>c__DisplayClass16_0.<WaitForFelOrMembootableShell>b__0(Tasker tasker, Object syncObject) in D:\a\1\s\Tasks\MembootTasks.cs:line 326
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread() in D:\a\1\s\Tasks\Tasker.cs:line 410
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\user\Documents\hakchi2 (non-portable mode)
Loading spine templates
Starting, version: 3.9.3
Loading libretro core info files
..Executing task: ModTasks.GetHmods
Tasker completed all tasks, conclusion: Success
Building libretro core cross index
Done, 5 cores loaded
Loading C:\Program Files (x86)\Team Shinkansen\Hakchi2 CE\data\nescarts.xml
Loading SNES Cartridge Cache
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] Checking for upgrade actions. Last run version: 0.0.0.0, current version: 3.9.3.0
[Upgrade] Running upgrade action 0.0.0.0 -> 3.0.0.0
.Executing task: GameTask.SyncOriginalGames
Loading original games data
Resetting game "????????? ????".
Resetting game "?????????II ???7?".
Resetting game "??????? ????".
Resetting game "???????3 ???".
Resetting game "???????Z ??!????".
Resetting game "????? ??????????".
Resetting game "????? ?????????".
Resetting game "??????".
Resetting game "??????II ??????????".
Resetting game "????3 ????? ????".
Resetting game "????? ????".
Resetting game "????? ???? ???".
Resetting game "???? ????????".
Resetting game "?!!?? ?????".
Resetting game "???????????? FANTASTIC WORLD!!".
Resetting game "?????BLUES".
Resetting game "????????".
Resetting game "??????".
Resetting game "???".
Resetting game "????".
Resetting game "Landstalker".
Resetting game "The Story of Thor".
Resetting game "Alien Soldier".
Resetting game "Alisia Dragoon".
Resetting game "Castlevania: BLOODLINES".
Resetting game "Castle of Illusion Starring Mickey Mouse".
Resetting game "Comix Zone".
Resetting game "Contra: Hard Corps".
Resetting game "Disney's Aladdin".
Resetting game "Dynamite Headdy".
Resetting game "Gauntlet IV".
Resetting game "Ghouls 'n Ghosts".
Resetting game "Gunstar Heroes".
Resetting game "Landstalker".
Resetting game "Mega Man: The Wily Wars".
Resetting game "M.U.S.H.A.".
Resetting game "OutRun 2019".
Resetting game "Phantasy Star IV".
Resetting game "Dr. Robotnik's Mean Bean Machine".
Resetting game "Road Rash II".
Resetting game "Shining Force".
Resetting game "Shining Force II".
Resetting game "Sonic The Hedgehog".
Resetting game "Sonic The Hedgehog 2".
Resetting game "Streets of Rage 2".
Resetting game "Strider".
Resetting game "Sword of Vermilion".
Resetting game "Target Earth".
Resetting game "Tetris?".
Resetting game "Beyond Oasis".
Resetting game "Wonder Boy in Monster World".
Resetting game "World of Illusion Starring Mickey Mouse and Donald Duck".
Resetting game "Landstalker".
Resetting game "Landstalker".
Resetting game "La Légende de Thor".
Resetting game "The Story of Thor".
Resetting game "??????????".
Resetting game "?????????".
Resetting game "VAMPIRE KILLER(????????)".
Resetting game "???? ??????? ?????????".
Resetting game "Columns".
Resetting game "????????".
Resetting game "??? ?·?????".
Resetting game "Darius".
Resetting game "Disney's Aladdin".
Resetting game "Dynamite Headdy".
Resetting game "Value Games in a Can".
Resetting game "Gauntlet IV".
Resetting game "????".
Resetting game "Golden Axe".
Resetting game "??????????".
Resetting game "???????? ~?????~".
Resetting game "Langrisser II".
Resetting game "Marble Madness".
Resetting game "???????????".
Resetting game "Monster World IV".
Resetting game "??????".
Resetting game "OutRun2019".
Resetting game "????????? ~???????~".
Resetting game "????".
Resetting game "Puyo Puyo 2".
Resetting game "???·????II".
Resetting game "??????·???? ~?????~".
Resetting game "??????·????II ?????".
Resetting game "Slap Fight".
Resetting game "Snow Bros.".
Resetting game "????·?·??????".
Resetting game "????·?·??????2".
Resetting game "Space Harrier II".
Resetting game "??·????II ???????".
Resetting game "????????".
Resetting game "Super Fantasy Zone".
Resetting game "???????".
Resetting game "Puzzle & Action: Tant-R".
Resetting game "????????".
Resetting game "?????".
Resetting game "The Revenge of Shinobi".
Resetting game "????? ?? ?? ~?????~".
Resetting game "Thunder Force III".
Resetting game "Wrestleball".
Resetting game "???????V ?????????III".
Resetting game "???? ????&???? ????????????".
Resetting game "??? ?? ??".
Resetting game "Castlevania: The New Generation".
Resetting game "Probotector".
Resetting game "The Story of Thor".
Resetting game "???? ~?????~".
Resetting game "Landstalker".
Resetting game "The Story of Thor".
Resetting game "Alex Kidd in the Enchanted Castle".
Resetting game "ALISIA DRAGOON".
Resetting game "Altered Beast".
Resetting game "Castlevania: The New Generation".
Resetting game "Castle of Illusion Starring Mickey Mouse".
Resetting game "Columns".
Resetting game "Comix Zone".
Resetting game "Probotector".
Resetting game "Darius".
Resetting game "Disney's Aladdin".
Resetting game "Dr. Robotnik's Mean Bean Machine".
Resetting game "Dynamite Headdy".
Resetting game "Earthworm Jim".
Resetting game "Ecco the Dolphin".
Resetting game "Eternal Champions".
Resetting game "Ghouls 'n Ghosts".
Resetting game "Golden Axe".
Resetting game "Gunstar Heroes".
Resetting game "Kid Chameleon".
Resetting game "Landstalker".
Resetting game "???????".
Resetting game "Mega Man: The Wily Wars".
Resetting game "Monster World IV".
Resetting game "Mortal Kombat II".
Resetting game "Phantasy Star IV".
Resetting game "Road Rash II".
Resetting game "Shining Force".
Resetting game "Shinobi III: Return of the Ninja Master".
Resetting game "Sonic Spinball".
Resetting game "Sonic The Hedgehog".
Resetting game "Sonic The Hedgehog 2".
Resetting game "Space Harrier II".
Resetting game "Streets of Rage II".
Resetting game "STREET FIGHTER II' : SPECIAL CHAMPION EDITION".
Resetting game "Strider".
Resetting game "Super Fantasy Zone".
Resetting game "Sword of Vermilion".
Resetting game "Tetris?".
Resetting game "The Story of Thor".
Resetting game "Thunder Force III".
Resetting game "ToeJam & Earl".
Resetting game "Vectorman".
Resetting game "Virtua Fighter 2".
Resetting game "Wonder Boy in Monster World".
Resetting game "World of Illusion Starring Mickey Mouse and Donald Duck".
Resetting game "Landstalker".
Resetting game "Light Crusader".
Resetting game "Sonic The Hedgehog Spinball".
Resetting game "Landstalker".
Resetting game "La Légende de Thor".
Resetting game "???????? ????".
Resetting game "?????????".
Resetting game "???".
Resetting game "VAMPIRE KILLER(????????)".
Resetting game "???? ??????? ?????????".
Resetting game "????????".
Resetting game "??? ?·?????".
Resetting game "Disney's Aladdin".
Resetting game "????".
Resetting game "???????????".
Resetting game "???·?·?????".
Resetting game "????????????".
Resetting game "????".
Resetting game "??????????".
Resetting game "????????".
Resetting game "???????? ~?????~".
Resetting game "?????????".
Resetting game "???????????".
Resetting game "????????? ~???????~".
Resetting game "???·????II".
Resetting game "??????·???? ~?????~".
Resetting game "?·?????II".
Resetting game "??????????".
Resetting game "????·?·??????".
Resetting game "????·?·??????2".
Resetting game "??????????II??????? CHAMPION EDITION".
Resetting game "????????".
Resetting game "Sword of Vermilion".
Resetting game "?????".
Resetting game "????? ?? ?? ~?????~".
Resetting game "???????V ?????????III".
Resetting game "???? ????&???? ????????????".
Resetting game "???? ??".
Resetting game "??? ? ????".
Resetting game "??? ?? ??".
Resetting game "The Story of Thor".
Resetting game "Streets of Rage II".
Resetting game "Landstalker".
Resetting game "The Story of Thor".
Resetting game "ALISIA DRAGOON".
Resetting game "Castlevania: BLOODLINES".
Resetting game "Comix Zone".
Resetting game "Contra: Hard Corps".
Resetting game "Disney's Aladdin".
Resetting game "Dynamite Headdy".
Resetting game "Gauntlet IV".
Resetting game "Ghouls 'n Ghosts".
Resetting game "Gunstar Heroes".
Resetting game "Landstalker".
Resetting game "Mega Man: The Wily Wars".
Resetting game "Monster World IV".
Resetting game "M.U.S.H.A.".
Resetting game "Phantasy Star IV".
Resetting game "Puyo Puyo".
Resetting game "Shining Force".
Resetting game "Shining Force II".
Resetting game "Sonic The Hedgehog".
Resetting game "Sonic The Hedgehog 2".
Resetting game "Streets of Rage 2".
Resetting game "STREET FIGHTER II': SPECIAL CHAMPION EDITION".
Resetting game "Target Earth".
Resetting game "Tetris?".
Resetting game "Beyond Oasis".
Resetting game "World of Illusion Starring Mickey Mouse and Donald Duck".
Resetting game "Landstalker".
Resetting game "Landstalker".
Resetting game "La Légende de Thor".
Resetting game "The Story of Thor".
Resetting game "?????????".
Resetting game "VAMPIRE KILLER(????????)".
Resetting game "Columns".
Resetting game "????????".
Resetting game "??? ?·?????".
Resetting game "Darius".
Resetting game "Disney's Aladdin".
Resetting game "???????????".
Resetting game "Dyna Brothers 2".
Resetting game "Value Games in a Can".
Resetting game "Gauntlet IV".
Resetting game "????".
Resetting game "Golden Axe".
Resetting game "??????????".
Resetting game "???????? ~?????~".
Resetting game "Langrisser II".
Resetting game "Lord Monarch".
Resetting game "Mado Monogatari I".
Resetting game "Marble Madness".
Resetting game "???????????".
Resetting game "?????????IV".
Resetting game "??????".
Resetting game "Party Quiz Mega Q".
Resetting game "????????? ~???????~".
Resetting game "Puyo Puyo".
Resetting game "Puyo Puyo 2".
Resetting game "Rent A Hero".
Resetting game "???·????II".
Resetting game "??????·???? ~?????~".
Resetting game "Shining Force II".
Resetting game "Slap Fight".
Resetting game "Snow Bros.".
Resetting game "Sonic The Hedgehog".
Resetting game "????·?·??????2".
Resetting game "Space Harrier II".
Resetting game "??·????II ???????".
Resetting game "??????????II??????? CHAMPION EDITION".
Resetting game "Super Fantasy Zone".
Resetting game "Puzzle & Action: Tant-R".
Resetting game "????????".
Resetting game "?????".
Resetting game "The Hybrid Front".
Resetting game "The Revenge of Shinobi".
Resetting game "????? ?? ?? ~?????~".
Resetting game "Thunder Force III".
Resetting game "???? ????&???? ????????????".
Resetting game "Wrestleball".
Resetting game "Yu Yu Hakusho: Battle to Unite the Demon Plane".
Resetting game "??? ?? ??".
Resetting game "Castlevania: The New Generation".
Resetting game "Probotector".
Resetting game "The Story of Thor".
Resetting game "Road Rash II".
Resetting game "Landstalker".
Resetting game "The Story of Thor".
Resetting game "Landstalker".
Resetting game "Light Crusader".
Resetting game "Sonic The Hedgehog Spinball".
Resetting game "Landstalker".
Resetting game "La Légende de Thor".
Resetting game "The Story of Thor".
Resetting game "???????? ????".
Resetting game "?????????".
Resetting game "???".
Resetting game "VAMPIRE KILLER(????????)".
Resetting game "???? ??????? ?????????".
Resetting game "????????".
Resetting game "??? ?·?????".
Resetting game "????".
Resetting game "???????????".
Resetting game "???·?·?????".
Resetting game "????????????".
Resetting game "????".
Resetting game "??????????".
Resetting game "????????".
Resetting game "???????? ~?????~".
Resetting game "?????????".
Resetting game "???????????".
Resetting game "????????? ~???????~".
Resetting game "???·????II".
Resetting game "??????·???? ~?????~".
Resetting game "?·?????II".
Resetting game "??????????".
Resetting game "????·?·??????".
Resetting game "??·????II ???????".
Resetting game "??????????II??????? CHAMPION EDITION".
Resetting game "????????".
Resetting game "Sword of Vermilion".
Resetting game "?????".
Resetting game "????? ?? ?? ~?????~".
Resetting game "???????V ?????????III".
Resetting game "???? ????&???? ????????????".
Resetting game "??? ?? ??".
Resetting game "Castlevania: The New Generation".
Resetting game "Probotector".
Resetting game "The Story of Thor".
Resetting game "Alex Kidd in the Enchanted Castle".
Resetting game "ALISIA DRAGOON".
Resetting game "Altered Beast".
Resetting game "Castlevania: BLOODLINES".
Resetting game "Castle of Illusion Starring Mickey Mouse".
Resetting game "Columns".
Resetting game "Comix Zone".
Resetting game "Contra: Hard Corps".
Resetting game "Darius".
Resetting game "Dr. Robotnik's Mean Bean Machine".
Resetting game "Dynamite Headdy".
Resetting game "Earthworm Jim".
Resetting game "Ecco the Dolphin".
Resetting game "Eternal Champions".
Resetting game "Ghouls 'n Ghosts".
Resetting game "Golden Axe".
Resetting game "Gunstar Heroes".
Resetting game "Kid Chameleon".
Resetting game "Landstalker".
Resetting game "Light Crusader".
Resetting game "Mega Man: The Wily Wars".
Resetting game "Monster World IV".
Resetting game "Mortal Kombat II".
Resetting game "Phantasy Star IV".
Resetting game "Road Rash II".
Resetting game "Shining Force".
Resetting game "Shinobi III: Return of the Ninja Master".
Resetting game "Sonic The Hedgehog Spinball".
Resetting game "Sonic The Hedgehog".
Resetting game "Sonic The Hedgehog 2".
Resetting game "Space Harrier II".
Resetting game "Streets of Rage 2".
Resetting game "STREET FIGHTER II' : SPECIAL CHAMPION EDITION".
Resetting game "Strider".
Resetting game "Super Fantasy Zone".
Resetting game "Sword of Vermilion".
Resetting game "Tetris?".
Resetting game "Beyond Oasis".
Resetting game "Thunder Force III".
Resetting game "ToeJam & Earl".
Resetting game "Vectorman".
Resetting game "Virtua Fighter 2".
Resetting game "Wonder Boy in Monster World".
Resetting game "World of Illusion Starring Mickey Mouse and Donald Duck".
Resetting game "????????????".
Resetting game "????????????3".
Resetting game "???????USA".
Resetting game "???????".
Resetting game "????????".
Resetting game "??????????".
Resetting game "??????".
Resetting game "?????? ??????".
Resetting game "?????".
Resetting game "????????".
Resetting game "??????".
Resetting game "????????".
Resetting game "????????".
Resetting game "???????".
Resetting game "?????r2 Dr.??????".
Resetting game "???r".
Resetting game "???????????rIII".
Resetting game "?????".
Resetting game "????".
Resetting game "????????".
Resetting game "??????".
Resetting game "???????".
Resetting game "??·??·????".
Resetting game "?????".
Resetting game "??????".
Resetting game "???????".
Resetting game "???????? The Revenge".
Resetting game "??????????".
Resetting game "??????????? ????????".
Resetting game "????????".
Resetting game "Super Mario Bros.".
Resetting game "Super Mario Bros. 3".
Resetting game "Super Mario Bros. 2".
Resetting game "Donkey Kong".
Resetting game "Donkey Kong Jr.".
Resetting game "Excitebike".
Resetting game "The Legend of Zelda".
Resetting game "Kirby's Adventure".
Resetting game "Metroid".
Resetting game "Balloon Fight".
Resetting game "Zelda II - The Adventure of Link".
Resetting game "Punch-Out!! Featuring Mr. Dream".
Resetting game "Ice Climber".
Resetting game "Kid Icarus".
Resetting game "Mario Bros.".
Resetting game "Dr. MARIO".
Resetting game "StarTropics".
Resetting game "MEGA MANT 2".
Resetting game "GHOSTS'N GOBLINST".
Resetting game "FINAL FANTASYr".
Resetting game "BUBBLE BOBBLE".
Resetting game "PAC-MAN".
Resetting game "Galaga".
Resetting game "Castlevania".
Resetting game "GRADIUS".
Resetting game "Super C".
Resetting game "Castlevania II Simon's Quest".
Resetting game "NINJA GAIDEN".
Resetting game "TECMO BOWL".
Resetting game "DOUBLE DRAGON II: The Revenge".
Resetting game "Super Mario World".
Resetting game "F-ZERO".
Resetting game "The Legend of Zelda: A Link to the Past".
Resetting game "Super Mario Kart".
Resetting game "Super Metroid".
Resetting game "EarthBound".
Resetting game "Kirby's Dream Course".
Resetting game "Donkey Kong Country".
Resetting game "Kirby Super Star".
Resetting game "Super Punch-Out!!".
Resetting game "Mega Man X".
Resetting game "Super Ghouls'n Ghosts".
Resetting game "Street Fighter II Turbo: Hyper Fighting".
Resetting game "Super Mario RPG: Legend of the Seven Stars".
Resetting game "Secret of Mana".
Resetting game "Final Fantasy III".
Resetting game "Super Castlevania IV".
Resetting game "CONTRA III THE ALIEN WARS".
Resetting game "Star Fox".
Resetting game "Yoshi's Island".
Resetting game "Star Fox 2".
Resetting game "???????????".
Resetting game "F-ZERO".
Resetting game "?????? ??????????".
Resetting game "??????????".
Resetting game "?????????? ????".
Resetting game "?????????".
Resetting game "???????????".
Resetting game "?????? ?????????".
Resetting game "??????????????? ? ???????????".
Resetting game "?????X".
Resetting game "????".
Resetting game "???????RPG".
Resetting game "????2".
Resetting game "???????????VI".
Resetting game "????????".
Resetting game "???????? ???????".
Resetting game "????????????????".
Resetting game "????????".
Resetting game "??????? ?????????".
Resetting game "????????2".
Resetting game "??????".
Resetting game "Super Mario World".
Resetting game "F-ZERO".
Resetting game "The Legend of Zelda: A Link to the Past".
Resetting game "Super Mario Kart".
Resetting game "Super Metroid".
Resetting game "EarthBound".
Resetting game "Kirby's Dream Course".
Resetting game "Donkey Kong Country".
Resetting game "Kirby Super Star".
Resetting game "Super Punch-Out!!".
Resetting game "Mega Man X".
Resetting game "Super Ghouls'n Ghosts".
Resetting game "Street Fighter II Turbo: Hyper Fighting".
Resetting game "Super Mario RPG: Legend of the Seven Stars".
Resetting game "Secret of Mana".
Resetting game "Final Fantasy III".
Resetting game "Super Castlevania IV".
Resetting game "CONTRA III THE ALIEN WARS".
Resetting game "Star Fox".
Resetting game "Yoshi's Island".
Resetting game "Star Fox 2".
Tasker completed all tasks, conclusion: Success
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
[Upgrade] Running upgrade action 3.0.0.0 -> 3.1.0.5
[Upgrade] Running upgrade action 3.1.0.5 -> 3.2.2.0
[Upgrade] Running upgrade action 3.2.2.0 -> 3.3.0.0
[Upgrade] Running upgrade action 0.0.0.0 -> 3.6.1.1008
[Upgrade] Running upgrade action 0.0.0.0 -> 3.8.0.1
[Upgrade] All actions executed successfully
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
.Executing task: <>c__DisplayClass0_0.<DownloadFile>b__0
Downloading: https://hakchi.net/hakchi/hakchi.hmod to C:\Users\user\AppData\Local\Temp\hakchi2-ce-temp\hakchi-latest.hmod
Executing task: <>c__DisplayClass1_0.<MoveFile>b__0
Executing task: <>c__DisplayClass70_0.<TaskTitle>b__0
Executing task: <>c__DisplayClass0_0.<DownloadFile>b__0
Downloading: https://github.com/TeamShinkansen/hash-db/releases/download/data/romfiles.xml.gz to C:\Users\user\AppData\Local\Temp\hakchi2-ce-temp\romfiles.xml
Executing task: <>c__DisplayClass1_0.<MoveFile>b__0
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.3, kernel 3.4.113.29-madmonkey, script v1.0.4-126
Downloading motd file, URL: https://teamshinkansen.github.io/motd.md
Motd timestamp: 2022-11-09T12:59:00.0000000-05:00
..Executing task: <>c__DisplayClass16_0.<WaitForFelOrMembootableShell>b__0
Checking USB endpoints...
IN endpoint found: 129
IN endpoint maxsize: 512
OUT endpoint found: 2
OUT endpoint maxsize: 512
Uncorrect FEL device/mode
--- End of DEBUGLOG.TXT content ---
</pre>
</details>

**Comment by nmrugg** [comment]
Turns out the system was not genuine.

**Comment by Zorglub51** [comment]
funny, this is what I get from a genuine PC Engine mini (z7213)
