### ISSUE TITLE
Famicom "Pages/folder structure" selection doesn't save after quitting.

### ISSUE THREAD

**Issue by speuj** [TeamShinkansen/Hakchi2-CE#47]
Just a small issue I noticed when setting up my multi-boot system.  
If you quit Hakchi2 CE while it is set to Famicom as the 'Console Type', the "Pages/folder structure" selection will always revert back to "Original games in root -> Automatic in subfolder", regardless of what it was set as when you shut it down.
This issue doesn't happen with any of the 3 other console types.  I always had mine set as custom, and I could leave and change console types without my selection reverting.  This only happened when the Console Type was set to Famicom.

**Comment by daPhie79** [comment]
should be fixed config file has changed completely. it probably was a copy+paste error!
