### ISSUE TITLE
didn't work at all

### ISSUE THREAD

**Issue by Dots227** [TeamShinkansen/Hakchi2-CE#472]
not a bug, so much as it not working at all. I go to install the kernel and i follow the instructions as it waits for my mini, and just nothing happens

i don't know if you'll be able to reproduce this, but here is what i did
1. open Hackchi2 ce
2. go to kernal -> install/repair
3. do you want to flash the custom kernal. click yes
4. unplug the snes mini from the mini
5. flip switch to on
6. hold reset, plug it in
7. nothing happens, and i felt like an idiot after holding it for a minute and nothing happens
**Expected behavior**  

i expect it to... y'know... work

**Screenshots**  

**Additional context**  
HDMI cable not plugged in during modding attempts

**Comment by Dots227** [comment]
it worked now, turns out i was using the wrong kind of cable (charging as opposed to data)

**Comment by impeeza** [comment]
> it worked now, turns out i was using the wrong kind of cable (charging as opposed to data)

Its the first step on the instructions DO NOT USE THE INCLUDED CABLE, THAT CABLE DO NO HAVE DATA LINES.  USE A FULL DATA CABLE.   please RTM and close the issue.

**Comment by Dots227** [comment]
yeah. sorry
