### ISSUE TITLE
Feature Request: Add a button in the Game Options section to open game folder

### ISSUE THREAD

**Issue by mplinuxgeek** [TeamShinkansen/Hakchi2-CE#48]
As title suggest, I often find myself copying the game folder string (ie CLV-Z-SQMJO) and pasting it into the address bar of Windows Explorer to go into the game folder when adding extra files like BIOS or WADs or replacing a mame ROM with a different version etc.

Alternatively maybe a button to add the extra files?

Just a simple UI tweak that would help with work flows.

**Comment by daPhie79** [comment]
just press F4, or right click the game an select "show in windows explorer" !

**Comment by mplinuxgeek** [comment]
I don't even know how I missed that... thanks.

**Comment by daPhie79** [comment]
no problem, happy that it was there already :)
