### ISSUE TITLE
Fullscreen Mode

### ISSUE THREAD

**Issue by CoMmAnDrX** [TeamShinkansen/Hakchi2-CE#49]
Since upgrading to Hakchi CE and RetroArch 1.7.1, I no longer have  true full screen (1920x1080)  in 16:9 

![20180325_155311](https://user-images.githubusercontent.com/37781115/37879366-e21f2452-3045-11e8-9b1c-500c5fa2422f.png)

I've gone through the settings and can't seem to rectify this. I could go back to RetroArch 1.1c but that does not support the ppsspp core. Any help with this would be great.

Thank You!

**Comment by daPhie79** [comment]
that's something to ask either TheOtherGuys who maintain a select selection of cores, or KMFDManic who maintains his regularly updated core sets. we can't do anything on our end for this! it's a retroarch setting thing.
