### ISSUE TITLE
Strange group name when using "group by app type"

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#5]
`/bin/pc98` has one entry that for some reason is put on it's own? Maybe a regex false match?

![screen shot 2018-02-03 at 19 06 57](https://user-images.githubusercontent.com/49612/35770554-72452d68-0915-11e8-9d7c-f6f59d5e6793.png)

**Comment by KMFDManic** [comment]
Extensions on the game is different, I would assume?  hdi, fdi?

**Comment by gingerbeardman** [comment]
Good spot! Top 3 are hdi, bottom one is fdi

**Comment by daPhie79** [comment]
i think i have it fixed in my branch, so it should be fixed soon. it might also work better if i can work the new libretro integration code!

**Comment by gingerbeardman** [comment]
@daPhie79 what is the "new libretro integration code"?

**Comment by daPhie79** [comment]
it's the code i've been working on for the last week or so.

**Comment by gingerbeardman** [comment]
Great - thanks!
