### ISSUE TITLE
Error when syncing games to SD modded SNES Mini

### ISSUE THREAD

**Issue by DecanFrost** [TeamShinkansen/Hakchi2-CE#50]
I did the SD card mod and when i sync games to the SNES mini with SD mod, I starts to transfer and gets about 200-300 games done and then get a strange error, it seems to time out after a min of transferring files.

I know the mod works and the microsd card and breakout board works, because if i take the care out and export the games manually they all play fine.. but I want to be able to do it via the snes mini usb port so i dont have to keep opening my snes mini every time

![sd error](https://user-images.githubusercontent.com/26047042/37885686-aa48553c-3084-11e8-883a-9c9a569ef49d.PNG)

**Comment by DecanFrost** [comment]
Just downloaded Hakchi2 2.30 copied the exe to the hakchi CE folder and did the and it is now syncing, with CE version it starts to build the list and Que it up and then that error happens,  with the 2.30 version it ques up and is transferring properly with no error...  whats going on I would rather use CE version and I need to resolve that error

**Comment by daPhie79** [comment]
oh, i think i know why this is happening, will try to fix if that's what i think!

**Comment by daPhie79** [comment]
hopefully this has been fixed with the longer timeouts
