### ISSUE TITLE
Improve screenshot capability by adding a hotkey and saving with a timestamped filename

### ISSUE THREAD

**Issue by aaronrudkin** [TeamShinkansen/Hakchi2-CE#51]
The current screenshot functionality is interesting, but not very useful. If someone has both the PC and the SNES Classic hooked up to different inputs on the same monitor, it is impossible to take a screenshot without pausing, switching inputs, taking the screenshot, waiting for the file to open, fishing it out of AppData, and moving it to somewhere sane.

It could be made useful by making the following changes:

1. Add a hotkey (F11, for example) to trigger the functionality without needing a mouse to access the menu. (This is easily done in MainForm.resx)
2. By default, name the screenshot based on the current timestamp instead of random characters. (This is in MainForm.cs)
3. By default, save the screenshot in a user-accessible directory, either under the hakchi folder structure, in /Desktop/, or in /Pictures/. (VLC, for instance, defaults to /Pictures/) -- instead of or in addition to opening the screenshot.

**Comment by daPhie79** [comment]
added this in 1.2RC5!
