### ISSUE TITLE
Hakchi2 CE prerelease USB_HOST bug

### ISSUE THREAD

**Issue by Remlet** [TeamShinkansen/Hakchi2-CE#57]
I just ugraded to Hakchi2 CE 1.2.0 from 1.1.0 and after I did all my things I started up USB_HOST_ and I would get a C8 error so I tried Nand and it didn't have any issues

**Comment by daPhie79** [comment]
just to be sure. did you check/uncheck the USB host option in settings menu? if it is not checked, connect your mini to your pc and power it on, once you have the green light, make sure the item is checked, and click save settings. otherwise, we'd need a bit more details about your setup to help.

**Comment by Remlet** [comment]
nope it didn't work even though I set it to Enable USB host

**Comment by KMFDManic** [comment]
What format is the flash drive in, and what brand?  What OTG Device type do you have?

**Comment by Remlet** [comment]
I have an Snes Classic (US) A sandisk 32GB usb formatted to NTFS and the OTG Device type is similar to yours pretty much

UPDATE: I reformatted it to ext4 but it wasn't the problem

**Comment by KMFDManic** [comment]
I would suggest trying uninstall kernel, flash custom, reinstall just retroarch, test one single nes clv folder by manually copying to hakchi/games. Command line should be /bin/fceumm or /bin/nestopia

**Comment by Remlet** [comment]
I'll try it when I get back home from vacation thanks

**Comment by Remlet** [comment]
it seems that one of my games could be causing the the problem

**Comment by Remlet** [comment]
I think installing every core from KMFDManic's set is the reason this is happening

**Comment by KMFDManic** [comment]
They install to Nand Memory which you have approximately 200MB to safely work with.  Definitely be careful there.  You can pay attention to the CMD prompt to see how much Nand is being used.  Despite what it still says you have remaining, stick to the safe number of 200MB give or take.  You can also use External RetroArch if you want to go that route.  But, Cores will run slower, since Nand is faster.

**Comment by Remlet** [comment]
thanks

**Comment by Remlet** [comment]
if I use external retroarch how do I transfer future cores into it?
also can you uninstall the cores stored in the NAND memory once they're transfered?
