### ISSUE TITLE
Folders to use same groupings as "group by app type"

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#6]
It would be great if folders could be sorted by platform/system like the rom list.

It could pick the correct folder icon.
And inside each platform group by letter/quantity.

**Comment by daPhie79** [comment]
the feature isn't perfect, but there's now a "Sort by App" button in the Folders Manager, and you can also sort by letters or split equally inside as well! v1.0.1 :)
