### ISSUE TITLE
Multiboot not working on USB-HOST CE 1.2.1

### ISSUE THREAD

**Issue by valenroy** [TeamShinkansen/Hakchi2-CE#64]
The system will hang at the Hakchi splash screen when I try booting into the NES hsqs while in USB-HOST mode. Works fine if USB-HOST is not enabled. Works fine as well when I was using cluster's v2.3 on USB-HOST previously.

**Comment by daPhie79** [comment]
is your usb drive formatted in NTFS?

**Comment by valenroy** [comment]
Hi there,




Thanks for thanking the time to write back. It's actually formatted in FAT32. In CE 1.2.1, USB-HOST works well with the drive in a single kernel environment but once I try to multiboot it with a US NES hsqs kernel, it will just freeze at the splash screen. The drive was working well in multiboot environment in cluster's v2.3 previously.




Get Outlook for Android







On Thu, Apr 19, 2018 at 2:33 AM +0800, "princess_daphie" <notifications@github.com> wrote:












is your usb drive formatted in NTFS?

**Comment by daPhie79** [comment]
i asked my team and the first troubleshooting suggestion is to uninstall any font fix and install font remount. if that does not work, have you tried resetting your kernel?

**Comment by valenroy** [comment]
Tried everything but still doesn't work... You guys have no issues with it? I'm just going to go back to cluster's v2.3. Thanks for the attention!
