### ISSUE TITLE
Ability to drop .sfrom files on hakchi has vanished

### ISSUE THREAD

**Issue by Mime64** [TeamShinkansen/Hakchi2-CE#65]
In previous versions I could just drop an .sfrom file on to hakchi and it would add it to the list of games. Now with the new version the mouse cursor becomes an error icon and I have to use the File menu to add the .sfrom, which is less convenient. Any chance of bringing it back?

**Comment by daPhie79** [comment]
uh, i just tried to reproduce and it works perfectly fine. are you sure you're drag and dropping an .sfrom file directly? maybe you're trying to go directly from a software to hakchi2 CE ?

**Comment by Mime64** [comment]
Apologies, it's.. working for me now too. File on the desktop, "Illusion of Gaia.sfrom", no matter how many times I dragged it on to the hakchi window it had that cursor I guess Windows uses to tell you that's not valid.

Then hakchi crashed, and now having reopened it works.

Can't reproduce again.

**Comment by daPhie79** [comment]
weird. well. hopefully it's a one-off :)
