### ISSUE TITLE
media write protected

### ISSUE THREAD

**Issue by tyjay99** [TeamShinkansen/Hakchi2-CE#66]
hi all 
been running usb linked for months without any problems Running CE1,0,0
cant use any version above that without errors  untill 1.2.1 which initially worked 
is much better and faster 
but now i get (and Previously) on lower versions this write error (see below)
tried running from laptop get write error when i try to export 
went back to 1.1.0 but that now gives the same write error  cant figure it out as the drive isnt locked can
use it as a normal drive 

so cant run from usb HD anymore cant run from laptop either realy stuck atm
error below

IOException
The media is write protected.

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.Tasks.SyncTask.ShowExportDialog(Tasker tasker)
   at com.clusterrr.hakchi_gui.Tasks.SyncTask.ExportGames(Tasker tasker, Object syncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()

**Comment by daPhie79** [comment]
does the same thing happen if you use the Debug version? if you're already using the debug version, it would help if we could see the part of the log where it happened, with some context. does the error happen right when the dialog pops up, or once the copy has started?

**Comment by tyjay99** [comment]
thanks 
i tried the debug was using retail 1.2.0 +  previously allways ran debug version 
error happens when i try to export it comes up about write error 
noticed that theres no debug.txt created allway did it on previous version so cant add that did a screen grab 
![error](https://user-images.githubusercontent.com/38589437/39096041-1c45e870-4642-11e8-9b28-0f25745fbf3f.png)

hope this helps

**Comment by nandolawson** [comment]
I have the same issue using a Win 10 64 bit virtual machine. Host machine is a MacBook with the newest macOS.

**Comment by daPhie79** [comment]
this is probably caused by elevation when updating app. this has been fixed very recently, but as long as an old setup is used, it can keep on going. try on latest version from a fresh install if you still have issues!
