### ISSUE TITLE
FRQ | Add change multiple (all) core to another for "filtered" games

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#69]
it would be nice to have the option sorting added games through the used /bin/command

e.g sort for:

/bin/clover-canoe-shvc-wr
/bin/genesis-plus-gx
/bin/segacd
/bin/gg
etc...

i dont use the system in front of the game name (dont like it that way) so this would be a handy solution for those people.
cheers

**Comment by daPhie79** [comment]
there is no way to sort on the actual command line as it's been requested so often for me not to do that, lol, but selecting `View >Sort by > Core` will essentially sort games by their used cores, based on the command line.

**Comment by ghost** [comment]
yeh well there is only one reason for me to use it, in case i want to change the core for those titles.
if theres any better way to do that, the info is most appreciated
:)

a simple change core (x to y) would be very nice... it took me 3days to add games to this nice thing. so such feature would be a great time safer at all ;)

**Comment by ghost** [comment]
found it, too obviosly jus selecting the stuff

**Comment by ghost** [comment]
closed
