### ISSUE TITLE
UnauthorizedAccessException on deleting Game

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#70]
got this error while delting a game.

`UnauthorizedAccessException
Der Zugriff auf den Pfad "Fullmetal.Alchemist.Brotherhood.EUR.PSP_XYZ.ISO" wurde verweigert.
   bei System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bei System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bei com.clusterrr.hakchi_gui.Tasks.GameTask.DeleteGames(Tasker tasker, Object SyncObject)
   bei com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()`

workaround: delete the leftover file manually through fileexplorer worked. after that the game could be removed on hackchi...

**Comment by daPhie79** [comment]
we are getting sparse reports of people getting access denied errors, but we're still not sure what's causing it. could it be possible that you've added this game right after having update the app with the auto-updater? this is one of the hypothesis we have.

**Comment by ghost** [comment]
nope i now adding and removing games on my existing fresh install of the latest core (several days now) and added the games to my 64gb usb stick.
i got this error now two times, my first thought was about a system limited filelenght?
another thing i thought about was the dots in my filenames, thats also not handlet (removed) while adding the game like underscores _... could be a problem that system is "thinking" its a fileextension in the middle of the string. (guessing).

**Comment by daPhie79** [comment]
in theory those issues should've been fixed. also, when calculating the extensions, i tried to always use the last one. is it the same unauthorized access exception on these? and when doing other things than deleting them?

**Comment by ghost** [comment]
i played around with it, it seems it has something to do with filenames or lenght. because i just got the error on such filename style

_Star.Ocean.Second.Evolution.EUR.PSP_ABCDE.iso_

but if i hit export games again, it runs for the second trie.
maybe its an issue with i/o cause my notebook has a shared usb port (physical) and my mouse isnt working correctly while transfering, maybe this is interferencing somehow... i give it a test on a single port.

`UnauthorizedAccessException
Der Zugriff auf den Pfad "D:\hakchi\games\047\CLV-I-GSYVC\Star.Ocean.Second.Evolution.EUR.PSP_ABCDE.iso" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalDelete(String path, Boolean checkHost)
   bei com.clusterrr.hakchi_gui.Tasks.SyncTask.DeleteLocalApplicationFilesFromDirectory(IEnumerable`1 filesToDelete, String rootDirectory)
   bei com.clusterrr.hakchi_gui.Tasks.SyncTask.ExportGames(Tasker tasker, Object syncObject)
   bei com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()`

**Comment by ghost** [comment]
so little update on this one.
i figured out that the error comes up if the game is played once and displays every sync until the iso gets deleted on usb-host and reuploaded by hackchi ce itself. i changed the name of the iso to sose.iso (to check if its a naming issue here) happened as well on this name.
i remember there was a freeze which resulted on an c8 of the device, maybe this is fuckin up the iso..... 
i trie to check on that.

by theway . usb-host on FAT32 and no UAC in windows activated.

**Comment by ghost** [comment]
error now on first upload to new usb stick.
`UnauthorizedAccessException
Der Zugriff auf den Pfad "C:\TEMP\SNES\hakchi2_CE_1.2.4\games_snes\CLV-I-GSYVC\sose.iso" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bei com.clusterrr.util.TrackableFileStream..ctor(String path, FileMode mode)
   bei com.clusterrr.hakchi_gui.Tasks.SyncTask.SyncLocalGames(Tasker tasker, Object syncObject)
   bei com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\TEMP\SNES\hakchi2_CE_1.2.4 (portable mode)
Loading configuration
Starting, version: 1.2.4
CoreCollection loading indexes from cache: Done!
....
--- End of DEBUGLOG.TXT content ---
`

**Comment by ghost** [comment]
since 1.2.4 no further errors on that one.
