### ISSUE TITLE
Bricked device

### ISSUE THREAD

**Issue by brianx87** [TeamShinkansen/Hakchi2-CE#71]
It appears that that by following the basic installation process my device is now bricked! Tried the reset and uninstall, device led stays on now even when in switched off, anyone know how I can fix this and what information should I grab?

**Comment by daPhie79** [comment]
on what version? what exactly did you try? it is usually impossible to brick the nes/snes mini. there is always FEL mode to go back to.

**Comment by brianx87** [comment]
Where do I find this version? I followed this [guide](http://snesclassicmods.com/how-to-add-more-games-to-snes-classic-mini/) and since it's a newer version of the software I went ahead and selected add games then sync which brought up the install kernal prompt which I followed resulting in a failure. Device no longer does anything, led stays on when power is connected despite power switch position.

EDIT: Latest version of Hakchi2 CE 1.2.3 and unsure of hardware version.

**Comment by brianx87** [comment]
This is the error I get when trying to install the kernal. https://pastebin.com/nZE60UEi

Would appreciate some help here since I followed the guide to the letter using your branch which resulted in this soft brick. Madmonkey will try and help later on Sunday.

**Comment by brianx87** [comment]
Been getting help from [reddit](https://www.reddit.com/r/miniSNESmods/comments/8fmxfm/how_to_unbrick/) maybe you can help elaborate on their solutions?

**Comment by brianx87** [comment]
MadMonkey has managed to fix my device and is sending over the details of my unique issue to your team, unfortunately I can not flash my device again until you guys have figured out the issue and updated CE.

**Comment by HappyKool** [comment]
is strange Brianx87 normally because for having soft brick you have maybe bad manipulation no ?

**Comment by HappyKool** [comment]
have you try of reflash kernel original (Dump) of your SNESM  with hakchi 2.21f and reset parameter console  ? for look if your console accept after Hakchi base

**Comment by brianx87** [comment]
Well I followed the guide to the letter which linked me to Hakchi CE 1.2.3 not any other version which resulted in a md5 mismatch when I attempted the original flash. As I said madmonkey has partially corrected my issue though I can not flash my hardware again if I attempt to do so it will break it again so my hardware is working but will require a further update when Hikchi CE 1.2.3 is updated to resolve my issue.

**Comment by super-triangle** [comment]
I'm having a similar issue here, MD5 mismatch after installing. After that, the device is black screened until I uninstall and reset things back to stock.

The one difference between this problem SNES and the last was that I used the same Hakchi CE folder I set up the last device with, instead of a fresh unzip.

**Comment by BuzzBotBaloo** [comment]
Same here. Ran into the MD5 mismatch when trying to install the custom kernel. Tried to restore to stock, and it says it was successful, but all I get is a blank screen. 

Using Win 10, Hakchi2 CE 1.2.4, North American SNESCE

I've done two NESCE before back when Hakchi2 was in it's 1.x era. But this was my first experience with Hakchi2 CE.

**Comment by brianx87** [comment]
Turns out that part of the NAND had become corrupt, you'll have to go over to the Discord server for support, Madmonkey got my hardware going again but I am unable to touch the kernal until Hakchi CE is updated properly.

**Comment by BuzzBotBaloo** [comment]
Thank you, I'll head over to the Discord chat. Could you use the none CE version of Hakchi2?

**Comment by brianx87** [comment]
No I'm stuck using CE and updating CE also caused the hardware to soft brick, don't change the version you are using and don't do anything that will touch the kernal.

**Comment by super-triangle** [comment]
As some folks noted on the reddit release discussion thread, flashing a stock kernel and factory reset worked for me. Once I had a working SNES again, flashing CE 1.1.0 worked successfully. I didn't try to do anything crazy though; added some Genesis games and a NES Classic multi boot.

CE 1.2.4 doesn't work on this device at all.

**Comment by BuzzBotBaloo** [comment]
I was never able to recover in CE 1.2.4. Yesterday, I used Hakchi2 2.30 and a download original SNES kernel to recover abd big the unti back to stock. This wasn't the first time I tried this but this time it did. Sometime during the night, little elves most have fixed it. 

Once I had it working, I flashed the Custom Kernel in 2.30 and had Hakchi2 working. But I did also try CE 1.2.4 one more time to see if the issue persists and got the Flash MD5 Mismatch error again. Repairing and flashing the unit one more time via 2.30, I decided to skip CE for now.

**Comment by HappyKool** [comment]
BuzzBotBaloo & brianx87 what was the reason for your Brick app when you install hakchi with hakchi CE 1.2.4 or other manipulations ?

**Comment by BuzzBotBaloo** [comment]
I'll have to see if I have a error log. But I got an error that stated "Flash MD5 mismatch!" while running Install/Repair and it screwed up the boot function and also couldn't be fixed with CE 1.2.4's Uninstall or Reset to Factory options. Even though CE implied the uninstalls were successful; the unit wouldn't boot. I was able to D/L a good original SNES kernel and flash it back with Hackhi 2.30

**Comment by madmonkey1907** [comment]
I figured out what the problem was. no devices bricked, just need a day or 2 to fix it. 1.1 and 2.30 should still work meanwhile.

**Comment by MikeJNZ** [comment]
Another user with what sounds like the same issue, had this for every 1.2.X release so far, restoring back to 1.1.0 fixes the issue, but would love to be able to get on the networking bandwagon at some point! :D 
EU/AU Snes mini, Windows10 64bit, hakchi installed on my same USB drive that I use for booting into USB-HOST. Upon updating Hakchi CE and running the update scripts/install custom kernel I eventually get the following error, and the mini hung at the boot splash screen, unable to power off properly until the cord is removed.

```
Exception
flash md5 mismatch! ca7cbf61c1d59347acdc55eb792b7eaa(./boot/boot.img) != 9d3c8821d0d5f53f76ff8b6ffb81fd74(flash+30)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.BootHakchi(Tasker tasker, Object syncObject) in D:\C\hakchi2\Tasks\MembootTasks.cs:line 565
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread() in D:\C\hakchi2\Tasks\Tasker.cs:line 387
--- DEBUGLOG.TXT content ---
Base directory: G:\HakchiCE (portable mode)
Loading legacy configuration file
Starting, version: 1.2.4
Loading libretro core info files
Building libretro core cross index
Downloading whitelist file, URL: https://teamshinkansen.github.io/retroarch-whitelist.txt
Loading G:\HakchiCE\data\nescarts.xml
Loading G:\HakchiCE\data\snescarts.xml
SNES XML loading done, 786 roms total
[Upgrade] Checking for upgrade actions. Last run version: 1.1.0, current version: 3.2.4.0
[Upgrade] Running upgrade action 0.0.0.0 -> 3.0.0.0
NES XML loading done, 2150 roms total
..Executing task: GameTask.SyncOriginalGames
Tasker completed all tasks, conclusion: Success
.Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
[Upgrade] Running upgrade action 3.0.0.0 -> 3.1.0.5
Converting folders_snes.xml file into eur and usa counterparts.
[Upgrade] Running upgrade action 3.1.0.5 -> 3.2.2.0
[Upgrade] All actions executed successfully
.....Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.112.18-madmonkey, script v1.0.4-116
Downloading motd file, URL: https://teamshinkansen.github.io/motd.md
Motd timestamp: 2018-05-03T10:15:00.0000000-05:00
clovershell connected
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code: 2
echo "`devmem 0x01C23800``devmem 0x01C23804``devmem 0x01C23808``devmem 0x01C2380C`" # exit code: 0
Detected device unique ID: 0461872A873C60C01D9836D76C118000
cat /etc/clover/boardtype # exit code: 0
cat /etc/clover/REGION # exit code: 0
hakchi currentFirmware # exit code: 0
Detected mounted board: dp-shvc, region: EUR, firmware: _nand_
source /var/version && echo "$bootVersion $kernelVersion $hakchiVersion" # exit code: 0
Detected versions: boot 1.0.1, kernel 3.4.112.madmonkey, script [master]v1.0.3-110(6f7b391)
.Executing task: MembootTasks.WaitForFelOrMembootableShell
[ -f /proc/atags ] # exit code: 0
Executing task: <>c__DisplayClass68_0.<TaskIf>b__0
uistop # exit code: 0
mkdir -p /tmp/kexec/ # exit code: 0
cat > "/tmp/kexec/kexec" && chmod +x "/tmp/kexec/kexec" # exit code: 0
cat > "/tmp/kexec/detached-fallback" && chmod +x "/tmp/kexec/detached-fallback" # exit code: 0
cat > "/tmp/kexec/boot.img" # exit code: 0
Executing task: MembootTasks.WaitForShellCycle
clovershell disconnected
clovershell connected
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code: 0
echo "`devmem 0x01C23800``devmem 0x01C23804``devmem 0x01C23808``devmem 0x01C2380C`" # exit code: 0
Detected device unique ID: 0461872A873C60C01D9836D76C118000
Executing task: ShellTasks.ShowSplashScreen
uistop # exit code: 0
gunzip -c - > /dev/fb0 # exit code: 0
Executing task: <>c__DisplayClass20_0.<HandleHakchi>b__0
echo "cf_install=y" >> /hakchi/config # exit code: 0
echo "cf_update=y" >> /hakchi/config # exit code: 0
mkdir -p /hakchi/transfer/ # exit code: 0
Executing task: <>c__DisplayClass6_0.<TransferBaseHmods>b__0
mkdir -p \/hakchi\/transfer # exit code: 0
queue: 40960 / 1048576, 0MB / 0MB (100%)
tar -xvC \/hakchi\/transfer # exit code: 0
Executing task: MembootTasks.BootHakchi

hakchi init script version: 1.0.2
rsync: change_dir "/newroot/etc" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
no modules for loaded kernel 3.4.112.18-madmonkey
updating hakchi...
rsync: change_dir "/newroot/bin" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
rsync: change_dir "/newroot/etc" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
installing clovercon...
creating uninstall for clovercon...
package clovercon installed
installing copyleft...
creating uninstall for copyleft...
package copyleft installed
installing font_remount...
creating uninstall for font_remount...
package font_remount installed
installing gamepath-cleanup...
package gamepath-cleanup installed
installing hakchi...
flash md5 mismatch! ca7cbf61c1d59347acdc55eb792b7eaa(./boot/boot.img) != 9d3c8821d0d5f53f76ff8b6ffb81fd74(flash+30)
package hakchi installed
installing ntfs-3g...
creating uninstall for ntfs-3g...
package ntfs-3g installed
installing tiny7zx...
creating uninstall for tiny7zx...
package tiny7zx installed
transferring data...


loading hakchi
usbMode: device
rsync: change_dir "/newroot/etc" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
overmounting /lib/modules
mount: mounting /newroot/var/lib/hakchi/rootfs/lib/modules on /newroot/lib/modules failed: No such file or directory
overmounting failed
find: /newroot/var/squashfs/usr/share/: No such file or directory
touch: /newroot/media/hakchi/write-test: No such file or directory
overmounting /bin
mount: mounting /newroot/var/lib/hakchi/rootfs/bin on /newroot/bin failed: No such file or directory
overmounting failed
overmounting /etc
mount: mounting /newroot/var/lib/hakchi/rootfs/etc on /newroot/etc failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_de/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_de/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_de/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_es/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_es/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_es/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_fr/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_fr/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_fr/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_it/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_it/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_it/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_nl/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_nl/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_nl/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_pt/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_pt/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_pt/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/eur_ru/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/eur_ru/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/eur_ru/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/jpn_ja/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/jpn_ja/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/jpn_ja/strings.lng failed: No such file or directory
overmounting failed
overmounting /usr/share/ui/snes-eur/resources/strings/usa_en/strings.lng
mount: mounting /newroot/var/lib/hakchi/rootfs/usr/share/ui/snes-eur/resources/strings/usa_en/strings.lng on /newroot/usr/share/ui/snes-eur/resources/strings/usa_en/strings.lng failed: No such file or directory
overmounting failed
menu code: 
no romz found at: /

jumping to switch_root...
no answer from device   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\C\hakchi2\Clovershell\ClovershellConnection.cs:line 266
clovershell disconnected
--- End of DEBUGLOG.TXT content ---
```

**Comment by madmonkey1907** [comment]
anyone who has this issue, find original kernel, do full uninstall and flash original kernel back with 1.2.5
then install again
except @brianx87 , you will need a simple hmod to undo changes I have done previously. just a bit later.

**Comment by daPhie79** [comment]
hopefully, this is fixed for good ^_^
