### ISSUE TITLE
"Samsung classic"?

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#72]
I've not used hakchi2CE for a while now, and came back to it today and my SNESC is being labelled as "Samsung classic" and I can't seem to do much with it.

Any ideas?

**Comment by daPhie79** [comment]
that's because it's now operating in simulated network mode. there is no distinct driver for it and it usually is detected as another android or linux networked device you've had connected to your computer before

**Comment by gingerbeardman** [comment]
I was not aware of that, would have been nice to list that in the release notes, wiki or faq for the new version.

thx
