### ISSUE TITLE
conclusion: Abort

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#74]
![screen shot 2018-04-28 at 23 10 16](https://user-images.githubusercontent.com/49612/39401291-6054975e-4b39-11e8-9d09-00d06f1e2310.png)

😭 💩

**Comment by daPhie79** [comment]
that just means an error occured, and in this case, it probably tried to reboot and the mini took too long, or something happened and it got stuck?

**Comment by gingerbeardman** [comment]
i give up, i'm going back to 1.1.0

good luck fixing the bugs

**Comment by daPhie79** [comment]
that is so weird. it works super smoothly for all of us devs, and most testers have had increasing luck with each fix. sorry for the inconvenience!

**Comment by gingerbeardman** [comment]
from my perspective - somebody who went from 1.1.0 to 1.2.2 (and then 1.2.3 manually) - the experience is a huge step backwards.

**Comment by gingerbeardman** [comment]
I managed to get to 1.2.4 this morning with slightly less problems that the other evening
