### ISSUE TITLE
Settings Reset

### ISSUE THREAD

**Issue by MindController** [TeamShinkansen/Hakchi2-CE#75]
I was on ce 1.1.0 before and I manually upgraded to ce 1.2.2 and now my controller hacks settings keep resetting.

When I install or uninstall hmods, hakchi will then prompt me with the "waiting for nes popup window" with steps 1-3, but then it realizes it's connected and continues anyway.  But during this process, the controller hacks settings will reset to default and some hmods I installed previously will still show installed, but not be working on the nesc.

I have also attempted a fresh install using Kernal > uninstall and gone through Kernel > install/repair, but the same issue occurs.

Here's a copy of the log

[debuglog1.txt](https://github.com/TeamShinkansen/hakchi2/files/1959430/debuglog1.txt)

I've also uploaded a video of it happening:

https://youtu.be/1myicRgdJMw

**Comment by daPhie79** [comment]
this indeed shouldn't happen. if you've been "carrying" the same setup for a while, upgrading as you go, and never cleaning up from scratch, you might have better results by doing so. just a suggestion. v1.2.4 should be out soon, and hopefully could fix that as many things have changed in the way we handle shell connections.

**Comment by daPhie79** [comment]
this should be fixed in latest. there was a bug in hakchi script.
