### ISSUE TITLE
BUG | incomplete language availability

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#76]
Version: hakchi2 CE v1.2.3
On this version languages can just selected for english and french. all other languages not available in the gui!

Due to the fact that the gui seems to have a problem and the other reports of bricking the device I am waiting for an updated answer to this behavior until I continue with the installation

**Comment by HappyKool** [comment]
AntiFly try of take languages other versions example of Hakchi CE v1.2.2 for look if languages is ok beware no final just test no connecting your SNESM

**Comment by ghost** [comment]
i already resettet my device this morning cause of the updated versions of KMFDManic.
language selection is working for ce v1.2.2 and not working for ce 1.2.3 (just can select between english and french, other language does not show up)

even not working in stock version direct run from unpacked zip.

[Screenshot](https://abload.de/img/languageyxuna.jpg)

**Comment by ghost** [comment]
ah lol yes exactly there just no langauge addons in the directory... i didnt check on that ;D
close it if you aware of that.
cheers

**Comment by DanTheMan827** [comment]
The majority of the language translations were actually missing about half of the text, so we just removed them until they can be re-translated.

Otherwise, you'd have about half of the program in English and half in whichever language you selected.

**Comment by ghost** [comment]
i could translate it to german iftheres any need.
but i need to know how to do that ;)
