### ISSUE TITLE
External UI no longer works?

### ISSUE THREAD

**Issue by Joonie86** [TeamShinkansen/Hakchi2-CE#77]
I recently switched from hakchi 2.21f to Hakchi 1.2.3 CE, and did factory reset my SNES MINI (USA), 

then I realized external UI files located in "usr/share/ui" don't work anymore, this was part of the features from the original hakchi2, but somehow it's disabled in this mod?

I can confirm external font files are working properly by using Font Remount, but not the language files.

do I need to make custom preinit.d for language files inside "usr/share/ui" as well?

**Comment by daPhie79** [comment]
this is something related to the external ui hmod. we have no control over hmod development, and with each new version, there is potential for these modules to need to be revised to work with newer versions!
