### ISSUE TITLE
Theme per folder?

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#8]
(Forgive me if this is the wrong place for this)

I'd like to change the theme on a per folder basis. 

At it's simplest that would mean when I am looking at SNES games I see the SNES theme, and when I am looking at NES games I see the NES theme. I could also separate my games into EN/JP and see SNES/NES or SFC/FC depending on what folder I am in.

When the user switches folders hakchi stops the UI and changes the game folder using overmount. So what's to stop us storing a `packed.png` per folder and overmounting it in the same way?

Thoughts?

**Comment by gingerbeardman** [comment]
And then I just found this: https://www.reddit.com/r/miniSNESmods/comments/7838ho/snes_classic_perfolder_ui_proof_of_concept/

I'll take this and run with it, expect a pull request or hmod soon.

```shell
overmount_folderui(){
local menu_code="$(cat "$installpath/menu")"
local device="$(cat "/etc/clover/ui")"
  if [ "$menu_code" != "000" ]; then
    if containsGames "$rootfs$gamepath/$menu_code"; then
      overmount "/usr/share/ui/$menu_code/packed.png" "/usr/share/ui/$device/resources/sprites/packed.png"
      overmount "/usr/share/ui/$menu_code/wall.png"  "/usr/share/ui/$device/resources/layout/asset/sprite/wallpaper/wall.png" && return 0
    fi
  fi
  if containsGames "$rootfs$gamepath"; then
  umount "/usr/share/ui/$device/resources/sprites/packed.png"
  umount "/usr/share/ui/$device/resources/layout/asset/sprite/wallpaper/wall.png" && return 0
  fi
  return 1
}
```

**Comment by TarkinMX** [comment]
@gingerbeardman This is awesome, I was wondering if this could be done. Another thing I was thinking about was maybe running kachikachi (nes mini emulator software) natively from the snes's clover ui so I don't have to see the system rebooting every time I want to play nes games. Looking at the command lines for both I believe it's pretty easy to do. This mod you found would be excellent for that purpose. I read the post you linked and would really love to see this as an hmod along with it supporting more than just two folders. I believe I saw a reddit post somewhere to change Mario and Luigi to different sprites and I think that would serve well with this too. For example, changing them to Sonic and Knuckles for a Sega theme.

**Comment by KMFDManic** [comment]
@gingerbeardman This would be a standalone HMOD.  I have another friend working on Themes, and this could be good to work in.  We will definitely need to figure out something, to get that amazing work out there for others to enjoy:)  This will be on the To Do list.
