### ISSUE TITLE
Feature Request | Adding game database

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#80]
so i got a thought and this would be a huge feature if it gets implemented.
ive once puttet all game information for my snes games in hackchi (original) since ive done a complete new start on hackchi i got no new energy to got allover that again.

it would be super cool to have a game database which can be filled online (with manual update or online repository)
so what to store there?
so ive got several ideas to be hones the mass is using "any" game set.... 
anyway, we could use the has of the game to store this in the database as well as the game informations (developer, cover, year...) if the hash fits a game on adding it could be autoselected with the features configured on the client side (hackchi) --> like (auto fill covers, game specs ....)

if hash unknown but game name got recognised it could popup and ask user if it should fill in the found data of game name. these data could be differed by different cores (eg. snesx9 core get the specs for snes and so on...)

this database could be filled by selected users or another feature a callback from client side, gathered hashcodes with specs upload... (advanced technique)

how do you feel about that?
cheers

**Comment by daPhie79** [comment]
if anyone wants to invest time in this, you're welcome to do a PR, because this is an involved feature addition and there are so many other issues for us to tackle with beforehand! (i can also say, personally, that i'm a bit exhausted with all the time i've put on h2ce lately, i'm concentrating on some side-projects for a little while at least for now!)

**Comment by KMFDManic** [comment]
As @daPhie79 mentioned, this would be a very time consuming process, and anyone wanting to take it on, can do a pull request.  As of right now, I implemented game database files as an HMOD, for use with Mini NES/SNES, as well as to Inject along with the PSC installer, that cover a lot of games, Playlist Style.  As far as directly in Hakchi, however, this will be a long project.  So, again, anyone wanting to take it on, go for it, and let us know if you make any solid ground.
