### ISSUE TITLE
Unable to edit PID after you enter lower case characters in extra byte field and accept

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#82]
You have to delete the game and re-add it.

**Comment by daPhie79** [comment]
the ctrl+alt+e thing?

**Comment by gingerbeardman** [comment]
Yes

Not sure I can reproduce, but the error was something to do with sfrom even though i do not use that tool. Sorry, should have taken a screen grab

**Comment by daPhie79** [comment]
I will look into this. this means it's an old bug rearing its head!
________________________________

**Comment by daPhie79** [comment]
I just tested this (I know I'm pretty late lol) and while it does pop up an overly detailed error dialog, it does not seem to corrupt the game. It saved zeros instead. If you happen to encounter this again, please take a screenshot, or a detailed way to reproduce.
