### ISSUE TITLE
confusing message after uninstall

### ISSUE THREAD

**Issue by u4113057** [TeamShinkansen/Hakchi2-CE#83]
![image](https://user-images.githubusercontent.com/33534198/39585688-91ccbf2a-4f1f-11e8-9748-171e5b3c3eb9.png)

confusing message after uninstall
first it said i can flash original kernel but there no more original dump file or even menu to flash it back
second if i want to flash custom firmware again there is no menu that said flash custom firmware (i think you mean "Install / Repair" but if you follow the instruction you will be lost on where to go next)

**Comment by daPhie79** [comment]
this should be fixed with 1.2.5
