### ISSUE TITLE
[REQ] use LaunchBox Games Database as source of cover images?

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#86]
https://gamesdb.launchbox-app.com

https://gamesdb.launchbox-app.com/games/details/82920

https://gamesdb.launchbox-app.com/games/images/82920

![https://images.launchbox-app.com/0f6cd318-aaf8-4174-af18-c2019909263b.jpg](https://images.launchbox-app.com/0f6cd318-aaf8-4174-af18-c2019909263b.jpg)

**Comment by daPhie79** [comment]
not sure it's really feasible as the API doesn't seem advertised anywhere. fetching images off a raw webpage would be sketchy at best!

**Comment by gingerbeardman** [comment]
Here we go: http://pluginapi.launchbox-app.com

**Comment by gingerbeardman** [comment]
Any further thoughts?

**Comment by KMFDManic** [comment]
@gingerbeardman The primary source for searching is most optimal as it currently stands.  Dan did a little tweaking to keep it from getting hung up on some result types.  As far as launchbox, as you suggested...Excellent idea.  If there is any possible way to have a generalized collection of said arts, we could host them on Google Drive or Mega NZ Link for yours' and others' perusals and usage.  Whenever you want to chat about any of the issues you've opened up or how you might like to proceed with a harmonious solution to them, be sure to let me know on Discord:)
