### ISSUE TITLE
wii classic controller

### ISSUE THREAD

**Issue by arthur071169** [TeamShinkansen/Hakchi2-CE#88]
returning to the menu using the blue 'home' button (wii classic controller) causes the snes mini to freeze.  reset not working when this happens and a power cycle required.

latest hakchi 2ce version running. (1.2.4)

**Comment by DanTheMan827** [comment]
are you using retroarch? if so, which version?

**Comment by ghost** [comment]
FYI 
i have the wii classic controller pro (original) and this does not happen for me. 
hackchi 1.2.4 on KMFDManic-NESC-SNESC-Cores.4-28-18

**Comment by daPhie79** [comment]
probably a retroarch issue, not really feasible for us to diagnose individual controllers :(
