### ISSUE TITLE
cannot synchronize games CE v1.2.4

### ISSUE THREAD

**Issue by massouji82** [TeamShinkansen/Hakchi2-CE#89]
Just upgraded to v1.2.4.

I have already flashed the custom kernel with a previous version of hakchi2 CE but I get prompted that my kernel or scripts are out of date.

When trying to flash the custom kernel I get to 22% before getting the message: "executing command: boota 47400000" before => "please wait while your SNES is rebooting ..." => "your device is taking a long time to reboot. You can wait some more and try the action again if it comes online after a while." 
But nothing happens.

Please help!

**Comment by daPhie79** [comment]
we recommend asking for help on a community like reddit or discord for troubleshooting!
