### ISSUE TITLE
Dual-booting - No Thumbnails Hack for Both Systems

### ISSUE THREAD

**Issue by creeve4** [TeamShinkansen/Hakchi2-CE#90]
I am using Hakchi2 CE 1.2.4.

I setup my SNES to dual boot following these instructions: https://www.reddit.com/r/miniSNESmods/comments/8emp9n/best_way_of_dual_booting_on_snes_classic_for_nes/dxy7u1e/

The No Thumbnails Hack will only work for the system that is booted when I install the mod. If I am booted to SNES and install the mod, it will work for the SNES only. If I am booted to NES and install the mod, it will work for the NES only.

**Comment by KMFDManic** [comment]
@creeve4 No Thumbnails Hack is not recommended for use, and can cause conflicts with some Cores/Games.  It is definitely best to run without it.  It was meant to be more of an example of applied HMOD making, than something to be seriously used.  In several instances, that is one key HMOD, along with various video splash, extra space, memory booster, etc, that have consistently been a culprit to instability in some peoples' setups.
