### ISSUE TITLE
[Suggestion] New type of sorting games

### ISSUE THREAD

**Issue by nandolawson** [TeamShinkansen/Hakchi2-CE#91]
Hello :)

I would love to see the (S)NES Mini folder system to behave more like they would be pages. I don't like the folder system that much and it would be really nice to have a "Next Page" and a "Previous Page" button on the device.

It would be really great if you could add that little suggestion! :)

**Comment by gingerbeardman** [comment]
Imagine you need to find a game beginning with S and you have 100 games.

How many pages would you have to go through to get there starting from A?

**Comment by KMFDManic** [comment]
@nandolawson Although this is a great idea, it wouldn't execute all too well with the very sensitive nature with which folders already react, accordingly, to even the current structure.  Folder changes will be quite minimal, unless safe changes can truly be made which have minimal chances of C8 and other such errors.  Thanks so much for the suggestion, though!  It can be taken into account with any restructure in the future, potentially.
