### ISSUE TITLE
Mod Store Issue

### ISSUE THREAD

**Issue by zweifuss** [TeamShinkansen/Hakchi2-CE#92]
The store isn't downloading a lot of the Retroarch Cores correctly. They end up as 35-60kb small files, all of which are corrupt. Here is a small list of cores that don't download properly from the Mod Store:

CORE_bsnes_mercury_performance.hmod
CORE_mednafen_gba.hmod
CORE_mednafen_ngp.hmod
CORE_mednafen_pce_fast.hmod
CORE_mednafen_supergrafx.hmod
CORE_pcsx_rearmed_neon.hmod
CORE_picodrive.hmod
CORE_pocketcdg.hmod
CORE_pokemini.hmod
CORE_ppsspp_neo.hmod
CORE_prosystem.hmod
CORE_puae.hmod
CORE_px68k.hmod
CORE_reminiscence.hmod
CORE_sameboy.hmod
CORE_scummvm.hmod
CORE_snes9x.hmod
CORE_snes9x2002.hmod
CORE_tgbdual.hmod
CORE_theodore.hmod
CORE_vba_next.hmod
CORE_vbam.hmod
CORE_vecx.hmod
CORE_vice_x64.hmod
CORE_virtualjaguar.hmod
CORE_xrick.hmod
CORE_yabause.hmod

Also, they aren't ordered alphabetically, but I suppose that's a feature request.

**Comment by BananaRama203** [comment]
Appologises this is my fault. Somone was helping me put up the cores on the site and I didn't make the instructions clear so they aren't pointing at the right place. 

Just fixing this now.

**Comment by BananaRama203** [comment]
This is now fixed. The JSON needs to repopulate with the new links but it's been fixed.
