### ISSUE TITLE
malware detection

### ISSUE THREAD

**Issue by acidrain97** [TeamShinkansen/Hakchi2-CE#93]
Just wondering is anyone getting malware detections? I'm sure it's false but it's really screwing with things. I get the detection when adding a directory of games. I have been d/ling the current version of Hakchi 2 CE from github and using Kaspersky. 

thanx

**Comment by madmonkey1907** [comment]
https://www.virustotal.com/en/file/149c00c6b55a6200d62c5cd7e1a15439a8c9bb4388af8929d0179f2a6bb91766/analysis/1526610867/
https://www.virustotal.com/en/file/b3014b69748487d7e849261407dd3be06ee96bb3a7a08fd7f44022ead5197d9c/analysis/1526611175/
https://www.virustotal.com/en/file/f15344c62971f2846a222bbd3b6d3130f2441b21fb1dae9c99f03e71e6d2bd50/analysis/1526611340/
https://www.virustotal.com/en/file/1bf413d893f5cd7181f052bbf416f82a60e84455452110de430f3cd367075dd7/analysis/1526611289/
