### ISSUE TITLE
[REQ] Export Games to system specific structure

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#97]
I now pretty much configured everything for my needs , systems ive got etc..
So this is my first emulation thing ive sorted, imported covers etc.. for. 

I would love to have an option to export my added games into a structure which i could use with another system too, like eg retropie. or at least have a option like export to system structure like

hackchi ce will create a system based structure (maybe based on the core) on a path of my choice like:
TurboGrafics16 -> Gamename -> (put,cover and gamefiles into)
SNES -> Gamename -> (put,cover and gamefiles into)
and so on...

would that be possible?
cheers

**Comment by KMFDManic** [comment]
Unfortunately, this is something I have discussed with madmonkey and DanTheMan827, which can lead to a great deal of confusion...if trying to branch out to too many systems.  I was really pushing for at least Playstation Classic, and potentially Genesis Mini, however!  These would be more feasible and doable than RetroPie.  But, if you need help getting a nice structure set-up for RetroPie, you can always let me know!  I don't mind helping out, outside of the hakchi perimeter:)
