### ISSUE TITLE
USB-Host diff Synchronization not working properly

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#99]
I am on the latest version 1.25 but i have this issue since ever...
im on a usb stick (i`ve tried 3 different usb sticks, so i strongly guess its not related to my sticks themselves) and everytime same issue.

(files are all .iso format)

so what ive done lately to get this issue again:
* added about 6 psp games and synchronized (all good, diff synchro of several gb)
* unplugged usb stick and tested these games on snes mini (shutdown properly, saw no c8 error or similar)
-> then
* deleted 2 of them from hackchi cause of not working smooth
* plugged usb stick into my device again
* moved the left games from the dummy folder through filemanager to my psp folder
* hit synchro

hackchi now does not synchronize the diff, it synchronzies the hole stick. thats *xfsxxd* it takes over two hours for me ;(
is there anything i can do to avoid this?

**Comment by daPhie79** [comment]
so, in the end, you delete 2 games from hakchi and it re synchronizes everything?

what was the folder and file arrangement at first, and what was it after you deleted 2 of them?

diff sync doesn't "understand" when files are moved from one folder to another, or when you delete games and it "slides" back games from folders to folders.

i.e.

```
/001/CLV-A-BCDEF/GAME.ISO
/001/CLV-B-CDEFG/GAME2.ISO
```

then you makes changes and it ends up:

```
/001/CLV-A-BCDEF/GAME.ISO
/002/CLV-B-CDEFG/GAME2.ISO (changed folder)
```

hakchi will recopy the second game in its entirety. and it's unfortunately not a bug, but a missing feature that is much more complicated to implement.

**Comment by ghost** [comment]
the folder structure is untouched as i just test and move added games each time.
indeed ive moved the tested games from the default directory to my desired directory.

**Comment by ghost** [comment]
this behavior exist also if you just delete a game and change the emulation core without moving anything else... definitly a feature i would like to have...
unlikely its difficult.. nice to have but no major thing :)

**Comment by daPhie79** [comment]
the diff sync algorithm is very sensitive lol it's directly tied to the full path of a file. we may improve eventually :) sorry if it's not the most convenient right now.

**Comment by KMFDManic** [comment]
@AntiFly Just going through the issues:)  You can technically run (copy your entire directory) Hakchi from the Flash Drive/Hard Drive, with linked sync option on.  And, the games should do the "diff" without issue, nowadays.  They would symlink like desktop shortcuts on a PC.  But, some games don't fare as well with symlinks, such as some of the ones that have dependencies, like AGA Amiga games.  Luckily, most Amiga games run fine with "direct loading" now!  Again, keep me posted on any ideas or suggestions you may still have, mate:)
